In [2]:
from pyalex import (
    Works, Authors, Sources,
    Institutions, Concepts, Publishers, Funders
)
import pyalex
import pandas as pd
import numpy as np
pyalex.config.email = "david@rs21.io"

from flair.embeddings import DocumentPoolEmbeddings
from flair.data import Sentence
from flair.embeddings import SentenceTransformerDocumentEmbeddings

EMBEDDING_MODEL_1 = "all-mpnet-base-v2" 

# this one is also good: all-MiniLM-L6-v2
EMBEDDING_MODEL_2 = "all-MiniLM-L6-v2"
SENT_EMBEDDINGS_1 = SentenceTransformerDocumentEmbeddings(EMBEDDING_MODEL_1)
SENT_EMBEDDINGS_2 = SentenceTransformerDocumentEmbeddings(EMBEDDING_MODEL_2)
DOC_EMBEDDINGS= DocumentPoolEmbeddings([SENT_EMBEDDINGS_2])

import torch
from tqdm import tqdm
import yake
import umap.umap_ as umap
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.mixture import GaussianMixture as GMM
import altair as alt
import math
import plotly.express as px
import textwrap

In [3]:
search_term = 'missile'
robot_concepts = Concepts().search_filter(display_name=search_term).get()
len(robot_concepts)
for i in range(len(robot_concepts)):
    id_, display_name = robot_concepts[i]['id'], robot_concepts[i]['display_name']
    print(id_, display_name)

https://openalex.org/C2778857364 Missile
https://openalex.org/C522053795 Missile guidance
https://openalex.org/C122136912 Ballistic missile
https://openalex.org/C559253537 Missile defense
https://openalex.org/C28849524 Cruise missile
https://openalex.org/C202802212 Air-to-air missile

In [4]:
results, meta  = Concepts().get(return_meta=True)
print(meta)

{'count': 65073, 'db_response_time_ms': 58, 'page': 1, 'per_page': 25, 'groups_count': None}

In [5]:
search_term = 'jamming'
search_term = 'radar jamming and deception|electronic warfare|Network-centric warfare|Air-to-air missile'
search_term = ('radar jamming and deception|electronic warfare|Network-centric warfare|missile guidance' +
               '|Robot manipulator|Automatic target recognition' + 
              '|Pulsed power|High-energy X-rays' + 
              '|Ballistic missile|Air-to-air missile' + 
              '|terminal guidance')
jamming_concepts = Concepts().\
search_filter(display_name=search_term).get()

In [6]:
concepts = []
for i in range(len(jamming_concepts)):
    id_, display_name = jamming_concepts[i]['id'], jamming_concepts[i]['display_name']
    concepts.append((id_, display_name))
concepts

[('https://openalex.org/C2985527887', 'Robot manipulator'),
 ('https://openalex.org/C97039730', 'Pulsed power'),
 ('https://openalex.org/C522053795', 'Missile guidance'),
 ('https://openalex.org/C117623542', 'Automatic target recognition'),
 ('https://openalex.org/C122136912', 'Ballistic missile'),
 ('https://openalex.org/C176381164', 'Radar jamming and deception'),
 ('https://openalex.org/C183838350', 'High-energy X-rays'),
 ('https://openalex.org/C133082901', 'Electronic warfare'),
 ('https://openalex.org/C2777047555', 'Terminal guidance'),
 ('https://openalex.org/C2781187084', 'Network-centric warfare'),
 ('https://openalex.org/C202802212', 'Air-to-air missile')]

In [23]:
def process_works_list(worklist:list):
    """
    transforms the 
    works list into a dataframe.
    """
    abstracts_dict = {h["id"]:h["abstract"] for h in worklist}
    df = pd.DataFrame.from_records(worklist)
    try: 
        del df['abstract_inverted_index'] # though don't all have abstracts is the problem
        df['abstract'] = df['id'].map(abstracts_dict)
    except:
        pass
   # df['author_affils'] = df['authorships'].apply(get_authors_and_affils)
    return df

In [24]:
for i in range(len(jamming_concepts)):
    print(jamming_concepts[i]['id'], jamming_concepts[i]['works_count'])

https://openalex.org/C2985527887 10153
https://openalex.org/C97039730 14094
https://openalex.org/C522053795 6487
https://openalex.org/C117623542 3634
https://openalex.org/C122136912 6210
https://openalex.org/C176381164 2671
https://openalex.org/C183838350 1184
https://openalex.org/C133082901 3471
https://openalex.org/C2777047555 1355
https://openalex.org/C2781187084 1799
https://openalex.org/C202802212 1313

In [25]:
def get_hpm_frame():
    #hpm_pager = Works().filter(publication_year='>2020').search("high power microwave").\
#filter(authorships={"institutions":{"country_code":"CN"}}).paginate(per_page=200,
#                                                                    n_max=None)
    hpm_pager = Works().filter(publication_year='>2020').search("high power microwave").\
        paginate(per_page=200,  n_max=None)
    df = pd.DataFrame()
    for page in tqdm(hpm_pager):
        dfpage = process_works_list(page)
        df = pd.concat([df, dfpage], ignore_index=True)
        df.drop_duplicates(subset='id', keep='first',inplace=True)
    return df

In [26]:
def get_sbl_frame():
    #sbl_pager = Works().filter(publication_year='>2020').search("space based laser").\
#filter(authorships={"institutions":{"country_code":"CN"}}).paginate(per_page=200,
#                                                                    n_max=None)
    sbl_pager = Works().filter(publication_year='>2020').search("space based laser").\
        paginate(per_page=200,
                                                                    n_max=None)
    df = pd.DataFrame()
    for page in tqdm(sbl_pager):
        dfpage = process_works_list(page)
        df = pd.concat([df, dfpage], ignore_index=True)
        df.drop_duplicates(subset='id', keep='first',inplace=True)
    return df

In [27]:
def get_kkv_frame():
    #kkv_pager = Works().filter(publication_year='>2020').search("kinetic kill vehicle").\
#filter(authorships={"institutions":{"country_code":"CN"}}).paginate(per_page=200,
#                                                                    n_max=None)
    kkv_pager = Works().filter(publication_year='>2020').search("kinetic kill vehicle").\
        paginate(per_page=200,
                                                                    n_max=None)
    df = pd.DataFrame()
    for page in tqdm(kkv_pager):
        dfpage = process_works_list(page)
        df = pd.concat([df, dfpage], ignore_index=True)
        df.drop_duplicates(subset='id', keep='first',inplace=True)
    return df

In [28]:
def get_rka_frame():
   # rka_pager = Works().filter(publication_year='>2020').search("relativistic klystron amplifier").\
#filter(authorships={"institutions":{"country_code":"CN"}}).paginate(per_page=200,
#                                                                    n_max=None)
    rka_pager = Works().filter(publication_year='>2020').search("relativistic klystron amplifier").\
        paginate(per_page=200,
                                                                    n_max=None)
    df = pd.DataFrame()
    for page in tqdm(rka_pager):
        dfpage = process_works_list(page)
        df = pd.concat([df, dfpage], ignore_index=True)
        df.drop_duplicates(subset='id', keep='first',inplace=True)
    return df

In [29]:
def get_concept_frame(concepts_list:list, i:int):
    """
    takes a list of Concepts() results and an index
    and forms the pagination object to retrive the 
    records
    """
    pager = Works().filter(publication_year='>2016',
    #concepts={"id":f"{concepts_list[i]['id']}"}).filter(authorships={"institutions":{"country_code":"CN"}}).\
    #paginate(per_page=200,n_max=None)
    concepts={"id":f"{concepts_list[i]['id']}"}).\
    paginate(per_page=200,n_max=None)
    df = pd.DataFrame()
    for page in tqdm(pager):
        dfpage = process_works_list(page)
        df = pd.concat([df, dfpage], ignore_index=True)
        df.drop_duplicates(subset='id', keep='first',inplace=True)
    return df

In [30]:
frames_list = []
for i in range(len(jamming_concepts)):
    df = get_concept_frame(jamming_concepts, i)
    frames_list.append(df)

14it [00:12,  1.08it/s]
16it [00:25,  1.62s/it]
8it [00:14,  1.80s/it]
8it [00:14,  1.85s/it]
7it [00:08,  1.24s/it]
6it [00:07,  1.31s/it]
2it [00:02,  1.08s/it]
6it [00:10,  1.77s/it]
3it [00:03,  1.04s/it]
3it [00:03,  1.02s/it]
2it [00:01,  1.02it/s]

In [37]:
frames_list[3]['created_date'].max()

'2024-05-14'

In [42]:
frames_list[2]['abstract'].value_counts(dropna=False)

None                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     92
Pursuit-evasion differential games using the Disturbance Attenuation approach are revisited. Under this approach, the pursuer actions are considered to be control actions, whereas all external actions, such as target maneuvers, measurement errors and initial position uncertainties, are considered to be disturbances. Two open issues have been addressed, namely the effect of noise on the control gains, and the effect of trajectory shaping on the solution. These issues are closely related to the question of the best choice for the disturbance attenuation ratio. Detailed analyses are performed for two simple pursuit-evasion cases: a Simple Boat Guidance Problem and Missile Guidance Engagement.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2
The great developments in applied mathematics and computational capabilities facilitate the design and implementation of robust control. Among the real applications are the guided missiles especially the antitank guided missile systems which are commanded to the line of sight (CLOS) against ground and short-range targets. The present work is concerned with improving the performance of an antitank guided missile system belonging to the first generation via robust synthesis of guidance systems. The selection of nominal model is required to design the guidance computer for the system. This paper is devoted to the quantitative analysis to select a nominal plant which used to design a guidance computer that has a successful flight path trajectory against different types of uncertainties. The design and analysis necessitate somehow accurate model with different uncertainties for the system. The flight path is evaluated considering the HIL environment.                                                                                                                                                                                                                                                                                           2
According to the analysis of trends in the use and development of missile weapons, it is shown that in the coming decades such weapons (missile, anti-aircraft missile, anti-ship systems) will remain one of the main units of the armed forces of the advanced countries. At the same time, in the conditions of independent Ukraine there is a need to create its own production of appropriate samples in a “closed cycle”. The synthesis of such weapons includes conducting comprehensive research on the principles of construction and operation of their basic elements, namely: substantiation of algorithms for launch equipment, control systems and navigation of missiles. The article deals with an example of a general solution to the problem.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2
The frequent minor wars have brought to the fore guided missiles as the main weapon against all types of military targets. Restoring the single shot kill probability can be achieved by using two methods as follows: first, using large warhead with the large lethal area; second, design a robust guidance system to reduce the miss-distance with high single shot kill probability. The performance of an anti-tank guided missile can be enhanced by select the nominal model to design the guidance computer system. Furthermore, an online closed-loop system identification is required to adaptive autopilot design. This paper is devoted to using system identification in position control robotic benchmark via open and closed loops system identification. Hence, applying the closed-loop methods to identify the actuator and airframe of the intended plant in order to design a self-tuning controller. The online system identification is based on the recursive least square method.                                                                                                                                                                                                                                                                              2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ..
This paper contributes to a modified guidance scheme based on a trajectory tracking method which is dedicated for an artillery rocket with a finite set of single use solid propellant side thrusters.Frequency modulation of pulses was used to achieve effective firing logic.The proposed control law is applicable in the last phase of flight when the rocket reaches the vertex of the trajectory.A correction engine activation sequence was chosen in such a way that possibility of rocket axial unbalance is minimized due to motors firing.Numerical simulation results indicate that significant dispersion reduction was achieved and the number of activated side rocket thrusters is minimized.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
Abstract In order to realize air-ground integration strike capability of the fortification storming/HEAT missiles, with the study background of addition of a laser proximity fuze to the missile, this paper proposes a fuze-guidance integration design method based on combination of image guidance and laser proximity fuze detection. By utilizing the missile-target encounter images, the gimbal angle of the seeker, the velocity and attitude of the missile, as well as the bearing and distance of the target detected by the laser proximity fuze, our design method establishes the space geometric equations of the relative motion of the missile and target, and of the equivalent conical plane of the dispersion center of the warhead fragments in the coordinate system of the missile body. Meanwhile, by solving the equations, a fully formulaic optimal time delay model of fuze-warhead matching is obtained, and the optimal detonation time of the warhead is given. The results show that this integration design method can effectively improve the damage effect of the missile on the helicopter target under complex encountering conditions, and realize the integrated air-to-ground strike capability of the fortification storming/HEAT missile.     1
In this paper, two open-loop cooperative guidance laws are proposed. First, a new time cooperative proportional navigation guidance (TCPNG) law is proposed based on the conventional proportional navigation guidance (PNG) law. In order to meet the impact time cooperative requirement, the navigation gain in the TCPNG law is designed as the function of the time error, which is the difference between the designated impact time and the time-to-go estimation of the missile. Second, an improved impact time control guidance (IITCG) law is proposed based on the existing impact time control guidance (ITCG) law. When the initial leading angle is large, the ITCG law may fail and there will be a singularity in the denominator in the later period of the guidance, which will cause the control instruction to oscillate. Therefore, the IITCG law is proposed to cope with this problem. Simulation results show that the TCPNG law can be applied to different initial leading angles and the salvo attack scenario. And the IITCG law can avoid the singularity in the later period of the guidance law, which solves the problem of the control instruction oscillation.                                                                                         1
The paper describes the methodology and the design process of a Model Predictive Controller (MPC) that has been applied to solve Missile-on-Missile Interception. The MPC combines the control and guidance laws to create an ideal control law with much higher performance and guarantees strike with a wide range of target and missile parameters. The MPC is also able to handle actuator delay and hence is more practically suited than traditional guidance/control schemes. Also, MPC satisfies sensor/seeker angle constraints, actuator constraints, angle of attack constraints, and fin deflection angle constraints, thus making it more versatile and powerful than any analytical method-based control/guidance schemes. The only disadvantage is the higher computational cost requirements, which will be easily mitigated in the future with the advancements of powerful microprocessors. The performance of the MPC is demonstrated in simulations where the missile is a standard supersonic missile but the target is a maneuvering hypersonic missile with initial separation of just a few kilometers.                                                                                                                                                           1
For missile defense systems, the sooner the group target split tracking of ballistic missile is completed, the more preparation time there will be. On the other hand, the group target split tracking too early may cause problems such as mixed tracking, wrong tracking and resources saturation during radar tracking process, which affect the combat performance of weapon systems. A group splitting algorithm for ballistic missile target tracking is proposed in this paper. First, the formation of group targets and the tracking strategy is analyzed, and the IMM-UKF filter framework is described. Then the mathematical model of the group splitting algorithm is established. The factors that affect the performance of the group splitting are discussed. Finally the multi-object optimization problem is solved by using Pareto method. Simulation and experimental results prove that the proposed algorithm can reach a balance between the instant splitting of group targets and the target association stability in a group.                                                                                                                                                                                                                                   1
Name: abstract, Length: 1119, dtype: int64

In [43]:
len(frames_list)

11

In [44]:
dftop = pd.concat(frames_list,
                  ignore_index=True)
dftop.drop_duplicates(subset='id', keep='first', 
                      inplace=True)

dftop.set_index('id', inplace=True, drop=False)

dfall = dftop
print(dfall.shape)

dfall['content'] = dfall['title'] + ". " + dfall['abstract']

dfrecords = dfall[~dfall['content'].isna()].copy()

(10889, 49)

In [45]:
def get_keywords(text:str, top:int=7, stopwords=None):
    """
    takes a blob of text and 
    returns the top **top** 
    keywords as a list
    """
    kw_extractor = yake.KeywordExtractor(top=top, stopwords=stopwords)
    keywords = kw_extractor.extract_keywords(text)
    return [p[0] for p in keywords]

In [46]:
def get_top_concepts(concept_list:list,score:float=.6):
    """
    takes a list of concept dictionaries 
    returns the top **top** display_names;
    concepts whose score is >= score
    """
    return [c['display_name'] for c in concept_list if c['score'] >= score]

In [47]:
dfrecords['keywords'] = dfrecords['content'].apply(get_keywords)
dfrecords['top_concepts'] = dfrecords['concepts'].apply(get_top_concepts)

In [48]:
texts = dfrecords['content'].str.lower().values.tolist()

In [49]:
def get_content_embeddings(dfrecords:pd.DataFrame) -> pd.DataFrame:
    """
    passes the preprocessed mitigation strings
    data through the embedding model to produce the vector
    space representation of each pet mitigation.
    """
    sent = Sentence("The grass is green.")
    DOC_EMBEDDINGS.embed(sent)
    texts = dfrecords["content"].str.lower().values.tolist()
    all_descriptions = np.empty((len(texts), len(sent.embedding)))
    for i in tqdm(range(len(texts))):
        sent = Sentence(texts[i])
        DOC_EMBEDDINGS.embed(sent)
        all_descriptions[i, :] = sent.embedding.cpu().numpy()
        # gc.collect()
        torch.cuda.empty_cache()
    dfcontentvectors = pd.DataFrame.from_records(all_descriptions, index=dfrecords.index)
    return dfcontentvectors

In [50]:
dfcontentvectors = get_content_embeddings(dfrecords)

100%|█████████████████████████████████████████████████████████████████████| 9301/9301 [02:20<00:00, 66.08it/s]

In [51]:
#umap.UMAP?
N_COMPONENTS = 2 # can visualize this way
umap_reducer = umap.UMAP(n_components=N_COMPONENTS,
                       #  metric='euclidean')
                         random_state=1234,
                         metric='cosine')  # can experiment with this metric as well as the other 
# parameters
# to see what other literature is in the same information space, we need to keep this umap_reducer 
# object as well as the gmm model below.

# Apply UMAP to the vectorized strings
reduced_vectors = umap_reducer.fit_transform(dfcontentvectors.to_numpy())
dfreduced = pd.DataFrame.from_records(reduced_vectors, 
                index=dfcontentvectors.index)
dfreduced.columns = ['x','y']

/home/davidd/.local/lib/python3.10/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

# use hdbscan to cluster

In [52]:
import hdbscan

hdbscan_args = {'min_cluster_size': 15,
                            'metric': 'euclidean',
                            'cluster_selection_method': 'eom',
                            'cluster_selection_epsilon': 0.1
               }

cluster = hdbscan.HDBSCAN(**hdbscan_args).fit(dfreduced[['x','y']].to_numpy())

dfreduced['cluster'] = cluster.labels_
dfreduced['probability'] = cluster.probabilities_

dfpapers = dfrecords.merge(dfreduced, left_index=True,
                           right_index=True)

In [53]:
#help(dfpapers.explode)
del dfpapers['id']
dfstart = dfpapers.reset_index()
dfstart.head()

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,created_date,fulltext_origin,abstract,is_authors_truncated,content,top_concepts,x,y,cluster,probability
0,https://openalex.org/W1517236425,https://doi.org/10.1201/9781003062714,Neural Network Control Of Robot Manipulators A...,Neural Network Control Of Robot Manipulators A...,2020,2020-08-13,{'openalex': 'https://openalex.org/W1517236425...,en,"{'is_oa': False, 'landing_page_url': 'https://...",book,...,2016-06-24,NaN,"There has been great interest in ""universal co...",NaN,Neural Network Control Of Robot Manipulators A...,"[Robot manipulator, Artificial neural network]",13.341581,-6.582227,1,1.0
1,https://openalex.org/W2740675802,https://doi.org/10.1109/tcyb.2017.2711961,Adaptive Neural Network Control of a Robotic M...,Adaptive Neural Network Control of a Robotic M...,2017,2017-10-01,{'openalex': 'https://openalex.org/W2740675802...,en,"{'is_oa': False, 'landing_page_url': 'https://...",article,...,2017-08-08,ngrams,The control problem of an uncertain n -degrees...,NaN,Adaptive Neural Network Control of a Robotic M...,"[Control theory (sociology), Lyapunov function...",13.561797,-7.088242,1,1.0
2,https://openalex.org/W2418767125,https://doi.org/10.1109/tsmc.2016.2562506,Neural Network Control of a Flexible Robotic M...,Neural Network Control of a Flexible Robotic M...,2017,2017-08-01,{'openalex': 'https://openalex.org/W2418767125...,en,"{'is_oa': False, 'landing_page_url': 'https://...",article,...,2016-06-24,ngrams,Adaptive neural networks (NNs) are employed fo...,NaN,Neural Network Control of a Flexible Robotic M...,"[Control theory (sociology), Deflection (physi...",13.269590,-6.870666,1,1.0
3,https://openalex.org/W2901112449,https://doi.org/10.1109/tro.2018.2878318,Model-Based Reinforcement Learning for Closed-...,Model-Based Reinforcement Learning for Closed-...,2019,2019-02-01,{'openalex': 'https://openalex.org/W2901112449...,en,"{'is_oa': False, 'landing_page_url': 'https://...",article,...,2018-11-29,pdf,Dynamic control of soft robotic manipulators i...,NaN,Model-Based Reinforcement Learning for Closed-...,"[Control theory (sociology), Kinematics, Reinf...",11.222045,-7.583316,1,1.0
4,https://openalex.org/W2792852625,https://doi.org/10.1016/j.neucom.2018.01.002,Robot manipulator control using neural network...,Robot manipulator control using neural network...,2018,2018-04-01,{'openalex': 'https://openalex.org/W2792852625...,en,"{'is_oa': False, 'landing_page_url': 'https://...",article,...,2018-03-29,ngrams,Robot manipulators are playing increasingly si...,NaN,Robot manipulator control using neural network...,"[Artificial neural network, Computer science]",13.152991,-6.284923,1,1.0

In [54]:
dfstart['publication_year'].value_counts(dropna=False)

2022    1402
2023    1399
2021    1316
2019    1287
2018    1231
2020    1222
2017    1147
2024     297
Name: publication_year, dtype: int64

In [55]:
dfstart.shape

(9301, 55)

In [56]:
dfbig = dfstart.explode(column='authorships')
dfbig.shape, dfstart.shape

((37236, 55), (9301, 55))

In [57]:
dfbig.columns

Index(['id', 'doi', 'title', 'display_name', 'publication_year',
       'publication_date', 'ids', 'language', 'primary_location', 'type',
       'type_crossref', 'indexed_in', 'open_access', 'authorships',
       'countries_distinct_count', 'institutions_distinct_count',
       'corresponding_author_ids', 'corresponding_institution_ids', 'apc_list',
       'apc_paid', 'has_fulltext', 'cited_by_count',
       'cited_by_percentile_year', 'biblio', 'is_retracted', 'is_paratext',
       'primary_topic', 'topics', 'keywords', 'concepts', 'mesh',
       'locations_count', 'locations', 'best_oa_location',
       'sustainable_development_goals', 'grants', 'datasets', 'versions',
       'referenced_works_count', 'referenced_works', 'related_works',
       'ngrams_url', 'cited_by_api_url', 'counts_by_year', 'updated_date',
       'created_date', 'fulltext_origin', 'abstract', 'is_authors_truncated',
       'content', 'top_concepts', 'x', 'y', 'cluster', 'probability'],
      dtype='object')

In [58]:
dfbig.locations.iloc[68]

[{'is_oa': False,
  'landing_page_url': 'https://doi.org/10.1109/tsmc.2020.2999485',
  'pdf_url': None,
  'source': {'id': 'https://openalex.org/S4210209078',
   'display_name': 'IEEE transactions on systems, man, and cybernetics. Systems',
   'issn_l': '2168-2216',
   'issn': ['2168-2216', '2168-2232'],
   'is_oa': False,
   'is_in_doaj': False,
   'host_organization': 'https://openalex.org/P4310319808',
   'host_organization_name': 'Institute of Electrical and Electronics Engineers',
   'host_organization_lineage': ['https://openalex.org/P4310319808'],
   'host_organization_lineage_names': ['Institute of Electrical and Electronics Engineers'],
   'type': 'journal'},
  'license': None,
  'license_id': None,
  'version': None,
  'is_accepted': False,
  'is_published': False}]

In [59]:
def add_extra_to_authorships(row: pd.DataFrame):
    """
    row[authorships] is a dictionary;
    add in the id key to that dictionary
    whose value is row[id]
    """
    complete_dict = row["authorships"]
   # assert type(complete_dict) == dict
    #print(type(complete_dict))
    if type(complete_dict) == dict:
        complete_dict["id"] = row["id"]
        complete_dict["x"] = row["x"]
        complete_dict["y"] = row["y"]
        complete_dict["cluster"] = row["cluster"]
        complete_dict["cluster_score"] = row["probability"]
        complete_dict["title"] = row["title"]
        complete_dict["abstract"] = row["abstract"]
        complete_dict["doi"] = row["doi"]
        complete_dict["publication_date"] = row["publication_date"]
        complete_dict["publication_year"] = row["publication_year"]
        complete_dict["grants"] = row["grants"]
        complete_dict["locations"] = row["locations"]
        return complete_dict
    else:
        return row["authorships"]

In [60]:
dfbig['big_authorships'] = dfbig.apply(add_extra_to_authorships, axis=1)

In [83]:
dfbig.columns

Index(['id', 'doi', 'title', 'display_name', 'publication_year',
       'publication_date', 'ids', 'language', 'primary_location', 'type',
       'type_crossref', 'indexed_in', 'open_access', 'authorships',
       'countries_distinct_count', 'institutions_distinct_count',
       'corresponding_author_ids', 'corresponding_institution_ids', 'apc_list',
       'apc_paid', 'has_fulltext', 'cited_by_count',
       'cited_by_percentile_year', 'biblio', 'is_retracted', 'is_paratext',
       'primary_topic', 'topics', 'keywords', 'concepts', 'mesh',
       'locations_count', 'locations', 'best_oa_location',
       'sustainable_development_goals', 'grants', 'datasets', 'versions',
       'referenced_works_count', 'referenced_works', 'related_works',
       'ngrams_url', 'cited_by_api_url', 'counts_by_year', 'updated_date',
       'created_date', 'fulltext_origin', 'abstract', 'is_authors_truncated',
       'content', 'top_concepts', 'x', 'y', 'cluster', 'probability',
       'big_authorships'],
      dtype='object')

In [85]:
dfbig['authorships'].iloc[69] # raw_affiliation_strings

{'author_position': 'middle',
 'author': {'id': 'https://openalex.org/A5029350515',
  'display_name': 'Wenkang Zhan',
  'orcid': None},
 'institutions': [{'id': 'https://openalex.org/I90610280',
   'display_name': 'South China University of Technology',
   'ror': 'https://ror.org/0530pts50',
   'country_code': 'CN',
   'type': 'education',
   'lineage': ['https://openalex.org/I90610280']}],
 'countries': ['CN'],
 'is_corresponding': False,
 'raw_author_name': 'Wenkang Zhan',
 'raw_affiliation_strings': ['School of Automation Science and Engineering South China University of Technology, Guangzhou 510640, China'],
 'id': 'https://openalex.org/W3037315148',
 'x': 12.566542625427246,
 'y': -7.863014221191406,
 'cluster': 1,
 'cluster_score': 1.0,
 'title': 'Boundary Control of a Rotating and Length-Varying Flexible Robotic Manipulator System',
 'abstract': 'This article copes with vibration suppression and angular position tracking problems of a robotic manipulator system comprised of a rotating hub and a length-varying manipulator. To obtain precise dynamic response, the manipulator system is modeled in infinite-dimension with partial differential equations. S-curve acceleration/deceleration (S-CA/D) scheme is employed for speed regulation of the length-varying manipulator. Two novel observers are developed to estimate both the unknown disturbances and their time-derivatives, and two auxiliary systems are put forward to tackle input constraints. With assistance of the auxiliary systems and observers, two boundary control laws are put forward to manage vibration suppression and angular position tracking of the proposed manipulator system. Through Lyapunov’s theory, the closed-loop system is proved to be bounded. Numerical simulations have displayed the effectiveness of the observers and boundary control laws.',
 'doi': 'https://doi.org/10.1109/tsmc.2020.2999485',
 'publication_date': '2022-01-01',
 'publication_year': 2022,
 'grants': [{'funder': 'https://openalex.org/F4320321001',
   'funder_display_name': 'National Natural Science Foundation of China',
   'award_id': '61203060'},
  {'funder': 'https://openalex.org/F4320321001',
   'funder_display_name': 'National Natural Science Foundation of China',
   'award_id': '61803098'},
  {'funder': 'https://openalex.org/F4320335795',
   'funder_display_name': 'Science and Technology Planning Project of Guangdong Province',
   'award_id': '2019A050510015'},
  {'funder': 'https://openalex.org/F4320335795',
   'funder_display_name': 'Science and Technology Planning Project of Guangdong Province',
   'award_id': '2016B010126001'},
  {'funder': 'https://openalex.org/F4320335795',
   'funder_display_name': 'Science and Technology Planning Project of Guangdong Province',
   'award_id': '2016B090927010'}],
 'locations': [{'is_oa': False,
   'landing_page_url': 'https://doi.org/10.1109/tsmc.2020.2999485',
   'pdf_url': None,
   'source': {'id': 'https://openalex.org/S4210209078',
    'display_name': 'IEEE transactions on systems, man, and cybernetics. Systems',
    'issn_l': '2168-2216',
    'issn': ['2168-2216', '2168-2232'],
    'is_oa': False,
    'is_in_doaj': False,
    'host_organization': 'https://openalex.org/P4310319808',
    'host_organization_name': 'Institute of Electrical and Electronics Engineers',
    'host_organization_lineage': ['https://openalex.org/P4310319808'],
    'host_organization_lineage_names': ['Institute of Electrical and Electronics Engineers'],
    'type': 'journal'},
   'license': None,
   'license_id': None,
   'version': None,
   'is_accepted': False,
   'is_published': False}]}

In [86]:
#dfbig['authorships'].tolist()
bigvals = dfbig['authorships'].tolist()

In [87]:
dictvals = [c for c in bigvals if type(c) != float]

In [92]:
dictvals[0]['author'].keys()

dict_keys(['id', 'display_name', 'orcid'])

raw_affiliation_string -> raw_affiliation_strings

In [93]:
dftriple = pd.json_normalize(dictvals,
                  record_path=['institutions'],
                  meta=['id','raw_affiliation_strings','author_position', 'doi',
                        'title','abstract','publication_date', 'publication_year',
                        'grants','locations',
                        'is_corrresponding','x','y','cluster','cluster_score',
                       ['author','id'], ['author', 'display_name'],
                       ['author','orcid']],
                  errors='ignore',
                  sep='_',
                  meta_prefix='paper_',
                #  record_prefix='author_'
                 )

In [94]:
dftopics = dfcontentvectors.copy()
dftopics['cluster'] = dfpapers['cluster']
dfmeantopics = dftopics.groupby('cluster').mean().copy()
reduced_topics = umap_reducer.transform(dfmeantopics.to_numpy())
df_reduced_topics = pd.DataFrame.from_records(reduced_topics, 
                index=dfmeantopics.index)
df_reduced_topics.columns = ['x','y']
df_reduced_topics['topic'] = df_reduced_topics.index
df_reduced_topics.head()

def get_cluster_concepts(topic_num:int, n:int=20):
    """
    takes an integer topic_num corresponding to a 
    given topic number and
    returns the list of top n occuring concepts
    from the top_concept field
    """
    top_concepts = dfpapers[dfpapers['cluster'] == topic_num]['top_concepts'].tolist()
    flat_concepts = [item for sublist in top_concepts for item in sublist]
    concepts_dict = {c:flat_concepts.count(c) for c in flat_concepts}
    sorted_concepts = sorted(concepts_dict.items(), key=lambda x:x[1], reverse=True)
    return [c[0] for c in sorted_concepts][:n]

def get_yake_cluster_phrases(topic_num:int, n:int=20):
    """
    takes in an integer n corresponding
    to a given topic number and
    returns the list of keyphrases (TopicRank method)
    """
    documents = dfpapers[dfpapers['cluster'] == topic_num]['content'].tolist()
    topic_input = ". ".join(documents)
    #extractor = pke.unsupervised.TextRank()
    kw_extractor = yake.KeywordExtractor(top=n, stopwords=None)
    keywords = kw_extractor.extract_keywords(topic_input)
    #extractor.load_document(input=topic_input,
    #                    language='en',
    #                    normalization=None)

    #extractor.candidate_selection()

    #window = 2
    #use_stems = False
    #extractor.candidate_weighting(window=window,
    #                          use_stems=use_stems)
    #extractor.candidate_weighting()
    #threshold = 0.8
   # keyphrases = extractor.get_n_best(n=20, threshold=threshold)
    #keyphrases = extractor.get_n_best(n=n)
    return [p[0] for p in keywords]

wikiconcepts = df_reduced_topics['topic'].apply(get_cluster_concepts)

wikikeywords = df_reduced_topics['topic'].apply(get_yake_cluster_phrases)

dfpapers['id'] = dfpapers.index
dfinfo = dfpapers[['x','y','id','title','doi','cluster','grants',
                   'locations',
                 'publication_date','keywords','top_concepts']].copy()

centroids = dfinfo.groupby('cluster')[['x','y']].mean().copy()
centroids['concepts'] = wikiconcepts
centroids['cluster'] = centroids.index
centroids['keywords'] = wikikeywords

In [95]:
def wrap_it(x):
    return "<br>".join(textwrap.wrap(x, width=40))
   # return "<br>".join(textwrap.wrap(x.replace(r'\s+', ' '), width=40))

In [96]:
centroids['wrapped_keywords'] = centroids['keywords'].apply(str).apply(wrap_it)
centroids['wrapped_concepts'] = centroids['concepts'].apply(str).apply(wrap_it)

In [97]:
centroids.to_pickle('updatejammingcentroids2d.pkl')

In [98]:
dftriple.to_pickle('updatejammingdftriple2d.pkl')

In [99]:
def get_affils_cluster_sort(dc:pd.DataFrame, cl:int):
    """
    restricts the dataframe dc to cluster value cl
    and returns the results grouped by id, ror sorted
    by the some of probablity descending
    """
    dg = dc[dc['paper_cluster'] == cl].copy()
    print(cl)
    dv = dg.groupby(['id','display_name','country_code',
                     'type'])['paper_cluster_score'].sum().to_frame()
    dv.sort_values('paper_cluster_score', ascending=False, inplace=True)
    kw = centroids[centroids.cluster == cl]['keywords'].iloc[0]
    return dv, kw

In [100]:
dv84, kw84 = get_affils_cluster_sort(dftriple, 1)
print(kw84)
dv84.head(10)

1
['robotic manipulator system', 'Robotic Manipulator', 'Robotic Manipulator Control', 'Robot manipulator', 'Sliding Mode Control', 'Flexible Robotic Manipulator', 'robotic manipulator based', 'redundant robot manipulators', 'manipulator control system', 'Timoshenko robotic manipulator', 'industrial robot manipulator', 'Robot Manipulators Based', 'Robotic Arm Manipulator', 'control robotic manipulators', 'Robot Manipulators Control', 'DOF Robotic Manipulator', 'Soft Robotic Manipulators', 'robot manipulator systems', 'Manipulator Robotic Control', 'Manipulator']

                                                                                                     paper_cluster_score
id                              display_name                                 country_code type
https://openalex.org/I204983213 Harbin Institute of Technology               CN           education                 83.0
https://openalex.org/I125839683 Beijing Institute of Technology              CN           education                 67.0
https://openalex.org/I90610280  South China University of Technology         CN           education                 51.0
https://openalex.org/I19820366  Chinese Academy of Sciences                  CN           government                51.0
https://openalex.org/I92403157  University of Science and Technology Beijing CN           education                 49.0
https://openalex.org/I157773358 Sun Yat-sen University                       CN           education                 47.0
https://openalex.org/I62916508  Technical University of Munich               DE           education                 42.0
https://openalex.org/I47508984  Imperial College London                      GB           education                 40.0
https://openalex.org/I40542001  University of Ulsan                          KR           education                 40.0
https://openalex.org/I197347611 Korea University                             KR           education                 39.0

In [101]:
dv84, kw84 = get_affils_cluster_sort(dftriple, 0)
print(kw84)
dv84.head(10)

0
['Aerial Manipulator', 'Aerial Manipulator Robot', 'Aerial Robotic Manipulators', 'Aerial', 'Manipulator', 'Aerial Manipulator System', 'unmanned aerial vehicle', 'aerial manipulator control', 'Control Aerial Manipulator', 'aerial manipulation', 'Aerial Robotic', 'aerial manipulator vehicle', 'aerial vehicle', 'Protocentric Aerial Manipulators', 'proposed aerial manipulator', 'Unmanned aerial', 'Robotic Manipulator', 'control', 'Aerial Robotic System', 'robotic arm']

                                                                                                            paper_cluster_score
id                               display_name                                       country_code type
https://openalex.org/I190497903  Laboratory for Analysis and Architecture of Sys... FR           facility               8.45873
https://openalex.org/I118946981  Escuela Politécnica del Ejército                   EC           education             8.124794
https://openalex.org/I1294671590 French National Centre for Scientific Research     FR           government            7.006282
https://openalex.org/I17866349   Université de Toulouse                             FR           education             7.006282
https://openalex.org/I71267560   University of Naples Federico II                   IT           education                  7.0
https://openalex.org/I82880672   Beihang University                                 CN           education                  6.0
https://openalex.org/I79238269   Universidad de Sevilla                             ES           education             5.377939
https://openalex.org/I157773358  Sun Yat-sen University                             CN           education             5.250598
https://openalex.org/I68947357   University of Strasbourg                           FR           education                  5.0
https://openalex.org/I2801509770 Institut National des Sciences Appliquées de St... FR           education                  5.0

In [102]:
dv84, kw84 = get_affils_cluster_sort(dftriple, 0)
print(kw84)
dv84.head(20)

0
['Aerial Manipulator', 'Aerial Manipulator Robot', 'Aerial Robotic Manipulators', 'Aerial', 'Manipulator', 'Aerial Manipulator System', 'unmanned aerial vehicle', 'aerial manipulator control', 'Control Aerial Manipulator', 'aerial manipulation', 'Aerial Robotic', 'aerial manipulator vehicle', 'aerial vehicle', 'Protocentric Aerial Manipulators', 'proposed aerial manipulator', 'Unmanned aerial', 'Robotic Manipulator', 'control', 'Aerial Robotic System', 'robotic arm']

                                                                                                            paper_cluster_score
id                               display_name                                       country_code type
https://openalex.org/I190497903  Laboratory for Analysis and Architecture of Sys... FR           facility               8.45873
https://openalex.org/I118946981  Escuela Politécnica del Ejército                   EC           education             8.124794
https://openalex.org/I1294671590 French National Centre for Scientific Research     FR           government            7.006282
https://openalex.org/I17866349   Université de Toulouse                             FR           education             7.006282
https://openalex.org/I71267560   University of Naples Federico II                   IT           education                  7.0
https://openalex.org/I82880672   Beihang University                                 CN           education                  6.0
https://openalex.org/I79238269   Universidad de Sevilla                             ES           education             5.377939
https://openalex.org/I157773358  Sun Yat-sen University                             CN           education             5.250598
https://openalex.org/I68947357   University of Strasbourg                           FR           education                  5.0
https://openalex.org/I2801509770 Institut National des Sciences Appliquées de St... FR           education                  5.0
https://openalex.org/I201537933  Tohoku University                                  JP           education             4.540139
https://openalex.org/I2801039369 Marconi University                                 IT           education             4.440636
https://openalex.org/I9360294    University of Bologna                              IT           education             4.440636
https://openalex.org/I4210098188 Laboratori Guglielmo Marconi (Italy)               IT           company               4.440636
https://openalex.org/I47508984   Imperial College London                            GB           education             3.843127
https://openalex.org/I181343428  University of Zagreb                               HR           education             3.810908
https://openalex.org/I2898391981 German Aerospace Center                            DE           facility              3.454642
https://openalex.org/I135768898  Ritsumeikan University                             JP           education             3.173709
https://openalex.org/I99542240   Polish Academy of Sciences                         PL           government                 3.0
https://openalex.org/I686019     AGH University of Krakow                           PL           education                  3.0

In [103]:
dfinfo = dfpapers[['x','y','id','title','doi','cluster','probability',
                 'publication_date','grants','locations',
                   'keywords','top_concepts']].copy()

In [104]:
dfpapers['primary_location'].iloc[58]

{'is_oa': False,
 'landing_page_url': 'https://doi.org/10.1016/j.robot.2017.05.015',
 'pdf_url': None,
 'source': {'id': 'https://openalex.org/S133768115',
  'display_name': 'Robotics and autonomous systems',
  'issn_l': '0921-8890',
  'issn': ['0921-8890', '1872-793X'],
  'is_oa': False,
  'is_in_doaj': False,
  'host_organization': 'https://openalex.org/P4310320990',
  'host_organization_name': 'Elsevier BV',
  'host_organization_lineage': ['https://openalex.org/P4310320990'],
  'host_organization_lineage_names': ['Elsevier BV'],
  'type': 'journal'},
 'license': None,
 'license_id': None,
 'version': None,
 'is_accepted': False,
 'is_published': False}

In [105]:
dfpapers['locations'].iloc[58]

[{'is_oa': False,
  'landing_page_url': 'https://doi.org/10.1016/j.robot.2017.05.015',
  'pdf_url': None,
  'source': {'id': 'https://openalex.org/S133768115',
   'display_name': 'Robotics and autonomous systems',
   'issn_l': '0921-8890',
   'issn': ['0921-8890', '1872-793X'],
   'is_oa': False,
   'is_in_doaj': False,
   'host_organization': 'https://openalex.org/P4310320990',
   'host_organization_name': 'Elsevier BV',
   'host_organization_lineage': ['https://openalex.org/P4310320990'],
   'host_organization_lineage_names': ['Elsevier BV'],
   'type': 'journal'},
  'license': None,
  'license_id': None,
  'version': None,
  'is_accepted': False,
  'is_published': False}]

In [106]:
dftriple.columns

Index(['id', 'display_name', 'ror', 'country_code', 'type', 'lineage',
       'paper_id', 'paper_raw_affiliation_strings', 'paper_author_position',
       'paper_doi', 'paper_title', 'paper_abstract', 'paper_publication_date',
       'paper_publication_year', 'paper_grants', 'paper_locations',
       'paper_is_corrresponding', 'paper_x', 'paper_y', 'paper_cluster',
       'paper_cluster_score', 'paper_author_id', 'paper_author_display_name',
       'paper_author_orcid'],
      dtype='object')

In [107]:
dftriple[['paper_id','paper_raw_affiliation_strings']].head()

,paper_id,paper_raw_affiliation_strings
0,https://openalex.org/W2740675802,"[Ministry of Education, Key Laboratory of Know..."
1,https://openalex.org/W2740675802,"[Ministry of Education, Key Laboratory of Know..."
2,https://openalex.org/W2740675802,[Department of Electrical and Computer Enginee...
3,https://openalex.org/W2418767125,"[School of Automation, Southeast University, N..."
4,https://openalex.org/W2418767125,[School of Automation and Electrical Engineeri...

In [108]:
dftriple['paper_raw_affiliation_strings'].value_counts(dropna=False)

[School of Information and Communication Engineering, University of Electronic Science and Technology of China, Chengdu, China]                     102
[Sandia National Laboratories, P.O. Box 5800, Albuquerque, New Mexico 87185, USA]                                                                    91
[Sandia National Laboratories, Albuquerque, New Mexico 87185, USA]                                                                                   85
[State Key Laboratory of Electronic Thin Films and Integrated Devices, University of Electronic Science and Technology of China, Chengdu, China]     84
[School of Electrical and Electronic Engineering, Shandong University of Technology, Zibo, China]                                                    80
                                                                                                                                                   ...
[Electrical and Computer Engineering Department, University of New Mexico, Albuquerque, USA]                                                          1
[National Institute for Space Research, Associated Plasma Laboratory, são José dos Campos, Brazil]                                                    1
[Dept. Electrical and Computer Eng., Texas Tech University, SARA Inc. High Power Electromagnetics Division, Colorado Springs, CO, USA]                1
[Leibniz Institute for Plasma Science and Technology e. V (INP Greifswald), Greifswald, Germany]                                                      1
[Inter-branch Scientific Research Institute of Physical Simulation Problems, Kharkiv, Ukraine]                                                        1
Name: paper_raw_affiliation_strings, Length: 11062, dtype: int64

In [112]:
dftriple[['paper_id','paper_raw_affiliation_strings']].head()

,paper_id,paper_raw_affiliation_strings
0,https://openalex.org/W2740675802,"[Ministry of Education, Key Laboratory of Know..."
1,https://openalex.org/W2740675802,"[Ministry of Education, Key Laboratory of Know..."
2,https://openalex.org/W2740675802,[Department of Electrical and Computer Enginee...
3,https://openalex.org/W2418767125,"[School of Automation, Southeast University, N..."
4,https://openalex.org/W2418767125,[School of Automation and Electrical Engineeri...

In [146]:
# Group by 'paper_id' and concatenate 'paper_raw_affiliation_strings'
grouped = dftriple.groupby('paper_id')['paper_raw_affiliation_strings'].apply(lambda x: list(set([item for sublist in x for item in sublist]))).reset_index()

# Convert the series back to a dictionary
pap_affils_dict = grouped.set_index('paper_id')['paper_raw_affiliation_strings'].to_dict()

In [147]:
#paper_affils_dict

In [148]:
#pap_affils_dict = dftriple.groupby('paper_id')['paper_raw_affiliation_strings'].\
#apply(lambda x: ' | '.join(x.tolist()))

#pap_affils_dict = dftriple.set_index('paper_id')['paper_raw_affiliation_strings'].to_dict()
import itertools

#pap_affils_dict = dftriple.set_index('paper_id')['paper_raw_affiliation_strings']

In [149]:
type(pap_affils_dict)

dict

In [138]:
#pap_affils_dict.head()

In [150]:
pap_authors_dict = dftriple.groupby('paper_id')['paper_author_display_name'].apply(lambda x: x.values)

In [151]:
pap_authors_dict

paper_id
https://openalex.org/W2166534330                   [Hussain Sultan, Eric M. Schwartz]
https://openalex.org/W2252881006                         [Xiaohan Chen, Xiaohan Chen]
https://openalex.org/W2280830725    [Alireza Rahrooh, Scott Shepard, Walter Buchan...
https://openalex.org/W2340996099                                      [John Dennison]
https://openalex.org/W2343923805    [Zhengxin Hou, Lei Liu, Yongji Wang, Jian Huan...
                                                          ...
https://openalex.org/W4396816771                                  [Menaouer Bennaoum]
https://openalex.org/W4396877673    [Qinzhe Lv, Hongqin Fan, Yinghai Zhao, Mengdao...
https://openalex.org/W4396877719    [Zhizhen Liu, Xinjie Yu, Zhen Li, Hao Sun, Bei...
https://openalex.org/W4396878689    [Lyubov Gorbacheva, Maxim Zakharov, Andrey Kou...
https://openalex.org/W584406582                              [M. O. Tokhi, Abul Azad]
Name: paper_author_display_name, Length: 7702, dtype: object

In [152]:
type(pap_authors_dict)

pandas.core.series.Series

In [155]:
#dfinfo.head()

In [156]:
dfinfo['affil_list'] = dfinfo['id'].map(pap_affils_dict)

In [158]:
dfinfo['affil_list'].head().iloc[4]

['School of Information Science and Engineering, Lanzhou University, Lanzhou, China',
 'School of Information Science and Engineering, Qufu Normal University, Rizhao, China',
 'Department of Computing, The Hong Kong Polytechnic University, Hong Kong']

In [159]:
dfinfo[['id','affil_list']].iloc[4]

id                             https://openalex.org/W2792852625
affil_list    [School of Information Science and Engineering...
Name: https://openalex.org/W2792852625, dtype: object

In [160]:
dfinfo['authors_list'] = dfinfo['id'].map(pap_authors_dict)

In [161]:
dfinfo['wrapped_affil_list'] = dfinfo['affil_list'].apply(str).apply(wrap_it)
dfinfo['wrapped_author_list'] = dfinfo['author_list'].apply(str).apply(wrap_it)

In [162]:
dfinfo['wrapped_keywords'] = dfinfo['keywords'].apply(str).apply(wrap_it)

In [163]:
dfinfo['locations'].iloc[69]

[{'is_oa': False,
  'landing_page_url': 'https://doi.org/10.1016/j.isatra.2020.06.017',
  'pdf_url': None,
  'source': {'id': 'https://openalex.org/S89543202',
   'display_name': 'ISA transactions',
   'issn_l': '0019-0578',
   'issn': ['0019-0578', '1879-2022'],
   'is_oa': False,
   'is_in_doaj': False,
   'host_organization': 'https://openalex.org/P4310320990',
   'host_organization_name': 'Elsevier BV',
   'host_organization_lineage': ['https://openalex.org/P4310320990'],
   'host_organization_lineage_names': ['Elsevier BV'],
   'type': 'journal'},
  'license': None,
  'license_id': None,
  'version': None,
  'is_accepted': False,
  'is_published': False},
 {'is_oa': False,
  'landing_page_url': 'https://pubmed.ncbi.nlm.nih.gov/32595010',
  'pdf_url': None,
  'source': {'id': 'https://openalex.org/S4306525036',
   'display_name': 'PubMed',
   'issn_l': None,
   'issn': None,
   'is_oa': False,
   'is_in_doaj': False,
   'host_organization': 'https://openalex.org/I1299303238',
   'host_organization_name': 'National Institutes of Health',
   'host_organization_lineage': ['https://openalex.org/I1299303238'],
   'host_organization_lineage_names': ['National Institutes of Health'],
   'type': 'repository'},
  'license': None,
  'license_id': None,
  'version': None,
  'is_accepted': False,
  'is_published': False}]

In [164]:
def get_source_name(loc_list):
    """
    grab the first item in the list;
    retturn the display name
    """
    try:
        primary = loc_list[0]
        return primary["source"]["display_name"]
    except:
        return None

def get_source_type(loc_list):
    """
    grab the first item in the list;
    return the source type
    """
    try:
        primary = loc_list[0]
        return primary["source"]["type"]
    except:
        return None

In [165]:
dfinfo["source"] = dfinfo["locations"].apply(get_source_name)
dfinfo["source_type"] = dfinfo["locations"].apply(get_source_type)

In [166]:
dfinfo["source"].value_counts()

IEEE transactions on plasma science                                                  303
arXiv (Cornell University)                                                           206
Lecture notes in electrical engineering                                              178
Journal of physics. Conference series                                                175
IEEE access                                                                          135
                                                                                    ...
2022 7th International Conference on Integrated Circuits and Microsystems (ICICM)      1
Pisʹma v Žurnal tehničeskoj fiziki                                                     1
Transportation research procedia                                                       1
Hyōmen kagaku/Hyoumen kagaku                                                           1
Šumadijski anali                                                                       1
Name: source, Length: 1689, dtype: int64

In [167]:
dfinfo["source_type"].value_counts()

journal           4984
conference         746
book series        482
repository         273
ebook platform     151
Name: source_type, dtype: int64

In [168]:
dfinfo[dfinfo["source_type"] == "conference"]

,x,y,id,title,doi,cluster,probability,publication_date,grants,locations,keywords,top_concepts,author_list,affil_list,authors_list,wrapped_affil_list,wrapped_author_list,wrapped_keywords,source,source_type
id,,,,,,,,,,,,,,,,,,,,
https://openalex.org/W4285102237,13.218431,-5.538858,https://openalex.org/W4285102237,Provably Safe Deep Reinforcement Learning for ...,https://doi.org/10.1109/icra46639.2022.9811698,1,1.000000,2022-05-23,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Safe Deep Reinforcement, Provably Safe Deep, ...","[Reinforcement learning, Reachability, Compute...","[Jakob Thumm, Matthias Althoff]","[Technical Univer-sity of Munich,Department of...","[Jakob Thumm, Matthias Althoff]","['Technical Univer-sity of<br>Munich,Departmen...",['Jakob Thumm' 'Matthias Althoff'],"['Safe Deep Reinforcement', 'Provably<br>Safe ...",2022 International Conference on Robotics and ...,conference
https://openalex.org/W3017045808,10.837953,-6.306325,https://openalex.org/W3017045808,A Systematic Review and Meta-analysis of Robot...,https://doi.org/10.1088/1757-899x/782/4/042055,1,1.000000,2020-03-01,[],"[{'is_oa': True, 'landing_page_url': 'https://...","[Systematic Review, Review and Meta-analysis, ...","[Grippers, GRASP, Robotics, Artificial intelli...","[Zhang Long, Jiang Qian, Shuai Tao, Feijuan We...",[Nanchong Key Laboratory of Robotics Engineeri...,"[Zhang Long, Jiang Qian, Shuai Tao, Feijuan We...",['Nanchong Key Laboratory of Robotics<br>Engin...,['Zhang Long' 'Jiang Qian' 'Shuai Tao'<br>'Fei...,"['Systematic Review', 'Review and Meta-<br>ana...",IOP conference series. Materials science and e...,conference
https://openalex.org/W2761006485,12.506837,-6.492780,https://openalex.org/W2761006485,Kinematic singularity avoidance for robot mani...,https://doi.org/10.1109/ccta.2017.8062454,1,1.000000,2017-08-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Kinematic singularity avoidance, singularity ...","[Kinematics, Singularity, Control theory (soci...","[J. Sverdrup-Thygeson, Signe Moe, Kristin Y. P...","[Department of Engineering Cybernetics, Norweg...","[J. Sverdrup-Thygeson, Signe Moe, Kristin Y. P...","['Department of Engineering Cybernetics,<br>No...",['J. Sverdrup-Thygeson' 'Signe Moe'<br>'Kristi...,"['Kinematic singularity avoidance',<br>'singul...",2017 IEEE Conference on Control Technology and...,conference
https://openalex.org/W4285102150,11.388507,-6.114420,https://openalex.org/W4285102150,An Integrated Design Pipeline for Tactile Sens...,https://doi.org/10.1109/icra46639.2022.9812335,1,1.000000,2022-05-23,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Integrated Design Pipeline, Tactile Sensing R...","[Modular design, Pipeline (software)]","[Lara Zlokapa, Yiyue Luo, Jie Xu, Michael Fosh...",[Computer Science and Artificial Intelligence ...,"[Lara Zlokapa, Yiyue Luo, Jie Xu, Michael Fosh...",['Computer Science and Artificial<br>Intellige...,['Lara Zlokapa' 'Yiyue Luo' 'Jie Xu'<br>'Micha...,"['Integrated Design Pipeline', 'Tactile<br>Sen...",2022 International Conference on Robotics and ...,conference
https://openalex.org/W2927011308,11.815010,-6.301626,https://openalex.org/W2927011308,URDF Generator for Manipulator Robot,https://doi.org/10.1109/irc.2019.00101,1,1.000000,2019-02-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[URDF Generator, robots market grows, Generato...","[Parallel manipulator, Robot, Manipulator (dev...","[Yeon June Kang, Donghan Kim]","[Department of Eletronics, Kyung Hee Universit...","[Yeon June Kang, Donghan Kim]","['Department of Eletronics, Kyung Hee<br>Unive...",['Yeon June Kang' 'Donghan Kim'],"['URDF Generator', 'robots market<br>grows', '...",2019 Third IEEE International Conference on Ro...,conference
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
https://openalex.org/W3023203661,10.058883,8.296876,https://openalex.org/W3023203661,Simulation Research on New Model of Air-to-Air...,https://doi.org/10.1109/itnec48623.2020.9084793,50,0.956870,2020-06-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Missile Attack Zone, Attack Zone, Missile Att...","[Missile, Atmospheric model]","[Aiguo Li, Yanan Meng, Zongkang He]","[College of Computer Science and Technology, X...","[Aiguo Li, Yanan Meng, Zongkang He]","[""College of Computer Science and<br>Technolog...",['Aiguo Li' 'Yanan Meng' 'Zongkang He'],"['Missile Attack Zone', 'Attack Zone',<br>'Mis...","2020 IEEE 4th Information Technology, Networki...",conference
https://openalex.org/W3009411444,10.136135,8.178399,https://openalex.org/W3009411444,Modeling and Simulation Analysis on Three-Dime...,https://doi.org/10.1109/gncc42960.2018.9018858,50,0.881589,2018-08-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Missile Attack Zone, Attack Zone, Missile Att...",[Missile],"[Zhenqing Shi, Xiaolong Liang, Jiaqiang Zhang,...",[National Key Laboratory of Air Traffic Collis...,"[Zhenqing Shi, Xiaolong Liang, Jiaqiang Zhang,...",['National Key Laboratory of Air Traffic<br>Co...,['Zhenqing Shi' 'Xiaolong Liang'<br>'Jiaqiang ...,"['Missile Attack Zone', 'Attack Zone',<br>'Mis...","2018 IEEE CSAA Guidance, Navigation and Contro...",conference
https://openalex.org/W2899852203,11.271832,7.751986,https://openalex.org/W2899852203,Research on the Air Combat Countermeasure Gene...,https://doi.org/10.1088/1757-899x/435/1/012062,-1,0.000000,2018-11-05,[],"[{'is_oa': True, 'landing_page_url': 'https://...","[Fighter Mid-range Turn, Air Combat Countermea...","[Air combat, Range (aeronautics), Missile, Air...","[Huiming Ji, Minjian Yu, Jiayi Yang]","[Air Force Engineering University, Xi’an, China]","[Huiming Ji, Minjian Yu, Jiayi Yang]","['Air Force Engineering University,<br>Xi’an, ...",['Huiming Ji' 'Minjian Yu' 'Jiayi Yang'],"['Fighter Mid-range Turn', 'Air Combat<br>Coun...",IOP conference series. Materials science and e...,conference
https://openalex.org/W2952933698,9.902278,8.138485,https://openalex.org/W2952933698,Operational Effectiveness Evaluation for the A...,https://doi.org/10.1109/itnec.2019.8729345,-1,0.000000,2019-03-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Two-step Adjudication Method, Improved Two-st...","[Missile, Adjudication]","[Baihua Xiao, Yang Xu, Chen Huang, Rui Wang, Y...","[Aeronautics Engineering College, Air Force En...","[Baihua Xiao, Yang Xu, Chen Huang, Rui Wang, Y...","['Aeronautics Engineering College, Air<br>Forc...",['Baihua Xiao' 'Yang Xu' 'Chen Huang'<br>'Rui ...,"['Two-step Adjudication Method',<br>'Improved ...","2019 IEEE 3rd Information Technology, Networki...",conference
https://openalex.org/W3009555957,11.435743,6.776400,https://openalex.org/W3009555957,Pseudospectral-based Multiple Missiles Salvo A...,https://doi.org/10.1109/gncc42960.2018.9018875,59,0.545570,2018-08-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Multiple Missiles Salvo, Missiles Salvo Attac...","[Gauss pseudospectral method, Pseudospectral o...","[Jiang Wang, Yadong Wang, Xinyao Duan, Yongwei...",[Beijing key laboratory of UAV Autonomous Cont...,"[Jiang Wang, Yadong Wang, Xinyao Duan, Yongwei...",['Beijing key laboratory of UAV<br>Autonomous ...,['Jiang Wang' 'Yadong Wang' 'Xinyao<br>Duan' '...,"['Multiple Missiles Salvo', 'Missiles<br>Salvo...","2018 IEEE CSAA Guidance, Navigation and Contro...",conference

In [169]:
dfinfo.columns

Index(['x', 'y', 'id', 'title', 'doi', 'cluster', 'probability',
       'publication_date', 'grants', 'locations', 'keywords', 'top_concepts',
       'author_list', 'affil_list', 'authors_list', 'wrapped_affil_list',
       'wrapped_author_list', 'wrapped_keywords', 'source', 'source_type'],
      dtype='object')

In [170]:
dftriple.columns

Index(['id', 'display_name', 'ror', 'country_code', 'type', 'lineage',
       'paper_id', 'paper_raw_affiliation_strings', 'paper_author_position',
       'paper_doi', 'paper_title', 'paper_abstract', 'paper_publication_date',
       'paper_publication_year', 'paper_grants', 'paper_locations',
       'paper_is_corrresponding', 'paper_x', 'paper_y', 'paper_cluster',
       'paper_cluster_score', 'paper_author_id', 'paper_author_display_name',
       'paper_author_orcid'],
      dtype='object')

In [171]:
dfinfo.to_pickle('updatejammingdfinfo2d.pkl')

In [175]:
#dftriple['paper_grants'].value_counts()

In [176]:
def get_funder_names(funder_list):
    """
    funder_list is a list of dictionaries
    with three keys; return the list of 
    unique **funder_display_name**
    values
    """
    try:
        funder_names = list(set([f['funder_display_name'] for f in funder_list]))
        return funder_names    
    except:
        return []

In [177]:
dftriple["source"] = dftriple["paper_locations"].apply(get_source_name)
dftriple["source_type"] = dftriple["paper_locations"].apply(get_source_type)
dftriple["funder_list"] = dftriple["paper_grants"].apply(get_funder_names)

In [178]:
dftriple.to_pickle('updatejammingdftriple2d.pkl')

In [179]:
dftriple['source'].value_counts()

IEEE transactions on plasma science                                         1701
Review of scientific instruments online/Review of scientific instruments    1106
Journal of physics. Conference series                                        589
Lecture notes in electrical engineering                                      547
IEEE access                                                                  540
                                                                            ...
Europhysics letters                                                            1
Fizika tverdogo tela                                                           1
Defense and security analysis                                                  1
Acta crystallographica. Section A, Foundations and advances                    1
Bioprocess engineering                                                         1
Name: source, Length: 1336, dtype: int64

In [180]:
dftriple['source_type'].value_counts()

journal           21212
conference         2811
book series        1540
repository          290
ebook platform      167
Name: source_type, dtype: int64

In [181]:
def get_journals_cluster_sort(dc:pd.DataFrame, cl:int):
    """
    restricts the dataframe dc to cluster value cl
    and returns the results grouped by source (where
    source_type == 'journal') sorted
    by the some of probablity descending
    """
    dg = dc[dc['paper_cluster'] == cl].copy()
    print(cl)
    dv = dg[dg['source_type'] == 'journal'].groupby(['source'])['paper_cluster_score'].sum().to_frame()
    dv.sort_values('paper_cluster_score', ascending=False, inplace=True)
    kw = centroids[centroids.cluster == cl]['keywords'].iloc[0]
    return dv, kw

In [182]:
def get_conferences_cluster_sort(dc:pd.DataFrame, cl:int):
    """
    restricts the dataframe dc to cluster value cl
    and returns the results grouped by source (where
    source_type == 'journal') sorted
    by the some of probablity descending
    """
    dg = dc[dc['paper_cluster'] == cl].copy()
    print(cl)
    dv = dg[dg['source_type'] == 'conference'].groupby(['source'])['paper_cluster_score'].sum().to_frame()
    dv.sort_values('paper_cluster_score', ascending=False, inplace=True)
    kw = centroids[centroids.cluster == cl]['keywords'].iloc[0]
    return dv, kw

In [183]:
dv84, kw84 = get_journals_cluster_sort(dftriple, 1)
print(kw84)
dv84.head(10)

1
['robotic manipulator system', 'Robotic Manipulator', 'Robotic Manipulator Control', 'Robot manipulator', 'Sliding Mode Control', 'Flexible Robotic Manipulator', 'robotic manipulator based', 'redundant robot manipulators', 'manipulator control system', 'Timoshenko robotic manipulator', 'industrial robot manipulator', 'Robot Manipulators Based', 'Robotic Arm Manipulator', 'control robotic manipulators', 'Robot Manipulators Control', 'DOF Robotic Manipulator', 'Soft Robotic Manipulators', 'robot manipulator systems', 'Manipulator Robotic Control', 'Manipulator']

                                                   paper_cluster_score
source
IFAC-PapersOnLine                                                119.0
Robotikusu, Mekatoronikusu Koenkai koen gaiyoshu                  89.0
Applied sciences                                                  87.0
IEEE access                                                       86.0
IEEE robotics & automation letters                                69.0
Robotica                                                          68.0
International journal of robust and nonlinear c...                58.0
Journal of physics. Conference series                             46.0
IEEE transactions on industrial informatics                       40.0
IEEE/ASME transactions on mechatronics                            39.0

# Country - Country Collaborations

want to report back though which countries are involved as well. ok.

In [184]:
def get_country_collaborations_sort(dc:pd.DataFrame, cl:int):
    """
    resticts the dataframe dc to cluster value cl
    and returns the results of paper_id s where there is 
    more than one country_code
    """
    dg = dc[dc['paper_cluster'] == cl].copy()
    dv = dg.groupby('paper_id')['country_code'].apply(lambda x: len(set(x.values))).to_frame()
    dc = dg.groupby('paper_id')['country_code'].apply(lambda x: list(set(x.values))).to_frame()
    dc.columns = ['collab_countries']
    dv.columns = ['country_count']
    dv['collab_countries'] = dc['collab_countries']
    dv.sort_values('country_count',ascending=False, inplace=True)
    di = dfinfo.loc[dv.index].copy()
    di['country_count'] = dv['country_count']
    di['collab_countries'] = dv['collab_countries']
    return di[di['country_count'] > 1]

In [185]:
dv = get_country_collaborations_sort(dftriple, 0)
dv

,x,y,id,title,doi,cluster,probability,publication_date,grants,locations,...,author_list,affil_list,authors_list,wrapped_affil_list,wrapped_author_list,wrapped_keywords,source,source_type,country_count,collab_countries
paper_id,,,,,,,,,,,,,,,,,,,,,
https://openalex.org/W3174123873,11.700774,-2.151464,https://openalex.org/W3174123873,"Past, Present, and Future of Aerial Robotic Ma...",https://doi.org/10.1109/tro.2021.3084395,0,0.712416,2022-02-01,[{'funder': 'https://openalex.org/F4320320300'...,"[{'is_oa': True, 'landing_page_url': 'https://...",...,"[Anı́bal Ollero, Marco Tognon, Alejandro Suáre...","[GRVC Robotics Lab, Universidad de Sevilla, Se...","[Anı́bal Ollero, Marco Tognon, Alejandro Suáre...","['GRVC Robotics Lab, Universidad de<br>Sevilla...",['Anı́bal Ollero' 'Marco Tognon'<br>'Alejandro...,"['Aerial Robotic Manipulators', 'Robotic<br>Ma...",IEEE transactions on robotics,journal,5,"[FR, NL, KR, CH, ES]"
https://openalex.org/W3013279486,11.678339,-2.210043,https://openalex.org/W3013279486,Design and Development of a Low-Cost Indigenou...,https://doi.org/10.1109/isai-nlp48611.2019.904...,0,0.113120,2019-10-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...",...,"[Adil Farooq, Muhammad Irfan, Abdullah Saeed, ...",[Emirates Integrated Telecommunications Compan...,"[Adil Farooq, Muhammad Irfan, Abdullah Saeed, ...",['Emirates Integrated Telecommunications<br>Co...,['Adil Farooq' 'Muhammad Irfan'<br>'Abdullah S...,"['Unmanned Ground Vehicle', 'Indigenous<br>Sol...",None,None,4,"[AE, CY, PK, TH]"
https://openalex.org/W4361764889,11.695472,-2.173434,https://openalex.org/W4361764889,Innovative Development of a Flying robot with ...,https://doi.org/10.15439/2022r47,0,0.297226,2022-02-20,[],"[{'is_oa': True, 'landing_page_url': 'https://...",...,"[Yavor Yotov, Yavor Yotov, Nikolay Zlatov, Nik...",[Institute of Mechanics. Bulgarian Academy of ...,"[Yavor Yotov, Yavor Yotov, Nikolay Zlatov, Nik...",['Institute of Mechanics. Bulgarian<br>Academy...,['Yavor Yotov' 'Yavor Yotov' 'Nikolay<br>Zlato...,"['aerial manipulation platform',<br>'Dexterous...",Annals of Computer Science and Information Sys...,conference,4,"[BG, MY, GB, VN]"
https://openalex.org/W3131230508,11.689248,-2.159222,https://openalex.org/W3131230508,Compliance Control of a Cable-Suspended Aerial...,https://doi.org/10.1109/iros45743.2020.9340703,0,0.620179,2020-10-24,[],"[{'is_oa': False, 'landing_page_url': 'https:/...",...,"[Chiara Gabellieri, Chiara Gabellieri, Yu. S. ...","[German Aerospace Center (DLR), Institute of R...","[Chiara Gabellieri, Chiara Gabellieri, Yu. S. ...","['German Aerospace Center (DLR),<br>Institute ...",['Chiara Gabellieri' 'Chiara Gabellieri'<br>'Y...,"['Cable-Suspended Aerial Manipulator',<br>'Hie...",None,None,3,"[IT, DE, RU]"
https://openalex.org/W2901687922,11.666718,-2.128519,https://openalex.org/W2901687922,Force control design for a robot manipulator a...,https://doi.org/10.1016/j.ifacol.2018.11.268,0,0.214043,2018-01-01,[],"[{'is_oa': True, 'landing_page_url': 'https://...",...,"[Κωνσταντίνος Γκούντας, Dimitris Chaikalis, An...","[New York University Abu Dhabi, Electrical and...","[Κωνσταντίνος Γκούντας, Dimitris Chaikalis, An...","['New York University Abu Dhabi,<br>Electrical...",['Κωνσταντίνος Γκούντας' 'Dimitris<br>Chaikali...,"['Unmanned Aerial Vehicle', 'Force<br>control ...",IFAC-PapersOnLine,journal,2,"[AE, GR]"
https://openalex.org/W3033578287,11.700250,-2.168555,https://openalex.org/W3033578287,"Design, modeling, and control of an aerial man...",https://doi.org/10.1002/rob.21963,0,0.366084,2020-06-01,[{'funder': 'https://openalex.org/F4320334627'...,"[{'is_oa': True, 'landing_page_url': 'https://...",...,"[Salua Hamaza, Ioannis Georgilas, Guillermo He...","[Department of Aerospace Engineering, Universi...","[Salua Hamaza, Ioannis Georgilas, Guillermo He...","['Department of Aerospace Engineering,<br>Univ...",['Salua Hamaza' 'Ioannis Georgilas'<br>'Guille...,"['Abstract On‐site inspection',<br>'placement ...",Journal of field robotics,journal,2,"[ES, GB]"
https://openalex.org/W2954439514,11.695272,-2.145563,https://openalex.org/W2954439514,Centralized Control of Helicopters with Manipu...,https://doi.org/10.1007/978-3-030-12945-3_9,0,0.973927,2019-01-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...",...,"[Manuel Béjar, Anı́bal Ollero, Konstantin Kondak]","[GRVC Robotics Lab Sevilla, Universidad de Sev...","[Manuel Béjar, Anı́bal Ollero, Konstantin Kondak]","['GRVC Robotics Lab Sevilla, Universidad<br>de...",['Manuel Béjar' 'Anı́bal Ollero'<br>'Konstanti...,"['Control', 'Centralized Control',<br>'Helicop...",Springer tracts in advanced robotics,book series,2,"[DE, ES]"
https://openalex.org/W4310720483,11.683209,-2.139517,https://openalex.org/W4310720483,Modeling and trajectory tracking by robust con...,https://doi.org/10.1109/icaee53772.2022.9962012,0,0.505613,2022-10-29,[],"[{'is_oa': False, 'landing_page_url': 'https:/...",...,"[Zamoum Housseyn, Zamoum Housseyn]","[Guidance and Navigation Laboratory, Ecole Mil...","[Zamoum Housseyn, Zamoum Housseyn]","['Guidance and Navigation Laboratory,<br>Ecole...",['Zamoum Housseyn' 'Zamoum Housseyn'],"['manipulator arm', 'aerial<br>manipulation', ...",2022 2nd International Conference on Advanced ...,conference,2,"[FR, GB]"
https://openalex.org/W2612358504,11.695197,-2.152135,https://openalex.org/W2612358504,"Explicit Computations, Simulations and additio...",None,0,1.000000,2017-02-23,[],"[{'is_oa': True, 'landing_page_url': 'https://...",...,"[Burak Yüksel, Gabriele Buondonno]",[Max Planck Institute for Biological Cyberneti...,"[Burak Yüksel, Gabriele Buondonno]",['Max Planck Institute for Biological<br>Cyber...,['Burak Yüksel' 'Gabriele Buondonno'],"['Dynamic Decentralized Control',<br>'Protocen...",None,None,2,"[IT, DE]"
https://openalex.org/W2950250300,11.691013,-2.150770,https://openalex.org/W2950250300,Equilibrium-Based Force and Torque Control for...,https://doi.org/10.1017/s0263574719000870,0,1.000000,2019-06-17,[],"[{'is_oa': False, 'landing_page_url': 'https:/...",...,"[Bruno Tavora, Hyeongjun Park]",[Department of Mechanical and Aerospace Engine...,"[Bruno Tavora, Hyeongjun Park]",['Department of Mechanical and Aerospace<br>En...,['Bruno Tavora' 'Hyeongjun Park'],"['Vertical Surface', 'Aerial', 'Force<br>and T...",Robotica,journal,2,"[BR, US]"
https://openalex.org/W2768263424,11.684436,-2.139461,https://openalex.org/W2768263424,Navigation control and stability investigation...,https://doi.org/10.1177/1729881417738103,0,0.548524,2017-11-01,[],"[{'is_oa': True, 'landing_page_url': 'https://...",...,"[Pavol Božek, Aiman Al Akkad M, Peter Blišťan,...","[Slovak University of Technology, Bratislava, ...","[Pavol Božek, Aiman Al Akkad M, Peter Blišťan,...","['Slovak University of Technology,<br>Bratisla...",['Pavol Božek' 'Aiman Al Akkad M' 'Peter<br>Bl...,"['mobile robot based', 'hexacopter<br>equipped...",International journal of advanced robotic systems,journal,2,"[SK, RU]"
https://openalex.org/W4388821918,11.688947,-2.149192,https://openalex.org/W4388821918,Aerial Manipulator Interaction with the Enviro...,https://doi.org/10.1007/978-3-031-39767-7_12,0,1.000000,2023-11-21,[],"[{'is_oa': False, 'landing_page_url': 'https:/...",...,"[Santos M. Orozco-Soto, Eugenio Cuniato, Jonat...","[ETH Zurich, Zurich, Switzerland, Università d...","[Santos M. Orozco-Soto, Eugenio Cuniato, Jonat...","['ETH Zurich, Zurich, Switzerland',<br>'Univer...",['Santos M. Orozco-Soto' 'Eugenio<br>Cuniato' ...,"['Aerial Manipulator', 'Aerial<br>Manipulator ...",Advances in industrial control,book series,2,"[IT, CH]"
https://openalex.org/W2783130908,11.693867,-2.149497,https://openalex.org/W2783130908,Cooperative Aerial Manipulation Using Multirot...,https://doi.org/10.1109/tmech.2018.2792318,0,1.000000,2018-04-01,[{'funder': 'https://openalex.org/F4320321681'...,"[{'is_oa': False, 'landing_page_url': 'https:/...",...,"[H. Jin Kim, Ho Seong Seo, Jong‐Ho Shin, H. Ji...","[Robotics and Perception Group, Department of ...","[H. Jin Kim, Ho Seong Seo, Jong‐Ho Shin, H. Ji...","['Robotics and Perception Group,<br>Department...",['H. Jin Kim' 'Ho Seong Seo' 'Jong‐Ho<br>Shin'...,"['Multi-DOF Robotic Arms', 'aerial<br>manipula...",IEEE/ASME transactions on mechatronics,journal,2,"[CH, KR]"
https://openalex.org/W2756063857,11.691165,-2.152282,https://openalex.org/W2756063857,Aerial Manipulator Dynamics,https://doi.org/10.1007/978-3-319-61022-1_5,0,1.000000,2017-09-22,[],"[{'is_oa': False, 'landing_page_url': 'https:/...",...,"[Matko Orsag, Christopher Korpela, Paul Oh, St...",[Department of Electrical Engineering and Comp...,"[Matko Orsag, Christopher Korpela, Paul Oh, St...",['Department of Electrical Engineering<br>and ...,['Matko Orsag' 'Christopher Korpela'<br>'Paul ...,"['Aerial Manipulator Dynamics',<br>'Manipulato...",Advances in industrial control,book series,2,"[US, HR]"

In [186]:
dfinfo.head()

,x,y,id,title,doi,cluster,probability,publication_date,grants,locations,keywords,top_concepts,author_list,affil_list,authors_list,wrapped_affil_list,wrapped_author_list,wrapped_keywords,source,source_type
id,,,,,,,,,,,,,,,,,,,,
https://openalex.org/W1517236425,13.341581,-6.582227,https://openalex.org/W1517236425,Neural Network Control Of Robot Manipulators A...,https://doi.org/10.1201/9781003062714,1,1.0,2020-08-13,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Robot Manipulators, Neural network controller...","[Robot manipulator, Artificial neural network]",NaN,NaN,NaN,nan,nan,"['Robot Manipulators', 'Neural network<br>cont...",CRC Press eBooks,ebook platform
https://openalex.org/W2740675802,13.561797,-7.088242,https://openalex.org/W2740675802,Adaptive Neural Network Control of a Robotic M...,https://doi.org/10.1109/tcyb.2017.2711961,1,1.0,2017-10-01,[{'funder': 'https://openalex.org/F4320320006'...,"[{'is_oa': False, 'landing_page_url': 'https:/...","[Time-Varying Output Constraints, Output Const...","[Control theory (sociology), Lyapunov function...","[Wei He, Haifeng Huang, Shuzhi Sam Ge]",[Department of Electrical and Computer Enginee...,"[Wei He, Haifeng Huang, Shuzhi Sam Ge]",['Department of Electrical and Computer<br>Eng...,['Wei He' 'Haifeng Huang' 'Shuzhi Sam<br>Ge'],"['Time-Varying Output Constraints',<br>'Output...",IEEE transactions on cybernetics,journal
https://openalex.org/W2418767125,13.269590,-6.870666,https://openalex.org/W2418767125,Neural Network Control of a Flexible Robotic M...,https://doi.org/10.1109/tsmc.2016.2562506,1,1.0,2017-08-01,[{'funder': 'https://openalex.org/F4320321001'...,"[{'is_oa': False, 'landing_page_url': 'https:/...","[Flexible Robotic Manipulator, Flexible Roboti...","[Control theory (sociology), Deflection (physi...","[Changyin Sun, Wei He, Jin‐Woo Hong]","[School of Automation, Southeast University, N...","[Changyin Sun, Wei He, Jin‐Woo Hong]","['School of Automation, Southeast<br>Universit...",['Changyin Sun' 'Wei He' 'Jin‐Woo Hong'],"['Flexible Robotic Manipulator',<br>'Flexible ...","IEEE transactions on systems, man, and cyberne...",journal
https://openalex.org/W2901112449,11.222045,-7.583316,https://openalex.org/W2901112449,Model-Based Reinforcement Learning for Closed-...,https://doi.org/10.1109/tro.2018.2878318,1,1.0,2019-02-01,[],"[{'is_oa': False, 'landing_page_url': 'https:/...","[Soft Robotic Manipulators, Soft Robotic, Mode...","[Control theory (sociology), Kinematics, Reinf...","[Thomas George Thuruthel, Egidio Falotico, Fed...","[BioRobotics Institute, Scuola Superiore Sant’...","[Thomas George Thuruthel, Egidio Falotico, Fed...","['BioRobotics Institute, Scuola<br>Superiore S...",['Thomas George Thuruthel' 'Egidio<br>Falotico...,"['Soft Robotic Manipulators', 'Soft<br>Robotic...",IEEE transactions on robotics,journal
https://openalex.org/W2792852625,13.152991,-6.284923,https://openalex.org/W2792852625,Robot manipulator control using neural network...,https://doi.org/10.1016/j.neucom.2018.01.002,1,1.0,2018-04-01,[{'funder': 'https://openalex.org/F4320321001'...,"[{'is_oa': False, 'landing_page_url': 'https:/...","[neural networks, neural, Robot manipulators, ...","[Artificial neural network, Computer science]","[Long Jin, Shuai Li, Jiguo Yu, Jinbo He]",[School of Information Science and Engineering...,"[Long Jin, Shuai Li, Jiguo Yu, Jinbo He]",['School of Information Science and<br>Enginee...,['Long Jin' 'Shuai Li' 'Jiguo Yu' 'Jinbo<br>He'],"['neural networks', 'neural', 'Robot<br>manipu...",Neurocomputing,journal

In [187]:
dftriple.head()

,id,display_name,ror,country_code,type,lineage,paper_id,paper_raw_affiliation_strings,paper_author_position,paper_doi,...,paper_x,paper_y,paper_cluster,paper_cluster_score,paper_author_id,paper_author_display_name,paper_author_orcid,source,source_type,funder_list
0,https://openalex.org/I92403157,University of Science and Technology Beijing,https://ror.org/02egmk993,CN,education,[https://openalex.org/I92403157],https://openalex.org/W2740675802,"[Ministry of Education, Key Laboratory of Know...",first,https://doi.org/10.1109/tcyb.2017.2711961,...,13.561797,-7.088242,1,1.0,https://openalex.org/A5022113595,Wei He,https://orcid.org/0000-0002-8944-9861,IEEE transactions on cybernetics,journal,"[National Natural Science Foundation of China,..."
1,https://openalex.org/I92403157,University of Science and Technology Beijing,https://ror.org/02egmk993,CN,education,[https://openalex.org/I92403157],https://openalex.org/W2740675802,"[Ministry of Education, Key Laboratory of Know...",middle,https://doi.org/10.1109/tcyb.2017.2711961,...,13.561797,-7.088242,1,1.0,https://openalex.org/A5055142075,Haifeng Huang,https://orcid.org/0000-0002-1615-3779,IEEE transactions on cybernetics,journal,"[National Natural Science Foundation of China,..."
2,https://openalex.org/I165932596,National University of Singapore,https://ror.org/01tgyzw49,SG,education,[https://openalex.org/I165932596],https://openalex.org/W2740675802,[Department of Electrical and Computer Enginee...,last,https://doi.org/10.1109/tcyb.2017.2711961,...,13.561797,-7.088242,1,1.0,https://openalex.org/A5069702292,Shuzhi Sam Ge,None,IEEE transactions on cybernetics,journal,"[National Natural Science Foundation of China,..."
3,https://openalex.org/I76569877,Southeast University,https://ror.org/04ct4d772,CN,education,[https://openalex.org/I76569877],https://openalex.org/W2418767125,"[School of Automation, Southeast University, N...",first,https://doi.org/10.1109/tsmc.2016.2562506,...,13.26959,-6.870666,1,1.0,https://openalex.org/A5019248683,Changyin Sun,https://orcid.org/0000-0001-9269-334X,"IEEE transactions on systems, man, and cyberne...",journal,[National Natural Science Foundation of China]
4,https://openalex.org/I92403157,University of Science and Technology Beijing,https://ror.org/02egmk993,CN,education,[https://openalex.org/I92403157],https://openalex.org/W2418767125,[School of Automation and Electrical Engineeri...,middle,https://doi.org/10.1109/tsmc.2016.2562506,...,13.26959,-6.870666,1,1.0,https://openalex.org/A5061536058,Wei He,https://orcid.org/0000-0001-8321-8256,"IEEE transactions on systems, man, and cyberne...",journal,[National Natural Science Foundation of China]

In [188]:
jamming_concepts

[{'id': 'https://openalex.org/C2985527887',
  'wikidata': 'https://www.wikidata.org/wiki/Q1587588',
  'display_name': 'Robot manipulator',
  'relevance_score': 16245.706,
  'level': 3,
  'description': None,
  'works_count': 10153,
  'cited_by_count': 108685,
  'summary_stats': {'2yr_mean_citedness': 1.6,
   'h_index': 130,
   'i10_index': 1527},
  'ids': {'openalex': 'https://openalex.org/C2985527887',
   'wikidata': 'https://www.wikidata.org/wiki/Q1587588',
   'mag': '2985527887',
   'wikipedia': 'https://en.wikipedia.org/wiki/Manipulator%20%28device%29'},
  'image_url': 'https://upload.wikimedia.org/wikipedia/commons/b/b8/GammaGIF.gif',
  'image_thumbnail_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/GammaGIF.gif/100px-GammaGIF.gif',
  'international': {'display_name': {'ar': 'مناور',
    'de': 'Manipulator',
    'en': 'manipulator',
    'et': 'Manipulaator',
    'fa': 'بازوی مکانیکی',
    'fi': 'Manipulaattori',
    'hr': 'Manipulator',
    'it': 'manipolatore',
    'ja': 'マニピュレーター',
    'ko': '매니퓰레이터',
    'ky': 'манипулятор',
    'mk': 'управувач',
    'nb': 'Manipulator',
    'nl': 'Manipulator',
    'nn': 'manipulator',
    'pl': 'Manipulator robotyczny',
    'ru': 'манипулятор',
    'uk': 'Маніпулятор',
    'zh': '音樂調整器'},
   'description': {'ru': 'устройство управления положением предметов',
    'uk': "керований пристрій, оснащений робочим органом для виконання рухових функцій, аналогічних до функцій руки людини, під час переміщення об'єктів у просторі"}},
  'ancestors': [{'id': 'https://openalex.org/C2775924081',
    'wikidata': 'https://www.wikidata.org/wiki/Q55608371',
    'display_name': 'Control (management)',
    'level': 2},
   {'id': 'https://openalex.org/C90509273',
    'wikidata': 'https://www.wikidata.org/wiki/Q11012',
    'display_name': 'Robot',
    'level': 2},
   {'id': 'https://openalex.org/C154945302',
    'wikidata': 'https://www.wikidata.org/wiki/Q11660',
    'display_name': 'Artificial intelligence',
    'level': 1},
   {'id': 'https://openalex.org/C187736073',
    'wikidata': 'https://www.wikidata.org/wiki/Q2920921',
    'display_name': 'Management',
    'level': 1},
   {'id': 'https://openalex.org/C41008148',
    'wikidata': 'https://www.wikidata.org/wiki/Q21198',
    'display_name': 'Computer science',
    'level': 0},
   {'id': 'https://openalex.org/C162324750',
    'wikidata': 'https://www.wikidata.org/wiki/Q8134',
    'display_name': 'Economics',
    'level': 0}],
  'related_concepts': [],
  'counts_by_year': [{'year': 2024,
    'works_count': 141,
    'cited_by_count': 1657},
   {'year': 2023, 'works_count': 327, 'cited_by_count': 6773},
   {'year': 2022, 'works_count': 297, 'cited_by_count': 7151},
   {'year': 2021, 'works_count': 320, 'cited_by_count': 6880},
   {'year': 2020, 'works_count': 349, 'cited_by_count': 6354},
   {'year': 2019, 'works_count': 356, 'cited_by_count': 5824},
   {'year': 2018, 'works_count': 375, 'cited_by_count': 5614},
   {'year': 2017, 'works_count': 307, 'cited_by_count': 4494},
   {'year': 2016, 'works_count': 308, 'cited_by_count': 4147},
   {'year': 2015, 'works_count': 292, 'cited_by_count': 3780},
   {'year': 2014, 'works_count': 289, 'cited_by_count': 3989},
   {'year': 2013, 'works_count': 282, 'cited_by_count': 3406},
   {'year': 2012, 'works_count': 264, 'cited_by_count': 2945}],
  'works_api_url': 'https://api.openalex.org/works?filter=concepts.id:C2985527887',
  'updated_date': '2024-05-12T13:25:17.441518',
  'created_date': '2019-11-22'},
 {'id': 'https://openalex.org/C97039730',
  'wikidata': 'https://www.wikidata.org/wiki/Q552565',
  'display_name': 'Pulsed power',
  'relevance_score': 12352.694,
  'level': 3,
  'description': None,
  'works_count': 14094,
  'cited_by_count': 98326,
  'summary_stats': {'2yr_mean_citedness': 2.7359900373599,
   'h_index': 107,
   'i10_index': 2178},
  'ids': {'openalex': 'https://openalex.org/C97039730',
   'wikidata': 'https://www.wikidata.org/wiki/Q552565',
   'mag': '97039730',
   'wikipedia': 'https://en.wikipedia.org/wiki/Pulsed%20power'},
  'image_url': None,
  'image_thumbnail_url': None,
  'international': {'display_name': {'en': 'Pulsed power',
    'fa': 'توان پالسی',
    'fr': 'Hautes puissances pulsées',
    'he': 'הספק מתפרץ',
    'hi': 'स्पन्दित शक्ति',
    'ja': 'パルスパワー',
    'zh': '脈衝'},
   'description': {'ja': 'エネルギーの放出の型式'}},
  'ancestors': [{'id': 'https://openalex.org/C163258240',
    'wikidata': 'https://www.wikidata.org/wiki/Q25342',
    'display_name': 'Power (physics)',
    'level': 2},
   {'id': 'https://openalex.org/C165801399',
    'wikidata': 'https://www.wikidata.org/wiki/Q25428',
    'display_name': 'Voltage',
    'level': 2},
   {'id': 'https://openalex.org/C119599485',
    'wikidata': 'https://www.wikidata.org/wiki/Q43035',
    'display_name': 'Electrical engineering',
    'level': 1},
   {'id': 'https://openalex.org/C62520636',
    'wikidata': 'https://www.wikidata.org/wiki/Q944',
    'display_name': 'Quantum mechanics',
    'level': 1},
   {'id': 'https://openalex.org/C97355855',
    'wikidata': 'https://www.wikidata.org/wiki/Q11473',
    'display_name': 'Thermodynamics',
    'level': 1},
   {'id': 'https://openalex.org/C127413603',
    'wikidata': 'https://www.wikidata.org/wiki/Q11023',
    'display_name': 'Engineering',
    'level': 0},
   {'id': 'https://openalex.org/C121332964',
    'wikidata': 'https://www.wikidata.org/wiki/Q413',
    'display_name': 'Physics',
    'level': 0}],
  'related_concepts': [{'id': 'https://openalex.org/C52192207',
    'wikidata': None,
    'display_name': 'Capacitor',
    'level': 3,
    'score': 3.385551},
   {'id': 'https://openalex.org/C24671956',
    'wikidata': None,
    'display_name': 'Fusion power',
    'level': 3,
    'score': 2.3425627},
   {'id': 'https://openalex.org/C116468062',
    'wikidata': None,
    'display_name': 'Electric current',
    'level': 2,
    'score': 2.1710656},
   {'id': 'https://openalex.org/C69285833',
    'wikidata': None,
    'display_name': 'Nuclear fusion',
    'level': 2,
    'score': 1.9093282},
   {'id': 'https://openalex.org/C107430045',
    'wikidata': None,
    'display_name': 'Inertial confinement fusion',
    'level': 3,
    'score': 1.8921918},
   {'id': 'https://openalex.org/C114331627',
    'wikidata': None,
    'display_name': 'Marx generator',
    'level': 4,
    'score': 1.8807838},
   {'id': 'https://openalex.org/C44012409',
    'wikidata': None,
    'display_name': 'Watt',
    'level': 3,
    'score': 1.8622965},
   {'id': 'https://openalex.org/C14589660',
    'wikidata': None,
    'display_name': 'Electromagnetic pulse',
    'level': 2,
    'score': 1.7751479},
   {'id': 'https://openalex.org/C554190296',
    'wikidata': None,
    'display_name': 'Radar',
    'level': 2,
    'score': 1.6652788},
   {'id': 'https://openalex.org/C520434653',
    'wikidata': None,
    'display_name': 'Laser',
    'level': 2,
    'score': 1.6191747},
   {'id': 'https://openalex.org/C189166818',
    'wikidata': None,
    'display_name': 'Particle accelerator',
    'level': 3,
    'score': 1.570331},
   {'id': 'https://openalex.org/C115260700',
    'wikidata': None,
    'display_name': 'Magnetic field',
    'level': 2,
    'score': 1.4619312},
   {'id': 'https://openalex.org/C194110935',
    'wikidata': None,
    'display_name': 'Nuclear weapon',
    'level': 2,
    'score': 1.4485346},
   {'id': 'https://openalex.org/C67737819',
    'wikidata': None,
    'display_name': 'Spark gap',
    'level': 3,
    'score': 1.4448732},
   {'id': 'https://openalex.org/C2779824264',
    'wikidata': None,
    'display_name': 'Z-pinch',
    'level': 3,
    'score': 1.3922803},
   {'id': 'https://openalex.org/C14480152',
    'wikidata': None,
    'display_name': 'Pinch',
    'level': 2,
    'score': 1.3855933},
   {'id': 'https://openalex.org/C2779543734',
    'wikidata': None,
    'display_name': 'Electromagnetic forming',
    'level': 3,
    'score': 1.1975492}],
  'counts_by_year': [{'year': 2024, 'works_count': 67, 'cited_by_count': 2646},
   {'year': 2023, 'works_count': 415, 'cited_by_count': 9318},
   {'year': 2022, 'works_count': 379, 'cited_by_count': 7824},
   {'year': 2021, 'works_count': 423, 'cited_by_count': 7323},
   {'year': 2020, 'works_count': 393, 'cited_by_count': 6085},
   {'year': 2019, 'works_count': 404, 'cited_by_count': 5442},
   {'year': 2018, 'works_count': 399, 'cited_by_count': 4930},
   {'year': 2017, 'works_count': 410, 'cited_by_count': 4638},
   {'year': 2016, 'works_count': 375, 'cited_by_count': 3928},
   {'year': 2015, 'works_count': 432, 'cited_by_count': 4026},
   {'year': 2014, 'works_count': 456, 'cited_by_count': 4041},
   {'year': 2013, 'works_count': 607, 'cited_by_count': 3540},
   {'year': 2012, 'works_count': 440, 'cited_by_count': 3387}],
  'works_api_url': 'https://api.openalex.org/works?filter=concepts.id:C97039730',
  'updated_date': '2024-05-12T13:42:07.589780',
  'created_date': '2016-06-24'},
 {'id': 'https://openalex.org/C522053795',
  'wikidata': 'https://www.wikidata.org/wiki/Q2335090',
  'display_name': 'Missile guidance',
  'relevance_score': 10389.899,
  'level': 3,
  'description': 'variety of methods of guiding a missile',
  'works_count': 6487,
  'cited_by_count': 36160,
  'summary_stats': {'2yr_mean_citedness': 1.4244186046511629,
   'h_index': 82,
   'i10_index': 634},
  'ids': {'openalex': 'https://openalex.org/C522053795',
   'wikidata': 'https://www.wikidata.org/wiki/Q2335090',
   'mag': '522053795',
   'wikipedia': 'https://en.wikipedia.org/wiki/Missile%20guidance'},
  'image_url': 'https://upload.wikimedia.org/wikipedia/commons/6/68/Image-GBU-24_Missile_testmontage-gi_BLU-109_bomb.jpg',
  'image_thumbnail_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Image-GBU-24_Missile_testmontage-gi_BLU-109_bomb.jpg/42px-Image-GBU-24_Missile_testmontage-gi_BLU-109_bomb.jpg',
  'international': {'display_name': {'ar': 'توجيه الصاروخ',
    'be-tarask': 'сыстэма навядзеньня ракеты',
    'bn': 'ক্ষেপণাস্ত্রের পথপ্রদর্শন',
    'ca': 'Guiatge de míssils',
    'cs': 'navádění střely',
    'de': 'Raketenlenkung',
    'en': 'missile guidance',
    'es': 'guiado de misiles',
    'et': 'Raketi juhtimine',
    'fa': 'هدایت موشک',
    'fr': 'Guidage de missile',
    'he': 'נשק מונחה',
    'ja': 'ミサイルの誘導方式',
    'kk': 'Өздігінен бағытталу жүйесі',
    'kk-arab': 'وزدىگىنەن باعىتتالۋ جۇيەسى',
    'kk-cyrl': 'Өздігінен бағытталу жүйесі',
    'kk-latn': 'Özdiginen bağıttalw jüýesi',
    'ko': '미사일 유도',
    'nb': 'Spesialildledning',
    'ru': 'Система самонаведения',
    'ta': 'வழி செலுத்திய ஏவுகணை',
    'uk': 'система наведення ракети',
    'vi': 'Tên lửa có điều khiển',
    'zh': '导弹制导',
    'zh-hans': '导弹制导',
    'zh-hant': '導彈制導',
    'zh-hk': '導彈制導',
    'zh-tw': '飛彈導引'},
   'description': {'de': 'Vielzahl von Methoden der Führung einer Rakete',
    'en': 'variety of methods of guiding a missile',
    'es': 'misil que sigue o persigue a su objetivo',
    'fr': 'ensemble des opérations qui permettent au missile de remplir sa mission, d’approche de sa cible',
    'he': 'חימוש בעל מערכות הנחייה עצמאיות או מונהגות ע"י מפעיל',
    'uk': 'система керування ракетами або бомбами для ураження цілей'}},
  'ancestors': [{'id': 'https://openalex.org/C2778857364',
    'wikidata': 'https://www.wikidata.org/wiki/Q974850',
    'display_name': 'Missile',
    'level': 2},
   {'id': 'https://openalex.org/C146978453',
    'wikidata': 'https://www.wikidata.org/wiki/Q3798668',
    'display_name': 'Aerospace engineering',
    'level': 1},
   {'id': 'https://openalex.org/C166957645',
    'wikidata': 'https://www.wikidata.org/wiki/Q23498',
    'display_name': 'Archaeology',
    'level': 1},
   {'id': 'https://openalex.org/C127413603',
    'wikidata': 'https://www.wikidata.org/wiki/Q11023',
    'display_name': 'Engineering',
    'level': 0},
   {'id': 'https://openalex.org/C205649164',
    'wikidata': 'https://www.wikidata.org/wiki/Q1071',
    'display_name': 'Geography',
    'level': 0},
   {'id': 'https://openalex.org/C95457728',
    'wikidata': 'https://www.wikidata.org/wiki/Q309',
    'display_name': 'History',
    'level': 0}],
  'related_concepts': [{'id': 'https://openalex.org/C2778857364',
    'wikidata': None,
    'display_name': 'Missile',
    'level': 2,
    'score': 13.318895},
   {'id': 'https://openalex.org/C554190296',
    'wikidata': None,
    'display_name': 'Radar',
    'level': 2,
    'score': 9.163574},
   {'id': 'https://openalex.org/C28849524',
    'wikidata': None,
    'display_name': 'Cruise missile',
    'level': 3,
    'score': 9.047797},
   {'id': 'https://openalex.org/C202802212',
    'wikidata': None,
    'display_name': 'Air-to-air missile',
    'level': 3,
    'score': 8.712841},
   {'id': 'https://openalex.org/C128651787',
    'wikidata': None,
    'display_name': 'Inertial navigation system',
    'level': 3,
    'score': 6.200868},
   {'id': 'https://openalex.org/C137355542',
    'wikidata': None,
    'display_name': 'World War II',
    'level': 2,
    'score': 4.0803022},
   {'id': 'https://openalex.org/C131426668',
    'wikidata': None,
    'display_name': 'Electronic countermeasure',
    'level': 3,
    'score': 4.0129113},
   {'id': 'https://openalex.org/C60229501',
    'wikidata': None,
    'display_name': 'Global Positioning System',
    'level': 2,
    'score': 3.6608455},
   {'id': 'https://openalex.org/C201004817',
    'wikidata': None,
    'display_name': 'Guidance system',
    'level': 2,
    'score': 2.6262429},
   {'id': 'https://openalex.org/C2777047555',
    'wikidata': None,
    'display_name': 'Terminal guidance',
    'level': 3,
    'score': 2.154631},
   {'id': 'https://openalex.org/C554876149',
    'wikidata': None,
    'display_name': 'Radio control',
    'level': 2,
    'score': 2.1314445},
   {'id': 'https://openalex.org/C2780928442',
    'wikidata': None,
    'display_name': 'Line-of-sight',
    'level': 2,
    'score': 1.8697124},
   {'id': 'https://openalex.org/C2778464233',
    'wikidata': None,
    'display_name': 'Proportional navigation',
    'level': 3,
    'score': 1.7503211},
   {'id': 'https://openalex.org/C21593369',
    'wikidata': None,
    'display_name': 'Countermeasure',
    'level': 2,
    'score': 1.7447729}],
  'counts_by_year': [{'year': 2024, 'works_count': 20, 'cited_by_count': 822},
   {'year': 2023, 'works_count': 175, 'cited_by_count': 3106},
   {'year': 2022, 'works_count': 182, 'cited_by_count': 3273},
   {'year': 2021, 'works_count': 162, 'cited_by_count': 2910},
   {'year': 2020, 'works_count': 145, 'cited_by_count': 2849},
   {'year': 2019, 'works_count': 184, 'cited_by_count': 2496},
   {'year': 2018, 'works_count': 187, 'cited_by_count': 2363},
   {'year': 2017, 'works_count': 153, 'cited_by_count': 1968},
   {'year': 2016, 'works_count': 172, 'cited_by_count': 2032},
   {'year': 2015, 'works_count': 223, 'cited_by_count': 1872},
   {'year': 2014, 'works_count': 267, 'cited_by_count': 1561},
   {'year': 2013, 'works_count': 311, 'cited_by_count': 1148},
   {'year': 2012, 'works_count': 291, 'cited_by_count': 1004}],
  'works_api_url': 'https://api.openalex.org/works?filter=concepts.id:C522053795',
  'updated_date': '2024-05-12T14:07:51.861104',
  'created_date': '2016-06-24'},
 {'id': 'https://openalex.org/C117623542',
  'wikidata': 'https://www.wikidata.org/wiki/Q621974',
  'display_name': 'Automatic target recognition',
  'relevance_score': 9972.467,
  'level': 3,
  'description': 'ability to automatically recognize targets',
  'works_count': 3634,
  'cited_by_count': 31597,
  'summary_stats': {'2yr_mean_citedness': 3.278481012658228,
   'h_index': 75,
   'i10_index': 629},
  'ids': {'openalex': 'https://openalex.org/C117623542',
   'wikidata': 'https://www.wikidata.org/wiki/Q621974',
   'mag': '117623542',
   'wikipedia': 'https://en.wikipedia.org/wiki/Automatic%20target%20recognition'},
  'image_url': None,
  'image_thumbnail_url': None,
  'international': {'display_name': {'ca': "Reconeixement automàtic de l'objectiu",
    'en': 'Automatic target recognition',
    'es': 'Reconocimiento Automático de Objetivo',
    'id': 'Pengenalan target otomatis',
    'ja': '自動目標識別',
    'mr': 'स्वयंलक्ष्यनिर्धारण',
    'tr': 'Otomatik hedef tanıma',
    'uk': 'Автоматичне розпізнавання цілі',
    'zh': '自动目标识别'},
   'description': {'en': 'ability to automatically recognize targets'}},
  'ancestors': [{'id': 'https://openalex.org/C87360688',
    'wikidata': 'https://www.wikidata.org/wiki/Q740686',
    'display_name': 'Synthetic aperture radar',
    'level': 2},
   {'id': 'https://openalex.org/C154945302',
    'wikidata': 'https://www.wikidata.org/wiki/Q11660',
    'display_name': 'Artificial intelligence',
    'level': 1},
   {'id': 'https://openalex.org/C31972630',
    'wikidata': 'https://www.wikidata.org/wiki/Q844240',
    'display_name': 'Computer vision',
    'level': 1},
   {'id': 'https://openalex.org/C62649853',
    'wikidata': 'https://www.wikidata.org/wiki/Q199687',
    'display_name': 'Remote sensing',
    'level': 1},
   {'id': 'https://openalex.org/C41008148',
    'wikidata': 'https://www.wikidata.org/wiki/Q21198',
    'display_name': 'Computer science',
    'level': 0},
   {'id': 'https://openalex.org/C205649164',
    'wikidata': 'https://www.wikidata.org/wiki/Q1071',
    'display_name': 'Geography',
    'level': 0},
   {'id': 'https://openalex.org/C127313418',
    'wikidata': 'https://www.wikidata.org/wiki/Q1069',
    'display_name': 'Geology',
    'level': 0}],
  'related_concepts': [{'id': 'https://openalex.org/C554190296',
    'wikidata': None,
    'display_name': 'Radar',
    'level': 2,
    'score': 2.8605235},
   {'id': 'https://openalex.org/C142433447',
    'wikidata': None,
    'display_name': 'Time–frequency analysis',
    'level': 3,
    'score': 1.2715209},
   {'id': 'https://openalex.org/C50878840',
    'wikidata': None,
    'display_name': 'Ambiguity function',
    'level': 4,
    'score': 1.2355801},
   {'id': 'https://openalex.org/C65165936',
    'wikidata': None,
    'display_name': 'Baseband',
    'level': 3,
    'score': 1.1843786},
   {'id': 'https://openalex.org/C87360688',
    'wikidata': None,
    'display_name': 'Synthetic aperture radar',
    'level': 2,
    'score': 1.1573641},
   {'id': 'https://openalex.org/C28849524',
    'wikidata': None,
    'display_name': 'Cruise missile',
    'level': 3,
    'score': 1.0891315},
   {'id': 'https://openalex.org/C60229501',
    'wikidata': None,
    'display_name': 'Global Positioning System',
    'level': 2,
    'score': 1.0661001},
   {'id': 'https://openalex.org/C102519508',
    'wikidata': None,
    'display_name': 'Fourier transform',
    'level': 2,
    'score': 1.03755},
   {'id': 'https://openalex.org/C28490314',
    'wikidata': None,
    'display_name': 'Speech recognition',
    'level': 1,
    'score': 0.9964525},
   {'id': 'https://openalex.org/C151077058',
    'wikidata': None,
    'display_name': 'Wigner distribution function',
    'level': 3,
    'score': 0.9511871},
   {'id': 'https://openalex.org/C166386157',
    'wikidata': None,
    'display_name': 'Short-time Fourier transform',
    'level': 4,
    'score': 0.9203837},
   {'id': 'https://openalex.org/C119857082',
    'wikidata': None,
    'display_name': 'Machine learning',
    'level': 1,
    'score': 0.8757511},
   {'id': 'https://openalex.org/C203024314',
    'wikidata': None,
    'display_name': 'Fourier analysis',
    'level': 3,
    'score': 0.8208903},
   {'id': 'https://openalex.org/C139931591',
    'wikidata': None,
    'display_name': 'Pulse-Doppler radar',
    'level': 4,
    'score': 0.77053654}],
  'counts_by_year': [{'year': 2024, 'works_count': 31, 'cited_by_count': 803},
   {'year': 2023, 'works_count': 232, 'cited_by_count': 3949},
   {'year': 2022, 'works_count': 214, 'cited_by_count': 3802},
   {'year': 2021, 'works_count': 181, 'cited_by_count': 3187},
   {'year': 2020, 'works_count': 146, 'cited_by_count': 2352},
   {'year': 2019, 'works_count': 155, 'cited_by_count': 2514},

# Co-authorship Network

Streamlit with pyvis: https://towardsdatascience.com/how-to-deploy-interactive-pyvis-network-graphs-on-streamlit-6c401d4c99db

the data source is dftriple; let a user interactively select which type of graph , the selection of node types, to display. otherwise its just too too much.

Can display works and authors; construct that first:

In [189]:
dftriple.columns

Index(['id', 'display_name', 'ror', 'country_code', 'type', 'lineage',
       'paper_id', 'paper_raw_affiliation_strings', 'paper_author_position',
       'paper_doi', 'paper_title', 'paper_abstract', 'paper_publication_date',
       'paper_publication_year', 'paper_grants', 'paper_locations',
       'paper_is_corrresponding', 'paper_x', 'paper_y', 'paper_cluster',
       'paper_cluster_score', 'paper_author_id', 'paper_author_display_name',
       'paper_author_orcid', 'source', 'source_type', 'funder_list'],
      dtype='object')

group dftriple by paper_id and get a list of all the paper_author_id values. and then from that list get all distinct subsets of two paper_author_ids. accumulate that list. and then we will haave a weighted undirected graph.

file://wsl.localhost/Ubuntu/home/davidd/2023/SWITCHBOARD/switchboard-mitigations-sort/graphvizmaker.html

In [190]:
import networkx as nx
from pyvis.network import Network
import igraph as ig # for getting a layout w/o relying on slow pyvis physics

In [191]:
dftriple.columns

Index(['id', 'display_name', 'ror', 'country_code', 'type', 'lineage',
       'paper_id', 'paper_raw_affiliation_strings', 'paper_author_position',
       'paper_doi', 'paper_title', 'paper_abstract', 'paper_publication_date',
       'paper_publication_year', 'paper_grants', 'paper_locations',
       'paper_is_corrresponding', 'paper_x', 'paper_y', 'paper_cluster',
       'paper_cluster_score', 'paper_author_id', 'paper_author_display_name',
       'paper_author_orcid', 'source', 'source_type', 'funder_list'],
      dtype='object')

In [192]:
dfinfo.columns

Index(['x', 'y', 'id', 'title', 'doi', 'cluster', 'probability',
       'publication_date', 'grants', 'locations', 'keywords', 'top_concepts',
       'author_list', 'affil_list', 'authors_list', 'wrapped_affil_list',
       'wrapped_author_list', 'wrapped_keywords', 'source', 'source_type'],
      dtype='object')

In [193]:
dfinfo["funder_list"] = dfinfo["grants"].apply(get_funder_names)
dfinfo["wrapped_funder_list"] = dfinfo["funder_list"].apply(str).apply(wrap_it)

In [194]:
dfinfo.to_pickle('updatejammingdfinfo2d.pkl')

In [195]:
dfinfo[['id','keywords','wrapped_keywords','wrapped_funder_list']].head()

,id,keywords,wrapped_keywords,wrapped_funder_list
id,,,,
https://openalex.org/W1517236425,https://openalex.org/W1517236425,"[Robot Manipulators, Neural network controller...","['Robot Manipulators', 'Neural network<br>cont...",[]
https://openalex.org/W2740675802,https://openalex.org/W2740675802,"[Time-Varying Output Constraints, Output Const...","['Time-Varying Output Constraints',<br>'Output...",['National Natural Science Foundation of<br>Ch...
https://openalex.org/W2418767125,https://openalex.org/W2418767125,"[Flexible Robotic Manipulator, Flexible Roboti...","['Flexible Robotic Manipulator',<br>'Flexible ...",['National Natural Science Foundation of<br>Ch...
https://openalex.org/W2901112449,https://openalex.org/W2901112449,"[Soft Robotic Manipulators, Soft Robotic, Mode...","['Soft Robotic Manipulators', 'Soft<br>Robotic...",[]
https://openalex.org/W2792852625,https://openalex.org/W2792852625,"[neural networks, neural, Robot manipulators, ...","['neural networks', 'neural', 'Robot<br>manipu...","['Research Grants Council, University<br>Grant..."

In [196]:
kw_dict = dfinfo['keywords'].to_dict()

In [197]:
dftriple[['source','source_type']].head()

                                              source source_type
0                   IEEE transactions on cybernetics     journal
1                   IEEE transactions on cybernetics     journal
2                   IEEE transactions on cybernetics     journal
3  IEEE transactions on systems, man, and cyberne...     journal
4  IEEE transactions on systems, man, and cyberne...     journal

In [198]:
dftriple.head()

,id,display_name,ror,country_code,type,lineage,paper_id,paper_raw_affiliation_strings,paper_author_position,paper_doi,...,paper_x,paper_y,paper_cluster,paper_cluster_score,paper_author_id,paper_author_display_name,paper_author_orcid,source,source_type,funder_list
0,https://openalex.org/I92403157,University of Science and Technology Beijing,https://ror.org/02egmk993,CN,education,[https://openalex.org/I92403157],https://openalex.org/W2740675802,"[Ministry of Education, Key Laboratory of Know...",first,https://doi.org/10.1109/tcyb.2017.2711961,...,13.561797,-7.088242,1,1.0,https://openalex.org/A5022113595,Wei He,https://orcid.org/0000-0002-8944-9861,IEEE transactions on cybernetics,journal,"[National Natural Science Foundation of China,..."
1,https://openalex.org/I92403157,University of Science and Technology Beijing,https://ror.org/02egmk993,CN,education,[https://openalex.org/I92403157],https://openalex.org/W2740675802,"[Ministry of Education, Key Laboratory of Know...",middle,https://doi.org/10.1109/tcyb.2017.2711961,...,13.561797,-7.088242,1,1.0,https://openalex.org/A5055142075,Haifeng Huang,https://orcid.org/0000-0002-1615-3779,IEEE transactions on cybernetics,journal,"[National Natural Science Foundation of China,..."
2,https://openalex.org/I165932596,National University of Singapore,https://ror.org/01tgyzw49,SG,education,[https://openalex.org/I165932596],https://openalex.org/W2740675802,[Department of Electrical and Computer Enginee...,last,https://doi.org/10.1109/tcyb.2017.2711961,...,13.561797,-7.088242,1,1.0,https://openalex.org/A5069702292,Shuzhi Sam Ge,None,IEEE transactions on cybernetics,journal,"[National Natural Science Foundation of China,..."
3,https://openalex.org/I76569877,Southeast University,https://ror.org/04ct4d772,CN,education,[https://openalex.org/I76569877],https://openalex.org/W2418767125,"[School of Automation, Southeast University, N...",first,https://doi.org/10.1109/tsmc.2016.2562506,...,13.26959,-6.870666,1,1.0,https://openalex.org/A5019248683,Changyin Sun,https://orcid.org/0000-0001-9269-334X,"IEEE transactions on systems, man, and cyberne...",journal,[National Natural Science Foundation of China]
4,https://openalex.org/I92403157,University of Science and Technology Beijing,https://ror.org/02egmk993,CN,education,[https://openalex.org/I92403157],https://openalex.org/W2418767125,[School of Automation and Electrical Engineeri...,middle,https://doi.org/10.1109/tsmc.2016.2562506,...,13.26959,-6.870666,1,1.0,https://openalex.org/A5061536058,Wei He,https://orcid.org/0000-0001-8321-8256,"IEEE transactions on systems, man, and cyberne...",journal,[National Natural Science Foundation of China]

In [199]:
dc = dftriple[dftriple['paper_cluster'] == 10].copy()
dc.shape

(11, 27)

In [200]:
[x for row in dc['funder_list'].tolist() for x in row]

[]

In [201]:
dftriple['funder_list'].value_counts().head()

[]                                                                                                         22386
[National Natural Science Foundation of China]                                                              3841
[U.S. Department of Energy]                                                                                  359
[National Natural Science Foundation of China, Fundamental Research Funds for the Central Universities]      215
[National Natural Science Foundation of China, China Postdoctoral Science Foundation]                        206
Name: funder_list, dtype: int64

In [202]:
kw_dict = dfinfo['keywords'].to_dict()

# add in the affiliations as nodes as well; that row, author, paper, affil. all three get links. ok.
def create_nx_graph(df: pd.DataFrame, cl:int) -> nx.Graph:
    """
    takes the dataframe df, and creates the undirected graph
    from the source and target columns for each row.
    """
    g = nx.Graph() # dc['paper_cluster'] == cl
    dc = df[df['paper_cluster'] == cl]
    author_counts = dc['paper_author_id'].tolist()
    author_counts_dict = {c:author_counts.count(c) for c in author_counts}
    affiliation_counts = dc['id'].tolist()
    affiliation_counts_dict = {c:affiliation_counts.count(c) for c in affiliation_counts}
    source_counts = dc['source'].tolist()
    source_counts_dict = {c:source_counts.count(c) for c in source_counts}
    funder_counts = [x for row in dc['funder_list'].tolist() for x in row]
    funder_counts_dict = {c:funder_counts.count(c) for c in funder_counts}
    for index, row in df[df['paper_cluster'] == cl].iterrows():
        g.add_node(row['paper_id'], group='work', title=row['paper_title'])
        g.add_node(row['paper_author_id'], title=row['paper_author_display_name'],
                   group='author',value = author_counts_dict[row['paper_author_id']])
        g.add_node(row['id'], group='affiliation',
                   title=row['display_name'] + '\n' + row['country_code'],
                  value = affiliation_counts_dict[row['id']])
        if row['source']:
            g.add_node(row['source'], group=row['source_type'],
                      title=row['source'] + ' :\n ' + row['source_type'],
                      value=source_counts_dict[row['source']])
            g.add_edge(
                row['paper_id'],
                row['source'],
                title=row['paper_title'] + ' :\n ' + str(row['paper_publication_date']) +  \
                ' :\n' + row['source'] + ' :\n ' + \
                row['source_type'],
              #  weight = df[(df['paper_id'] == row['paper_id']) & \
              #              (df['source'] == row['source'])]['paper_cluster_score'].sum()
               # weight = row['paper_cluster_score']
            )
            g.add_edge(
                row['paper_author_id'],
                row['source'],
                title=row['paper_author_display_name'] + ':\n' + row['source'],
             #   weight = df[(df['paper_author_id'] == row['paper_author_id']) & \
              #              (df['source'] == row['source'])]['paper_cluster_score'].sum()
               # weight = row['paper_cluster_score']
            )
        if len(row['funder_list']) > 0:
            for f in row['funder_list']:
                g.add_node(f, group='funder',
                          title=str(f),
                          value = founder_counts_dict[f]),
                g.add_edge(
                       row['paper_id'],
                       f,
                       title=row['paper_title'] + ':\n ' +  str(row['paper_publication_date']) + \
                       ' :\n' + str(f),
                  #  weight = row['paper_cluster_score']
                   )
                g.add_edge(
                       f,
                       row['paper_author_id'],
                       title=row['paper_author_display_name'] + ' :\n ' + \
                       str(f),
                  #  weight = row['paper_cluster_score']
                       
                   )
                g.add_edge(
                       f,
                       row['id'],
                       title=row['display_name'] + '\n' + row['country_code'] + ' :\n ' + \
                       str(f)  ,
                  #  weight = row['paper_cluster_score']
                   )  
                if row["source"]:
                    g.add_edge(
                        f,
                        row["source"],
                        title=row["source"] + ' :\n' + str(f),
                     #   weight = row['paper_cluster_score']
                    )
        g.nodes[row['paper_id']]['title'] = (
            row['paper_title'] + ' :\n ' + str(row['paper_publication_date'] + ':\n' + 
            '\n'.join(kw_dict[row['paper_id']]))
        )
        g.nodes[row['paper_author_id']]['title'] = (
            row['paper_author_display_name']
        )
        g.add_edge(
            row['paper_id'],
            row['paper_author_id'],
        title=row['paper_title'] + ' :\n ' + row['paper_author_display_name'] + ' :\n ' + \
            row['paper_raw_affiliation_string'],
         #   weight = row['paper_cluster_score']
        )
        g.add_edge(
            row['paper_author_id'],
            row['id'],
            title=row['paper_author_display_name'] + ' :\n ' + \
            row['display_name'] + ' :\n ' + row['country_code'],
          #  weight = row['paper_cluster_score']
        )
        g.add_edge(
            row['paper_id'],
            row['id'],
            title=row['paper_title'] + ' :\n ' + str(row['paper_publication_date']) + ':\n' + 
            row['display_name'] + ' :\n ' + row['country_code'],
         #   weight = row['paper_cluster_score']
        )
        
    g_ig = ig.Graph.from_networkx(g) # assign 'x', and 'y' to g before returning
    #layout = g_ig.layout_auto()
    #layout = g_ig.layout_davidson_harel()
    layout = g_ig.layout_umap(min_dist = 2, epochs = 500)
    # https://igraph.org/python/tutorial/0.9.6/visualisation.html
    coords = layout.coords
    allnodes = list(g.nodes())
    coords_dict = {allnodes[i]:(coords[i][0], coords[i][1]) for i in range(len(allnodes))}
    for i in g.nodes():
        g.nodes[i]['x'] = 250 * coords_dict[i][0] # the scale factor needed 
        g.nodes[i]['y'] = 250 * coords_dict[i][1]
    return g

In [203]:
def create_pyvis_html(cl: int, filename: str = "pyvis_coauthorships_graph.html"):
    """
    wrapper function that calls create_nx_graph to finally 
    produce an interactive pyvis standalone html file
    """
    g_nx = create_nx_graph(dftriple, cl);
    h = Network(height="1000px",
          #  heading="Mitigations and Techniques Relationships",
                width="100%",
                cdn_resources="remote", # can grab the visjs library to make this local if needed
            # probably should
                bgcolor="#222222",
            neighborhood_highlight=True,
              # default_node_size=1,
                font_color="white",
                directed=False,
               # select_menu=True,
                filter_menu=True,
                notebook=False,
               )
    #h.repulsion()
    h.from_nx(g_nx, show_edge_weights=False)
    #h.barnes_hut()
    #h.repulsion(node_distance=40,
    #            central_gravity=-0.2, spring_length=5, spring_strength=0.005, damping=0.09)
    neighbor_map = h.get_adj_list()
   # for node in h.nodes:
   #     if node['group'] == 'author':
   #         a = list(neighbor_map[node["id"]]) # want to insert a "\n" into every third element of a
   #     if node['group'] == 'work':
   #         a = list(neighbor_map[node["id"]])
   #     i = 3
   #     while i < len(a):
   #         a.insert(i, "\n")
   #         i += 4
   #     node["title"] += "\n Neighbors: \n" + " | ".join(a)
   #     node["value"] = len(neighbor_map[node["id"]]) 
# "physics": {
#    "enabled": false
#  },
    h.set_options(
    """
const options = {
  "interaction": {
    "navigationButtons": false
  },
 "physics": {
     "enabled": false
 },
  "edges": {
    "color": {
        "inherit": true
    },
    "setReferenceSize": null,
    "setReference": {
        "angle": 0.7853981633974483
    },
    "smooth": {
        "forceDirection": "none"
    }
  }
  }
    """
    )
    #h.show_buttons(filter_=['physics'])
  #  h.barnes_hut()
    #h.repulsion()
    try:
        path = './tmp'
        h.save_graph(f"{path}/{filename}")
        HtmlFile = open(f"{path}/{filename}","r",
                        encoding='utf-8')
    except:
        h.save_graph(f"{filename}")
        HtmlFile = open(f"{filename}", "r",
                        encoding="utf-8")
    return h

In [204]:
dfinfo.shape

(9301, 22)

In [205]:
dfinfo.columns

Index(['x', 'y', 'id', 'title', 'doi', 'cluster', 'probability',
       'publication_date', 'grants', 'locations', 'keywords', 'top_concepts',
       'author_list', 'affil_list', 'authors_list', 'wrapped_affil_list',
       'wrapped_author_list', 'wrapped_keywords', 'source', 'source_type',
       'funder_list', 'wrapped_funder_list'],
      dtype='object')

In [206]:
dfinfo[['author_list','authors_list']].head()

,author_list,authors_list
id,,
https://openalex.org/W1517236425,NaN,NaN
https://openalex.org/W2740675802,"[Wei He, Haifeng Huang, Shuzhi Sam Ge]","[Wei He, Haifeng Huang, Shuzhi Sam Ge]"
https://openalex.org/W2418767125,"[Changyin Sun, Wei He, Jin‐Woo Hong]","[Changyin Sun, Wei He, Jin‐Woo Hong]"
https://openalex.org/W2901112449,"[Thomas George Thuruthel, Egidio Falotico, Fed...","[Thomas George Thuruthel, Egidio Falotico, Fed..."
https://openalex.org/W2792852625,"[Long Jin, Shuai Li, Jiguo Yu, Jinbo He]","[Long Jin, Shuai Li, Jiguo Yu, Jinbo He]"

In [207]:
del dfinfo['authors_list']

In [208]:
dfinfo.shape

(9301, 21)

In [209]:
dfinfo[['cluster','probability','publication_date']].head()

                                  cluster  probability publication_date
id
https://openalex.org/W1517236425        1          1.0       2020-08-13
https://openalex.org/W2740675802        1          1.0       2017-10-01
https://openalex.org/W2418767125        1          1.0       2017-08-01
https://openalex.org/W2901112449        1          1.0       2019-02-01
https://openalex.org/W2792852625        1          1.0       2018-04-01

In [210]:
dftime = dfinfo[['cluster','probability','publication_date']].copy()

In [211]:
dftime['publication_datetime'] = pd.to_datetime(dftime['publication_date'])

In [212]:
dftime.head()

,cluster,probability,publication_date,publication_datetime
id,,,,
https://openalex.org/W1517236425,1,1.0,2020-08-13,2020-08-13
https://openalex.org/W2740675802,1,1.0,2017-10-01,2017-10-01
https://openalex.org/W2418767125,1,1.0,2017-08-01,2017-08-01
https://openalex.org/W2901112449,1,1.0,2019-02-01,2019-02-01
https://openalex.org/W2792852625,1,1.0,2018-04-01,2018-04-01

In [213]:
def get_time_series(dg, cl:int):
    """
    takes dg and the cluster number cl
    and returns a time series chart
    by month, y-axis is the article count
    """
    dftime = dg[dg.cluster == cl][['cluster','probability','publication_date']].copy()
    dftime['date'] = pd.to_datetime(dftime['publication_date'])
    dftime.sort_values('date', inplace=True)
    #by_month = pd.to_datetime(dftime['date']).dt.to_period('M').value_counts().sort_index()
    #by_month.index = pd.PeriodIndex(by_month.index)
    #df_month = by_month.rename_axis('month').reset_index(name='counts')
    return dftime

In [214]:
dfinfo.cluster.value_counts().head()

-1     2292
 1     1899
 34     381
 78     289
 81     204
Name: cluster, dtype: int64

In [215]:
df_month_21 = get_time_series(dfinfo, 12)
df_month_21.head()

,cluster,probability,publication_date,date
id,,,,
https://openalex.org/W2743450334,12,0.760383,2017-01-01,2017-01-01
https://openalex.org/W2751560014,12,0.979145,2017-07-01,2017-07-01
https://openalex.org/W2781553841,12,1.000000,2017-11-01,2017-11-01
https://openalex.org/W2795077684,12,0.998225,2017-12-01,2017-12-01
https://openalex.org/W2942601417,12,1.000000,2018-01-01,2018-01-01

In [216]:
import altair as alt
#alt.data_transformers.enable("data_server")

In [217]:
alt.Chart(df_month_21).mark_line().transform_fold(
    ['probability']
).encode(
    x = 'yearmonth(date):T',
    y = 'sum(value):Q',
    color='key:N'
)

alt.Chart(...)

In [218]:
sources_list = dftriple['source'].unique().tolist()
type(sources_list), len(sources_list)

(list, 1337)

In [235]:
Sources().random()

{'id': 'https://openalex.org/S2755347481',
 'issn_l': '0146-1575',
 'issn': ['0146-1575'],
 'display_name': 'Journal of oral surgery',
 'host_organization': 'https://openalex.org/P4310315755',
 'host_organization_name': 'American Dental Association',
 'host_organization_lineage': ['https://openalex.org/P4310315755'],
 'works_count': 100,
 'cited_by_count': 83,
 'summary_stats': {'2yr_mean_citedness': 0.0, 'h_index': 54, 'i10_index': 739},
 'is_oa': False,
 'is_in_doaj': False,
 'ids': {'openalex': 'https://openalex.org/S2755347481',
  'issn_l': '0146-1575',
  'issn': ['0146-1575'],
  'mag': '2755347481',
  'wikidata': 'https://www.wikidata.org/entity/Q27720654',
  'fatcat': 'https://fatcat.wiki/container/bxbvtsdktndfhnv4p2tngbud74'},
 'homepage_url': None,
 'apc_prices': None,
 'apc_usd': None,
 'country_code': 'US',
 'societies': [],
 'alternate_titles': [],
 'abbreviated_title': None,
 'type': 'journal',
 'topics': [{'id': 'https://openalex.org/T11787',
   'display_name': 'Classification and Management of Odontogenic Tumors',
   'count': 730,
   'subfield': {'id': 'https://openalex.org/subfields/3504',
    'display_name': 'Oral Surgery'},
   'field': {'id': 'https://openalex.org/fields/35',
    'display_name': 'Dentistry'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10975',
   'display_name': 'Bone Tumors and Tumor-like Conditions in Skeletal System',
   'count': 403,
   'subfield': {'id': 'https://openalex.org/subfields/2745',
    'display_name': 'Rheumatology'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11562',
   'display_name': 'Epidemiology and Management of Maxillofacial Trauma',
   'count': 324,
   'subfield': {'id': 'https://openalex.org/subfields/2746',
    'display_name': 'Surgery'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11374',
   'display_name': 'Genetic and Environmental Influences on Cleft Lip and Palate',
   'count': 231,
   'subfield': {'id': 'https://openalex.org/subfields/1311',
    'display_name': 'Genetics'},
   'field': {'id': 'https://openalex.org/fields/13',
    'display_name': 'Biochemistry, Genetics and Molecular Biology'},
   'domain': {'id': 'https://openalex.org/domains/1',
    'display_name': 'Life Sciences'}},
  {'id': 'https://openalex.org/T11679',
   'display_name': 'Genetics and Development of Craniofacial Abnormalities',
   'count': 195,
   'subfield': {'id': 'https://openalex.org/subfields/1311',
    'display_name': 'Genetics'},
   'field': {'id': 'https://openalex.org/fields/13',
    'display_name': 'Biochemistry, Genetics and Molecular Biology'},
   'domain': {'id': 'https://openalex.org/domains/1',
    'display_name': 'Life Sciences'}},
  {'id': 'https://openalex.org/T12379',
   'display_name': 'Cancer of Unknown Primary Site',
   'count': 190,
   'subfield': {'id': 'https://openalex.org/subfields/2730',
    'display_name': 'Oncology'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T14134',
   'display_name': 'Evolution and Usage of Anatomical Nomenclature',
   'count': 186,
   'subfield': {'id': 'https://openalex.org/subfields/2702',
    'display_name': 'Anatomy'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T13383',
   'display_name': 'Granular Cell Tumor: Clinical and Pathological Characteristics',
   'count': 183,
   'subfield': {'id': 'https://openalex.org/subfields/2734',
    'display_name': 'Pathology and Forensic Medicine'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T13457',
   'display_name': 'Motivation and Career Choices in Dentistry',
   'count': 176,
   'subfield': {'id': 'https://openalex.org/subfields/3600',
    'display_name': 'General Health Professions'},
   'field': {'id': 'https://openalex.org/fields/36',
    'display_name': 'Health Professions'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11363',
   'display_name': 'Cone-Beam Computed Tomography in Dentistry',
   'count': 175,
   'subfield': {'id': 'https://openalex.org/subfields/3504',
    'display_name': 'Oral Surgery'},
   'field': {'id': 'https://openalex.org/fields/35',
    'display_name': 'Dentistry'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11669',
   'display_name': 'Endoscopic Skull Base Surgery Techniques',
   'count': 169,
   'subfield': {'id': 'https://openalex.org/subfields/2746',
    'display_name': 'Surgery'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11035',
   'display_name': 'Salivary Gland Tumors and Carcinomas',
   'count': 167,
   'subfield': {'id': 'https://openalex.org/subfields/2746',
    'display_name': 'Surgery'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T13768',
   'display_name': 'Risk Factors for Gingival Overgrowth in Medication Use',
   'count': 144,
   'subfield': {'id': 'https://openalex.org/subfields/3611',
    'display_name': 'Pharmacy'},
   'field': {'id': 'https://openalex.org/fields/36',
    'display_name': 'Health Professions'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10830',
   'display_name': 'Management of Difficult Airway in Anesthesia Practice',
   'count': 138,
   'subfield': {'id': 'https://openalex.org/subfields/2703',
    'display_name': 'Anesthesiology and Pain Medicine'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10253',
   'display_name': 'Sarcoma Research and Treatment',
   'count': 137,
   'subfield': {'id': 'https://openalex.org/subfields/2740',
    'display_name': 'Pulmonary and Respiratory Medicine'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10852',
   'display_name': 'Diagnosis and Management of Temporomandibular Disorders',
   'count': 136,
   'subfield': {'id': 'https://openalex.org/subfields/3603',
    'display_name': 'Complementary and Manual Therapy'},
   'field': {'id': 'https://openalex.org/fields/36',
    'display_name': 'Health Professions'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10359',
   'display_name': 'Dental Implantology and Peri-implant Diseases',
   'count': 131,
   'subfield': {'id': 'https://openalex.org/subfields/3504',
    'display_name': 'Oral Surgery'},
   'field': {'id': 'https://openalex.org/fields/35',
    'display_name': 'Dentistry'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11991',
   'display_name': 'Clinicopathology of Fibrous Tumors and Treatment Strategies',
   'count': 124,
   'subfield': {'id': 'https://openalex.org/subfields/2745',
    'display_name': 'Rheumatology'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11919',
   'display_name': 'Molecular Mechanisms of Tooth Development and Morphogenesis',
   'count': 114,
   'subfield': {'id': 'https://openalex.org/subfields/1312',
    'display_name': 'Molecular Biology'},
   'field': {'id': 'https://openalex.org/fields/13',
    'display_name': 'Biochemistry, Genetics and Molecular Biology'},
   'domain': {'id': 'https://openalex.org/domains/1',
    'display_name': 'Life Sciences'}},
  {'id': 'https://openalex.org/T10356',
   'display_name': 'Orthodontic Research and Treatment',
   'count': 112,
   'subfield': {'id': 'https://openalex.org/subfields/3505',
    'display_name': 'Orthodontics'},
   'field': {'id': 'https://openalex.org/fields/35',
    'display_name': 'Dentistry'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T12145',
   'display_name': 'Dental Anxiety and Anesthetic Management in Dentistry',
   'count': 111,
   'subfield': {'id': 'https://openalex.org/subfields/3504',
    'display_name': 'Oral Surgery'},
   'field': {'id': 'https://openalex.org/fields/35',
    'display_name': 'Dentistry'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10980',
   'display_name': 'Classification and Treatment of Vascular Anomalies',
   'count': 98,
   'subfield': {'id': 'https://openalex.org/subfields/2746',
    'display_name': 'Surgery'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10436',
   'display_name': 'Anesthesia and Sedation Management',
   'count': 95,
   'subfield': {'id': 'https://openalex.org/subfields/2703',
    'display_name': 'Anesthesiology and Pain Medicine'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11381',
   'display_name': 'Diagnosis and Treatment of Spinal Infections',
   'count': 87,
   'subfield': {'id': 'https://openalex.org/subfields/2746',
    'display_name': 'Surgery'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11221',
   'display_name': 'Bisphosphonates in Cancer Treatment and Bone Health',
   'count': 85,
   'subfield': {'id': 'https://openalex.org/subfields/2730',
    'display_name': 'Oncology'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}}],
 'topic_share': [{'id': 'https://openalex.org/T11562',
   'display_name': 'Epidemiology and Management of Maxillofacial Trauma',
   'value': 0.0033893,
   'subfield': {'id': 'https://openalex.org/subfields/2746',
    'display_name': 'Surgery'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11787',
   'display_name': 'Classification and Management of Odontogenic Tumors',
   'value': 0.0032598,
   'subfield': {'id': 'https://openalex.org/subfields/3504',
    'display_name': 'Oral Surgery'},
   'field': {'id': 'https://openalex.org/fields/35',
    'display_name': 'Dentistry'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10975',
   'display_name': 'Bone Tumors and Tumor-like Conditions in Skeletal System',
   'value': 0.0025949,
   'subfield': {'id': 'https://openalex.org/subfields/2745',
    'display_name': 'Rheumatology'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11679',
   'display_name': 'Genetics and Development of Craniofacial Abnormalities',
   'value': 0.0017277,
   'subfield': {'id': 'https://openalex.org/subfields/1311',
    'display_name': 'Genetics'},
   'field': {'id': 'https://openalex.org/fields/13',
    'display_name': 'Biochemistry, Genetics and Molecular Biology'},
   'domain': {'id': 'https://openalex.org/domains/1',
    'display_name': 'Life Sciences'}},
  {'id': 'https://openalex.org/T13328',
   'display_name': 'Autoinflammatory Bone Disorders',
   'value': 0.0016993,
   'subfield': {'id': 'https://openalex.org/subfields/2745',
    'display_name': 'Rheumatology'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11374',
   'display_name': 'Genetic and Environmental Influences on Cleft Lip and Palate',
   'value': 0.0015492,
   'subfield': {'id': 'https://openalex.org/subfields/1311',
    'display_name': 'Genetics'},
   'field': {'id': 'https://openalex.org/fields/13',
    'display_name': 'Biochemistry, Genetics and Molecular Biology'},
   'domain': {'id': 'https://openalex.org/domains/1',
    'display_name': 'Life Sciences'}},
  {'id': 'https://openalex.org/T10852',
   'display_name': 'Diagnosis and Management of Temporomandibular Disorders',
   'value': 0.0014541,
   'subfield': {'id': 'https://openalex.org/subfields/3603',
    'display_name': 'Complementary and Manual Therapy'},
   'field': {'id': 'https://openalex.org/fields/36',
    'display_name': 'Health Professions'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T13813',
   'display_name': 'Ankyloglossia and its Impact on Breastfeeding and Speech',
   'value': 0.0013554,
   'subfield': {'id': 'https://openalex.org/subfields/3616',
    'display_name': 'Speech and Hearing'},
   'field': {'id': 'https://openalex.org/fields/36',
    'display_name': 'Health Professions'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T13383',
   'display_name': 'Granular Cell Tumor: Clinical and Pathological Characteristics',
   'value': 0.0012743,
   'subfield': {'id': 'https://openalex.org/subfields/2734',
    'display_name': 'Pathology and Forensic Medicine'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T12145',
   'display_name': 'Dental Anxiety and Anesthetic Management in Dentistry',
   'value': 0.0012534,
   'subfield': {'id': 'https://openalex.org/subfields/3504',
    'display_name': 'Oral Surgery'},
   'field': {'id': 'https://openalex.org/fields/35',
    'display_name': 'Dentistry'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T13768',
   'display_name': 'Risk Factors for Gingival Overgrowth in Medication Use',
   'value': 0.0012466,
   'subfield': {'id': 'https://openalex.org/subfields/3611',
    'display_name': 'Pharmacy'},
   'field': {'id': 'https://openalex.org/fields/36',
    'display_name': 'Health Professions'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T12183',
   'display_name': 'Diagnosis and Management of Fetal and Neonatal Tumors',
   'value': 0.0012259,
   'subfield': {'id': 'https://openalex.org/subfields/2746',
    'display_name': 'Surgery'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T13543',
   'display_name': 'Elongated Styloid Process Syndrome: Clinical and Anatomical Study',
   'value': 0.0011845,
   'subfield': {'id': 'https://openalex.org/subfields/2745',
    'display_name': 'Rheumatology'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T13457',
   'display_name': 'Motivation and Career Choices in Dentistry',
   'value': 0.0011204,
   'subfield': {'id': 'https://openalex.org/subfields/3600',
    'display_name': 'General Health Professions'},
   'field': {'id': 'https://openalex.org/fields/36',
    'display_name': 'Health Professions'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11991',
   'display_name': 'Clinicopathology of Fibrous Tumors and Treatment Strategies',
   'value': 0.0011187,
   'subfield': {'id': 'https://openalex.org/subfields/2745',
    'display_name': 'Rheumatology'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11035',
   'display_name': 'Salivary Gland Tumors and Carcinomas',
   'value': 0.0011187,
   'subfield': {'id': 'https://openalex.org/subfields/2746',
    'display_name': 'Surgery'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T12198',
   'display_name': 'Pathobiology and Management of Mucositis in Cancer Therapy',
   'value': 0.0009913,
   'subfield': {'id': 'https://openalex.org/subfields/2740',
    'display_name': 'Pulmonary and Respiratory Medicine'},
   'field': {'id': 'https://openalex.org/fields/27',
    'display_name': 'Medicine'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10356',
   'display_name': 'Orthodontic Research and Treatment',
   'value': 0.0009811,
   'subfield': {'id': 'https://openalex.org/subfields/3505',
    'display_name': 'Orthodontics'},
   'field': {'id': 'https://openalex.org/fields/35',
    'display_name': 'Dentistry'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T11919',
   'display_name': 'Molecular Mechanisms of Tooth Development and Morphogenesis',
   'value': 0.0009667,
   'subfield': {'id': 'https://openalex.org/subfields/1312',
    'display_name': 'Molecular Biology'},
   'field': {'id': 'https://openalex.org/fields/13',
    'display_name': 'Biochemistry, Genetics and Molecular Biology'},
   'domain': {'id': 'https://openalex.org/domains/1',
    'display_name': 'Life Sciences'}},
  {'id': 'https://openalex.org/T12367',
   'display_name': 'Epidemiology and Management of Traumatic Dental Injuries',
   'value': 0.0009541,
   'subfield': {'id': 'https://openalex.org/subfields/3604',
    'display_name': 'Emergency Medical Services'},
   'field': {'id': 'https://openalex.org/fields/36',
    'display_name': 'Health Professions'},
   'domain': {'id': 'https://openalex.org/domains/4',
    'display_name': 'Health Sciences'}},
  {'id': 'https://openalex.org/T10980',

In [244]:
def get_source_json(s:str):
    """
    s is an openalex Sources display_name
    return that Sources object
    """
    source_json = Sources().search_filter(display_name = s).get()
    a = source_json[0]['type']
    if "homepage_url" in source_json[0] and source_json[0]['homepage_url']:
        print(f"{s} has homepage_url and type {source_json[0]['type']}")
        return source_json[0]["homepage_url"]
    else:
        return None

In [245]:
sources_list[5]

'IEEE transactions on control systems technology'

In [246]:
sj0 = get_source_json(sources_list[5])
sj0

IEEE transactions on control systems technology has homepage_url and type journal

'http://www.ieeecss.org/publications/tcst'

In [247]:
def get_display_page_dict(sl:list):
    """
    sl is a list of Sources display_name values
    returns the dictionary mapping
    display_names with homepage_url values."""
    mapping_dict = dict()
    for s in tqdm(sl):
        try:
            mapping_dict[s] = get_source_json(s)
        except:
            pass
    return mapping_dict

In [248]:
source_page_dict = get_display_page_dict(sources_list)

  0%|                                                                        | 1/1337 [00:01<34:27,  1.55s/it]

IEEE transactions on cybernetics has homepage_url and type journal

  0%|▏                                                                       | 3/1337 [00:03<23:53,  1.07s/it]

IEEE transactions on robotics has homepage_url and type journal

  0%|▏                                                                       | 4/1337 [00:03<19:08,  1.16it/s]

Neurocomputing has homepage_url and type journal

  0%|▎                                                                       | 5/1337 [00:04<21:37,  1.03it/s]

IEEE transactions on industrial electronics has homepage_url and type journal

  0%|▎                                                                       | 6/1337 [00:05<18:40,  1.19it/s]

IEEE transactions on control systems technology has homepage_url and type journal

  1%|▍                                                                       | 8/1337 [00:06<16:23,  1.35it/s]

IEEE transactions on industrial informatics has homepage_url and type journal

  1%|▍                                                                       | 9/1337 [00:07<14:43,  1.50it/s]

IEEE transactions on neural networks and learning systems has homepage_url and type journal

  1%|▌                                                                      | 11/1337 [00:08<16:15,  1.36it/s]

International journal of systems science has homepage_url and type journal

  1%|▋                                                                      | 12/1337 [00:09<17:18,  1.28it/s]

ISA transactions has homepage_url and type journal

  1%|▋                                                                      | 13/1337 [00:10<15:12,  1.45it/s]

Robotics and computer-integrated manufacturing has homepage_url and type journal

  1%|▋                                                                      | 14/1337 [00:12<22:36,  1.03s/it]

The international journal of robotics research has homepage_url and type journal

  1%|▊                                                                      | 15/1337 [00:12<19:19,  1.14it/s]

Annual reviews in control has homepage_url and type journal

  1%|▉                                                                      | 18/1337 [00:14<17:12,  1.28it/s]

International journal of agricultural and biological engineering has homepage_url and type journal

  1%|█                                                                      | 20/1337 [00:16<19:41,  1.11it/s]

International journal of intelligent systems has homepage_url and type journal

  2%|█                                                                      | 21/1337 [00:16<16:53,  1.30it/s]

Robotica has homepage_url and type journal

  2%|█▏                                                                     | 22/1337 [00:17<15:14,  1.44it/s]

Control engineering practice has homepage_url and type journal

  2%|█▎                                                                     | 25/1337 [00:19<13:26,  1.63it/s]

Mechanism and machine theory has homepage_url and type journal

  2%|█▍                                                                     | 26/1337 [00:19<12:41,  1.72it/s]

IEEE transactions on automation science and engineering has homepage_url and type journal

  2%|█▍                                                                     | 28/1337 [00:20<11:58,  1.82it/s]

IEEE transactions on automatic control has homepage_url and type journal

  2%|█▌                                                                     | 29/1337 [00:21<12:09,  1.79it/s]

IEEE access has homepage_url and type journal

  2%|█▌                                                                     | 30/1337 [00:22<14:26,  1.51it/s]

Robotics and autonomous systems has homepage_url and type journal

  2%|█▋                                                                     | 31/1337 [00:23<18:17,  1.19it/s]

Cybernetics and systems has homepage_url and type journal

  2%|█▋                                                                     | 32/1337 [00:24<19:19,  1.13it/s]

Procedia computer science has homepage_url and type journal

  2%|█▊                                                                     | 33/1337 [00:25<22:16,  1.02s/it]

Journal of computational science has homepage_url and type journal

  3%|█▊                                                                     | 34/1337 [00:26<19:23,  1.12it/s]

Asian journal of control has homepage_url and type journal

  3%|█▊                                                                     | 35/1337 [00:27<16:50,  1.29it/s]

Automatica has homepage_url and type journal

  3%|█▉                                                                     | 36/1337 [00:27<17:47,  1.22it/s]

Information sciences has homepage_url and type journal

  3%|██                                                                     | 38/1337 [00:29<19:47,  1.09it/s]

Proceedings of the IEEE has homepage_url and type journal

  3%|██                                                                     | 40/1337 [00:30<14:44,  1.47it/s]

Computer-aided civil and infrastructure engineering has homepage_url and type journal

  3%|██▏                                                                    | 42/1337 [00:32<16:28,  1.31it/s]

Engineering applications of artificial intelligence has homepage_url and type journal

  3%|██▎                                                                    | 43/1337 [00:32<14:40,  1.47it/s]

IEEE transactions on fuzzy systems has homepage_url and type journal

  3%|██▍                                                                    | 45/1337 [00:33<13:18,  1.62it/s]

IEEE journal of radio frequency identification has homepage_url and type journal

  3%|██▍                                                                    | 46/1337 [00:34<16:03,  1.34it/s]

Procedia engineering has homepage_url and type journal

  4%|██▍                                                                    | 47/1337 [00:36<19:46,  1.09it/s]

Applied sciences has homepage_url and type journal

  4%|██▌                                                                    | 48/1337 [00:36<17:24,  1.23it/s]

International journal of robust and nonlinear control has homepage_url and type journal

  4%|██▌                                                                    | 49/1337 [00:38<20:51,  1.03it/s]

Computers and electronics in agriculture has homepage_url and type journal

  4%|██▋                                                                    | 50/1337 [00:38<18:42,  1.15it/s]

Communications biology has homepage_url and type journal

  4%|██▋                                                                    | 51/1337 [00:39<16:15,  1.32it/s]

Journal of King Saud University. Engineering sciences/Maǧallaẗ ǧāmiʹaẗ al-malik Saʹūd. al-ʹUlūm al-handsiyyaẗ has homepage_url and type journal

  4%|██▊                                                                    | 52/1337 [00:39<14:26,  1.48it/s]

IEEE sensors journal has homepage_url and type journal

  4%|███                                                                    | 58/1337 [00:43<12:06,  1.76it/s]

Applied mathematical modelling has homepage_url and type journal

  4%|███▏                                                                   | 59/1337 [00:43<13:33,  1.57it/s]

Sensors has homepage_url and type journal

  4%|███▏                                                                   | 60/1337 [00:45<16:45,  1.27it/s]

Frontiers in neurorobotics has homepage_url and type journal

  5%|███▏                                                                   | 61/1337 [00:45<15:03,  1.41it/s]

Journal of field robotics has homepage_url and type journal

  5%|███▎                                                                   | 62/1337 [00:46<13:41,  1.55it/s]

Advances in intelligent systems and computing has homepage_url and type book series

  5%|███▎                                                                   | 63/1337 [00:46<13:06,  1.62it/s]

Materials today: proceedings has homepage_url and type journal

  5%|███▍                                                                   | 65/1337 [00:48<14:32,  1.46it/s]

Scientia iranica has homepage_url and type journal

  5%|███▌                                                                   | 66/1337 [00:48<13:15,  1.60it/s]

Applied soft computing has homepage_url and type journal

  5%|███▌                                                                   | 67/1337 [00:49<12:21,  1.71it/s]

Procedia CIRP has homepage_url and type journal

  5%|███▌                                                                   | 68/1337 [00:49<11:40,  1.81it/s]

Soft robotics has homepage_url and type journal

  5%|███▋                                                                   | 69/1337 [00:49<11:06,  1.90it/s]

IFAC-PapersOnLine has homepage_url and type journal

  5%|███▋                                                                   | 70/1337 [00:50<10:57,  1.93it/s]

International journal of advanced robotic systems has homepage_url and type journal

  5%|███▊                                                                   | 72/1337 [00:51<10:59,  1.92it/s]

Studies in informatics and control has homepage_url and type journal

  5%|███▉                                                                   | 73/1337 [00:52<10:46,  1.96it/s]

Neural computation has homepage_url and type journal

  6%|███▉                                                                   | 74/1337 [00:52<12:18,  1.71it/s]

Robotics has homepage_url and type journal

  6%|███▉                                                                   | 75/1337 [00:53<11:31,  1.83it/s]

Journal of the Franklin Institute has homepage_url and type journal

  6%|████                                                                   | 76/1337 [00:53<11:22,  1.85it/s]

IEEE/CAA journal of automatica sinica has homepage_url and type journal

  6%|████                                                                   | 77/1337 [00:54<10:55,  1.92it/s]

IEEE control systems letters has homepage_url and type journal

  6%|████▏                                                                  | 78/1337 [00:54<10:36,  1.98it/s]

Frontiers in robotics and AI has homepage_url and type journal

  6%|████▏                                                                  | 79/1337 [00:55<10:26,  2.01it/s]

IEEE transactions on medical robotics and bionics has homepage_url and type journal

  6%|████▎                                                                  | 81/1337 [00:56<10:23,  2.01it/s]

Automation in construction has homepage_url and type journal

  6%|████▎                                                                  | 82/1337 [00:56<12:22,  1.69it/s]

Mathematics has homepage_url and type journal

  6%|████▍                                                                  | 83/1337 [00:57<11:41,  1.79it/s]

AIP advances has homepage_url and type journal

  6%|████▍                                                                  | 84/1337 [00:57<11:12,  1.86it/s]

Journal of mechanisms and robotics has homepage_url and type journal

  6%|████▌                                                                  | 85/1337 [00:58<11:04,  1.88it/s]

Mechanical sciences has homepage_url and type journal

  7%|████▌                                                                  | 87/1337 [00:59<10:47,  1.93it/s]

Journal of robotics and mechatronics has homepage_url and type journal

  7%|████▋                                                                  | 88/1337 [00:59<10:37,  1.96it/s]

Research Square (Research Square) has homepage_url and type repository

  7%|████▋                                                                  | 89/1337 [01:00<10:33,  1.97it/s]

Journal of spacecraft and rockets has homepage_url and type journal

  7%|████▊                                                                  | 90/1337 [01:01<11:12,  1.85it/s]

Al-Khwarizmi engineering journal/Al-Khwarizmi engineering journal has homepage_url and type journal

  7%|████▊                                                                  | 91/1337 [01:01<11:21,  1.83it/s]

Lecture notes in electrical engineering has homepage_url and type book series

  7%|████▉                                                                  | 92/1337 [01:02<11:05,  1.87it/s]

Advances in space research has homepage_url and type journal

  7%|████▉                                                                  | 93/1337 [01:02<10:44,  1.93it/s]

Lecture notes in networks and systems has homepage_url and type book series

  7%|████▉                                                                  | 94/1337 [01:03<10:25,  1.99it/s]

Bio web of conferences/BIO web of conferences has homepage_url and type journal

  7%|█████                                                                  | 95/1337 [01:04<13:01,  1.59it/s]

Žurnal Srednevolžskogo matematičeskogo obŝestva has homepage_url and type journal

  7%|█████                                                                  | 96/1337 [01:05<16:08,  1.28it/s]

International journal of non-linear mechanics has homepage_url and type journal

  7%|█████▏                                                                 | 97/1337 [01:06<18:06,  1.14it/s]

Transactions of the Institute of Measurement and Control has homepage_url and type journal

  7%|█████▏                                                                 | 98/1337 [01:07<19:26,  1.06it/s]

Advanced robotics has homepage_url and type journal

  7%|█████▏                                                                | 100/1337 [01:08<15:50,  1.30it/s]

Neural networks has homepage_url and type journal

  8%|█████▎                                                                | 101/1337 [01:08<14:07,  1.46it/s]

IEEE transactions on control of network systems has homepage_url and type journal

  8%|█████▎                                                                | 102/1337 [01:09<12:56,  1.59it/s]

Transactions on internet and information systems has homepage_url and type journal

  8%|█████▍                                                                | 103/1337 [01:10<17:07,  1.20it/s]

Machines has homepage_url and type journal

  8%|█████▍                                                                | 104/1337 [01:11<14:53,  1.38it/s]

Cyborg and bionic systems has homepage_url and type journal

  8%|█████▍                                                                | 105/1337 [01:12<17:39,  1.16it/s]

Actuators has homepage_url and type journal

  8%|█████▋                                                                | 108/1337 [01:22<58:46,  2.87s/it]

Electronics has homepage_url and type journal

  8%|█████▋                                                                | 109/1337 [01:22<45:04,  2.20s/it]

Mathematical methods in the applied sciences has homepage_url and type journal

  8%|█████▊                                                                | 110/1337 [01:25<44:37,  2.18s/it]

Processes has homepage_url and type journal

  8%|█████▊                                                                | 111/1337 [01:27<45:58,  2.25s/it]

AIP conference proceedings has homepage_url and type journal

  8%|█████▊                                                                | 112/1337 [01:28<39:57,  1.96s/it]

Ocean engineering has homepage_url and type journal

  8%|█████▉                                                                | 113/1337 [01:29<31:00,  1.52s/it]

American journal of obstetrics and gynecology has homepage_url and type journal

  9%|██████                                                                | 115/1337 [01:30<24:07,  1.18s/it]

Symmetry has homepage_url and type journal

  9%|██████                                                                | 116/1337 [01:31<19:49,  1.03it/s]

Acta polytechnica Hungarica has homepage_url and type journal

  9%|██████▏                                                               | 117/1337 [01:31<17:08,  1.19it/s]

Chinese journal of aeronautics/Chinese Journal of Aeronautics has homepage_url and type journal

  9%|██████▏                                                               | 118/1337 [01:32<15:05,  1.35it/s]

Frontiers in energy research has homepage_url and type journal

  9%|██████▏                                                               | 119/1337 [01:32<14:09,  1.43it/s]

Engineering research express has homepage_url and type journal

  9%|██████▎                                                               | 120/1337 [01:33<12:48,  1.58it/s]

AIMS mathematics has homepage_url and type journal

  9%|██████▎                                                               | 121/1337 [01:33<12:13,  1.66it/s]

International journal of adaptive control and signal processing has homepage_url and type journal

  9%|██████▍                                                               | 123/1337 [01:35<14:04,  1.44it/s]

International journal of control has homepage_url and type journal

  9%|██████▍                                                               | 124/1337 [01:35<12:58,  1.56it/s]

AIMS electronics and electrical engineering has homepage_url and type journal

  9%|██████▌                                                               | 126/1337 [01:36<11:24,  1.77it/s]

International journal of electrical engineering education has homepage_url and type journal

  9%|██████▋                                                               | 127/1337 [01:37<11:57,  1.69it/s]

Interdisciplinary description of complex systems has homepage_url and type journal

 10%|██████▋                                                               | 128/1337 [01:38<11:31,  1.75it/s]

IOP conference series. Materials science and engineering has homepage_url and type conference

 10%|██████▊                                                               | 130/1337 [01:39<12:45,  1.58it/s]

Simulation has homepage_url and type journal

 10%|██████▊                                                               | 131/1337 [01:40<12:07,  1.66it/s]

International journal of humanoid robotics has homepage_url and type journal

 10%|██████▉                                                               | 133/1337 [01:41<13:29,  1.49it/s]

Revista IEEE América Latina has homepage_url and type journal

 10%|███████                                                               | 134/1337 [01:42<15:17,  1.31it/s]

International journal of dynamics and control has homepage_url and type journal

 10%|███████                                                               | 135/1337 [01:42<14:13,  1.41it/s]

Communications in computer and information science has homepage_url and type book series

 10%|███████▏                                                              | 137/1337 [01:43<12:08,  1.65it/s]

Expert systems with applications has homepage_url and type journal

 10%|███████▏                                                              | 138/1337 [01:44<11:39,  1.71it/s]

Drones has homepage_url and type journal

 10%|███████▎                                                              | 140/1337 [01:45<11:10,  1.78it/s]

Journal of Theoretical and Applied Mechanics/Mechanika Teoretyczna i Stosowana has homepage_url and type journal

 11%|███████▍                                                              | 141/1337 [01:46<10:50,  1.84it/s]

Mechanics based design of structures and machines has homepage_url and type journal

 11%|███████▍                                                              | 142/1337 [01:47<13:50,  1.44it/s]

Journal of vibration and control has homepage_url and type journal

 11%|███████▊                                                              | 150/1337 [01:51<09:40,  2.04it/s]

Intelligent systems reference library has homepage_url and type book series

 11%|████████                                                              | 153/1337 [01:53<16:46,  1.18it/s]

Rossijskij tehnologičeskij žurnal/Russian technological journal has homepage_url and type journal

 12%|████████                                                              | 154/1337 [01:54<14:41,  1.34it/s]

Zenodo (CERN European Organization for Nuclear Research) has homepage_url and type repository

 12%|████████                                                              | 155/1337 [01:54<13:21,  1.48it/s]

International Journal of Applied Mathematics and Computer Science has homepage_url and type journal

 12%|████████▏                                                             | 156/1337 [01:55<12:16,  1.60it/s]

International journal of intelligent systems and applications has homepage_url and type journal

 12%|████████▏                                                             | 157/1337 [01:55<11:38,  1.69it/s]

Mathematical problems in engineering has homepage_url and type journal

 12%|████████▎                                                             | 158/1337 [01:56<11:35,  1.70it/s]

The International journal of computational intelligence systems/International journal of computational intelligence systems has homepage_url and type journal

 12%|████████▎                                                             | 159/1337 [01:57<10:53,  1.80it/s]

Assembly automation has homepage_url and type journal

 12%|████████▍                                                             | 160/1337 [01:57<10:53,  1.80it/s]

Pattern recognition letters has homepage_url and type journal

 12%|████████▌                                                             | 163/1337 [02:00<18:20,  1.07it/s]

IEEE transactions on industry applications has homepage_url and type journal

 12%|████████▌                                                             | 164/1337 [02:00<15:48,  1.24it/s]

Mechanical systems and signal processing has homepage_url and type journal

 12%|████████▋                                                             | 165/1337 [02:01<13:53,  1.41it/s]

Lecture notes in computer science has homepage_url and type book series

 13%|█████████                                                             | 172/1337 [02:07<19:40,  1.01s/it]

Inventions has homepage_url and type journal

 13%|█████████                                                             | 173/1337 [02:08<22:22,  1.15s/it]

Measurement has homepage_url and type journal

 13%|█████████                                                             | 174/1337 [02:09<21:26,  1.11s/it]

Science robotics has homepage_url and type journal

 13%|█████████▏                                                            | 175/1337 [02:10<17:46,  1.09it/s]

Lecture notes in mechanical engineering has homepage_url and type book series

 13%|█████████▏                                                            | 176/1337 [02:10<15:33,  1.24it/s]

Journal of mobile information systems has homepage_url and type journal

 13%|█████████▎                                                            | 177/1337 [02:11<16:58,  1.14it/s]

International journal of engineering and manufacturing has homepage_url and type journal

 13%|█████████▎                                                            | 178/1337 [02:12<14:36,  1.32it/s]

Swarm and evolutionary computation has homepage_url and type journal

 13%|█████████▎                                                            | 179/1337 [02:12<13:19,  1.45it/s]

arXiv (Cornell University) has homepage_url and type repository

 13%|█████████▍                                                            | 180/1337 [02:13<12:11,  1.58it/s]

International journal of computer assisted radiology and surgery has homepage_url and type journal

 14%|█████████▍                                                            | 181/1337 [02:13<11:43,  1.64it/s]

Journal of the Brazilian Society of Mechanical Sciences and Engineering has homepage_url and type journal

 14%|█████████▌                                                            | 182/1337 [02:14<11:02,  1.74it/s]

International journal of advanced technology and engineering exploration has homepage_url and type journal

 14%|█████████▋                                                            | 184/1337 [02:15<12:53,  1.49it/s]

SpringerBriefs in applied sciences and technology has homepage_url and type book series

 14%|█████████▋                                                            | 185/1337 [02:16<12:02,  1.60it/s]

Recent patents on engineering has homepage_url and type journal

 14%|█████████▋                                                            | 186/1337 [02:17<13:39,  1.41it/s]

Courses and lectures has homepage_url and type book series

 14%|█████████▉                                                            | 189/1337 [02:19<16:14,  1.18it/s]

Complexity has homepage_url and type journal

 14%|██████████                                                            | 191/1337 [02:20<12:41,  1.50it/s]

MATEC web of conferences has homepage_url and type journal

 15%|██████████▏                                                           | 195/1337 [02:23<17:00,  1.12it/s]

Structures has homepage_url and type journal

 15%|██████████▎                                                           | 196/1337 [02:25<18:22,  1.03it/s]

International journal of online engineering has homepage_url and type journal

 15%|██████████▎                                                           | 197/1337 [02:26<19:40,  1.04s/it]

Zhōngguó gōngchéng xuékān has homepage_url and type journal

 15%|██████████▎                                                           | 198/1337 [02:27<23:09,  1.22s/it]

Algorithms has homepage_url and type journal

 15%|██████████▍                                                           | 199/1337 [02:28<19:19,  1.02s/it]

Universal journal of mechanical engineering has homepage_url and type journal

 15%|██████████▍                                                           | 200/1337 [02:28<16:28,  1.15it/s]

Sensors and materials has homepage_url and type journal

 15%|██████████▌                                                           | 201/1337 [02:29<17:10,  1.10it/s]

Advances in mechanical engineering/Advances in Mechanical Engineering has homepage_url and type journal

 15%|██████████▋                                                           | 203/1337 [02:31<16:44,  1.13it/s]

Lecture notes in control and information sciences has homepage_url and type book series

 15%|██████████▊                                                           | 207/1337 [02:33<11:24,  1.65it/s]

International journal of intelligent engineering and systems has homepage_url and type journal

 16%|██████████▉                                                           | 209/1337 [02:34<10:16,  1.83it/s]

Applied mechanics and materials has homepage_url and type journal

 16%|███████████                                                           | 211/1337 [02:35<09:38,  1.95it/s]

IEEE transactions on human-machine systems has homepage_url and type journal

 16%|███████████▏                                                          | 213/1337 [02:37<15:08,  1.24it/s]

Manufacturing Technology has homepage_url and type journal

 16%|███████████▎                                                          | 215/1337 [02:38<12:25,  1.51it/s]

Automatisierungstechnik has homepage_url and type journal

 16%|███████████▍                                                          | 218/1337 [02:40<10:04,  1.85it/s]

Springer tracts in advanced robotics has homepage_url and type book series

 16%|███████████▍                                                          | 219/1337 [02:40<09:57,  1.87it/s]

International journal of mechatronics and automation has homepage_url and type journal

 16%|███████████▌                                                          | 220/1337 [02:41<09:40,  1.92it/s]

International journal of digital signals and smart systems has homepage_url and type journal

 17%|███████████▌                                                          | 222/1337 [02:42<09:26,  1.97it/s]

DOAJ (DOAJ: Directory of Open Access Journals) has homepage_url and type repository

 17%|███████████▋                                                          | 223/1337 [02:43<10:48,  1.72it/s]

Journal of sensors has homepage_url and type journal

 17%|███████████▊                                                          | 225/1337 [02:44<09:56,  1.86it/s]

Journal of composites science has homepage_url and type journal

 17%|███████████▉                                                          | 228/1337 [02:45<09:20,  1.98it/s]

Mathematical biosciences and engineering has homepage_url and type journal

 17%|████████████                                                          | 231/1337 [02:47<12:42,  1.45it/s]

Advances in industrial control has homepage_url and type book series

 17%|████████████▏                                                         | 232/1337 [02:48<11:37,  1.59it/s]

Proceedings of the ... AAAI Conference on Artificial Intelligence has homepage_url and type conference

 18%|████████████▎                                                         | 235/1337 [02:49<09:41,  1.90it/s]

Elektronika ir elektrotechnika has homepage_url and type journal

 18%|████████████▌                                                         | 240/1337 [02:52<10:34,  1.73it/s]

HAL (Le Centre pour la Communication Scientifique Directe) has homepage_url and type repository

 18%|████████████▌                                                         | 241/1337 [02:53<13:47,  1.33it/s]

Mechanika has homepage_url and type journal

 18%|████████████▋                                                         | 243/1337 [02:55<15:30,  1.18it/s]

Indian journal of science and technology has homepage_url and type journal

 18%|████████████▊                                                         | 245/1337 [02:56<12:03,  1.51it/s]

International journal emerging technology and advanced engineering has homepage_url and type journal

 18%|████████████▉                                                         | 247/1337 [02:57<10:27,  1.74it/s]

Izvestiâ vysših učebnyh zavedenij. Mašinostroenie has homepage_url and type journal

 19%|█████████████                                                         | 249/1337 [02:59<13:51,  1.31it/s]

Frontiers in physics has homepage_url and type journal

 19%|█████████████▏                                                        | 253/1337 [03:02<14:32,  1.24it/s]

Rekayasa Mesin has homepage_url and type journal

 19%|█████████████▎                                                        | 254/1337 [03:02<12:52,  1.40it/s]

PAR. Pomiary Automatyka Robotyka/Pomiary Automatyka Robotyka has homepage_url and type journal

 19%|█████████████▎                                                        | 255/1337 [03:03<11:44,  1.53it/s]

Journal of marine science and engineering has homepage_url and type journal

 19%|█████████████▌                                                        | 258/1337 [03:04<10:07,  1.78it/s]

JIMEKA (Jurnal Ilmiah Mahasiswa Ekonomi Akuntansi) has homepage_url and type journal

 19%|█████████████▌                                                        | 260/1337 [03:06<13:40,  1.31it/s]

Journal of robotics has homepage_url and type journal

 20%|█████████████▊                                                        | 263/1337 [03:08<14:05,  1.27it/s]

Fractal and fractional has homepage_url and type journal

 20%|█████████████▊                                                        | 265/1337 [03:09<11:31,  1.55it/s]

SN Computer Science/SN computer science has homepage_url and type journal

 20%|█████████████▉                                                        | 266/1337 [03:10<10:35,  1.68it/s]

International review of automatic control has homepage_url and type journal

 20%|██████████████▏                                                       | 271/1337 [03:13<12:17,  1.44it/s]

Contemporary materials has homepage_url and type journal

 20%|██████████████▏                                                       | 272/1337 [03:14<13:45,  1.29it/s]

Journal of Robotics and Control/Journal of Robotics and Control (JRC) has homepage_url and type journal

 21%|██████████████▍                                                       | 275/1337 [03:16<10:21,  1.71it/s]

Studies in computational intelligence has homepage_url and type book series

 21%|██████████████▌                                                       | 278/1337 [03:17<08:49,  2.00it/s]

KnE engineering has homepage_url and type journal

 21%|██████████████▋                                                       | 280/1337 [03:19<12:09,  1.45it/s]

ITM web of conferences has homepage_url and type journal

 21%|██████████████▋                                                       | 281/1337 [03:19<11:28,  1.53it/s]

International journal of integrated engineering/International Journal of Integrated Engineering has homepage_url and type journal

 21%|██████████████▊                                                       | 284/1337 [03:22<14:14,  1.23it/s]

Europan journal of science and technology has homepage_url and type journal

 22%|███████████████                                                       | 288/1337 [03:24<12:27,  1.40it/s]

Nihon Robotto Gakkaishi has homepage_url and type journal

 22%|███████████████▏                                                      | 289/1337 [03:25<11:08,  1.57it/s]

Izvestiâ vysših učebnyh zavedenij. Prikladnaâ nelinejnaâ dinamika has homepage_url and type journal

 22%|███████████████▎                                                      | 292/1337 [03:26<09:52,  1.76it/s]

International journal for research in applied science and engineering technology has homepage_url and type journal

 22%|███████████████▎                                                      | 293/1337 [03:27<10:00,  1.74it/s]

Journal of physics. Conference series has homepage_url and type journal

 22%|███████████████▌                                                      | 298/1337 [03:30<10:22,  1.67it/s]

Micromachines has homepage_url and type journal

 23%|███████████████▊                                                      | 301/1337 [03:32<09:05,  1.90it/s]

Èlektronnye biblioteki has homepage_url and type journal

 23%|███████████████▊                                                      | 302/1337 [03:33<11:37,  1.48it/s]

Journal of intelligent manufacturing has homepage_url and type journal

 23%|███████████████▉                                                      | 304/1337 [03:34<12:48,  1.34it/s]

Gastrointestinal endoscopy has homepage_url and type journal

 23%|███████████████▉                                                      | 305/1337 [03:36<15:51,  1.08it/s]

Journal of healthcare engineering has homepage_url and type journal

 23%|████████████████                                                      | 306/1337 [03:36<13:43,  1.25it/s]

Advances in Sciences and Technology/Postępy Nauki i Techniki has homepage_url and type journal

 23%|████████████████▍                                                     | 313/1337 [03:40<08:59,  1.90it/s]

Journal of minimally invasive gynecology has homepage_url and type journal

 23%|████████████████▍                                                     | 314/1337 [03:40<08:41,  1.96it/s]

DergiPark (Istanbul University) has homepage_url and type repository

 24%|████████████████▍                                                     | 315/1337 [03:41<08:56,  1.91it/s]

Fusion engineering and design has homepage_url and type journal

 24%|████████████████▌                                                     | 316/1337 [03:42<11:14,  1.51it/s]

International journal of new technology and research has homepage_url and type journal

 24%|████████████████▋                                                     | 319/1337 [03:43<09:18,  1.82it/s]

Mathematical models in engineering has homepage_url and type journal

 24%|████████████████▊                                                     | 321/1337 [03:44<08:52,  1.91it/s]

International journal of ambient energy has homepage_url and type journal

 24%|████████████████▊                                                     | 322/1337 [03:45<08:46,  1.93it/s]

Fen-mühendislik dergisi/Dokuz Eylül Üniversitesi Mühendislik Fakültesi fen ve mühendislik dergisi has homepage_url and type journal

 25%|█████████████████▏                                                    | 328/1337 [03:47<08:05,  2.08it/s]

Jixie gongcheng xuebao has homepage_url and type journal

 25%|█████████████████▏                                                    | 329/1337 [03:49<11:40,  1.44it/s]

Journal of Engineering Science and Technology Review has homepage_url and type journal

 25%|█████████████████▎                                                    | 330/1337 [03:49<10:49,  1.55it/s]

JGH open has homepage_url and type journal

 25%|█████████████████▍                                                    | 332/1337 [03:51<11:50,  1.41it/s]

International journal of engineering and advanced technology has homepage_url and type journal

 25%|█████████████████▍                                                    | 333/1337 [03:51<10:38,  1.57it/s]

Linköping electronic conference proceedings has homepage_url and type conference

 25%|█████████████████▋                                                    | 339/1337 [03:55<11:40,  1.43it/s]

South African journal of industrial engineering has homepage_url and type journal

 26%|██████████████████                                                    | 344/1337 [03:58<10:13,  1.62it/s]

Journal of mechanics engineering and automation has homepage_url and type journal

 26%|██████████████████                                                    | 345/1337 [03:58<09:33,  1.73it/s]

Journal of Asian scientific research has homepage_url and type journal

 26%|██████████████████                                                    | 346/1337 [03:59<09:19,  1.77it/s]

Archives of physical medicine and rehabilitation has homepage_url and type journal

 26%|██████████████████▏                                                   | 347/1337 [04:00<12:05,  1.36it/s]

International journal of control and automation has homepage_url and type journal

 26%|██████████████████▎                                                   | 349/1337 [04:02<13:55,  1.18it/s]

Impact has homepage_url and type journal

 26%|██████████████████▍                                                   | 351/1337 [04:04<14:08,  1.16it/s]

Scientific reports has homepage_url and type journal

 27%|██████████████████▊                                                   | 359/1337 [04:08<08:33,  1.90it/s]

Social Science Research Network has homepage_url and type repository

 27%|██████████████████▊                                                   | 360/1337 [04:09<08:29,  1.92it/s]

Diagnostyka has homepage_url and type journal

 27%|██████████████████▉                                                   | 362/1337 [04:10<08:34,  1.90it/s]

Springer proceedings in physics has homepage_url and type book series

 27%|███████████████████▏                                                  | 366/1337 [04:12<08:31,  1.90it/s]

Journal of pharmaceutical negative results has homepage_url and type journal

 28%|███████████████████▎                                                  | 368/1337 [04:13<11:14,  1.44it/s]

Global Journal of Engineering and Technology Advances has homepage_url and type journal

 29%|████████████████████                                                  | 382/1337 [04:22<09:28,  1.68it/s]

Annals of Computer Science and Information Systems has homepage_url and type conference

 29%|████████████████████                                                  | 384/1337 [04:23<08:36,  1.85it/s]

Majallah-i kuntrul has homepage_url and type journal

 29%|████████████████████▎                                                 | 388/1337 [04:26<10:58,  1.44it/s]

GeoPlanet: earth and planetary sciences has homepage_url and type book series

 29%|████████████████████▌                                                 | 393/1337 [04:28<08:17,  1.90it/s]

Zeszyty Naukowe Politechniki Rzeszowskiej. Mechanika has homepage_url and type journal

 30%|████████████████████▋                                                 | 395/1337 [04:30<11:25,  1.37it/s]

Journal of mechatronics and robotics has homepage_url and type journal

 30%|████████████████████▋                                                 | 396/1337 [04:30<10:32,  1.49it/s]

Journal of Mechatronics Engineering has homepage_url and type journal

 30%|████████████████████▊                                                 | 397/1337 [04:31<11:41,  1.34it/s]

International journal of intelligent machines and robotics has homepage_url and type journal

 30%|████████████████████▊                                                 | 398/1337 [04:33<16:18,  1.04s/it]

Sun International journal of engineering and basic sciences has homepage_url and type journal

 30%|████████████████████▉                                                 | 401/1337 [04:41<26:03,  1.67s/it]

Helix has homepage_url and type journal

 30%|█████████████████████▏                                                | 404/1337 [04:42<14:01,  1.11it/s]

Journal on Advances in Theoretical and Applied Informatics has homepage_url and type journal

 30%|█████████████████████▎                                                | 406/1337 [04:44<14:19,  1.08it/s]

IOP conference series. Earth and environmental science has homepage_url and type conference

 31%|█████████████████████▍                                                | 410/1337 [04:46<12:07,  1.28it/s]

Doklady Akademii nauk. Rossijskaâ akademiâ nauk has homepage_url and type journal

 31%|█████████████████████▌                                                | 411/1337 [04:47<11:51,  1.30it/s]

International journal of research in engineering and technology has homepage_url and type journal

 31%|█████████████████████▌                                                | 412/1337 [04:48<10:34,  1.46it/s]

Advances in applied Clifford algebras has homepage_url and type journal

 31%|█████████████████████▌                                                | 413/1337 [04:48<10:10,  1.51it/s]

International Journal of Industrial Research and Applied Engineering has homepage_url and type journal

 31%|█████████████████████▋                                                | 414/1337 [04:49<09:27,  1.63it/s]

International journal of scientific research in science and technology has homepage_url and type journal

 32%|██████████████████████▏                                               | 424/1337 [04:54<07:22,  2.06it/s]

Lecture notes on data engineering and communications technologies has homepage_url and type book series

 32%|██████████████████████▌                                               | 430/1337 [04:57<10:42,  1.41it/s]

Advanced functional materials has homepage_url and type journal

 32%|██████████████████████▌                                               | 431/1337 [04:58<10:54,  1.38it/s]

Advanced materials has homepage_url and type journal

 32%|██████████████████████▌                                               | 432/1337 [04:59<10:07,  1.49it/s]

Energy storage materials has homepage_url and type journal

 32%|██████████████████████▋                                               | 433/1337 [04:59<10:36,  1.42it/s]

Chemical engineering journal has homepage_url and type journal

 33%|██████████████████████▊                                               | 435/1337 [05:01<11:12,  1.34it/s]

High voltage has homepage_url and type journal

 33%|██████████████████████▊                                               | 436/1337 [05:01<10:11,  1.47it/s]

Nano energy has homepage_url and type journal

 33%|██████████████████████▉                                               | 437/1337 [05:02<09:15,  1.62it/s]

Journal of advanced ceramics has homepage_url and type journal

 33%|██████████████████████▉                                               | 438/1337 [05:02<08:40,  1.73it/s]

Physics of plasmas has homepage_url and type journal

 33%|██████████████████████▉                                               | 439/1337 [05:04<12:15,  1.22it/s]

Advanced science has homepage_url and type journal

 33%|███████████████████████                                               | 440/1337 [05:04<11:00,  1.36it/s]

Journal of the European Ceramic Society has homepage_url and type journal

 33%|███████████████████████                                               | 441/1337 [05:05<13:22,  1.12it/s]

Ceramics international has homepage_url and type journal

 33%|███████████████████████▏                                              | 442/1337 [05:07<14:03,  1.06it/s]

Applied energy has homepage_url and type journal

 33%|███████████████████████▏                                              | 444/1337 [05:07<10:21,  1.44it/s]

Journal of materiomics has homepage_url and type journal

 33%|███████████████████████▎                                              | 445/1337 [05:08<09:26,  1.58it/s]

High power laser science and engineering has homepage_url and type journal

 33%|███████████████████████▎                                              | 446/1337 [05:09<12:36,  1.18it/s]

Small has homepage_url and type journal

 33%|███████████████████████▍                                              | 447/1337 [05:10<11:23,  1.30it/s]

Journal of alloys and compounds has homepage_url and type journal

 34%|███████████████████████▍                                              | 448/1337 [05:10<10:06,  1.46it/s]

Journal of the American Ceramic Society has homepage_url and type journal

 34%|███████████████████████▌                                              | 449/1337 [05:12<12:24,  1.19it/s]

Chemistry of materials has homepage_url and type journal

 34%|███████████████████████▌                                              | 450/1337 [05:12<10:54,  1.36it/s]

Journal of power sources has homepage_url and type journal

 34%|███████████████████████▌                                              | 451/1337 [05:13<09:45,  1.51it/s]

Applied physics letters has homepage_url and type journal

 34%|███████████████████████▋                                              | 452/1337 [05:13<08:58,  1.64it/s]

IEEE transactions on power electronics has homepage_url and type journal

 34%|███████████████████████▋                                              | 453/1337 [05:14<08:30,  1.73it/s]

Reviews of modern physics has homepage_url and type journal

 34%|███████████████████████▊                                              | 454/1337 [05:14<08:21,  1.76it/s]

Han-guk seramik hakoeji/Han'gug se'la'mig haghoeji has homepage_url and type journal

 34%|███████████████████████▊                                              | 455/1337 [05:15<07:56,  1.85it/s]

Review of scientific instruments online/Review of scientific instruments has homepage_url and type journal

 34%|███████████████████████▊                                              | 456/1337 [05:16<10:44,  1.37it/s]

Journal of materials chemistry. C has homepage_url and type journal

 34%|███████████████████████▉                                              | 457/1337 [05:17<11:42,  1.25it/s]

Energies has homepage_url and type journal

 34%|███████████████████████▉                                              | 458/1337 [05:17<10:16,  1.43it/s]

Cell reports physical science has homepage_url and type journal

 34%|████████████████████████                                              | 459/1337 [05:18<09:13,  1.59it/s]

Materials today energy has homepage_url and type journal

 34%|████████████████████████                                              | 460/1337 [05:18<08:40,  1.68it/s]

Journal of energy storage has homepage_url and type journal

 34%|████████████████████████▏                                             | 461/1337 [05:19<08:13,  1.77it/s]

International journal of impact engineering has homepage_url and type journal

 35%|████████████████████████▏                                             | 462/1337 [05:19<08:12,  1.78it/s]

IEEE transactions on plasma science has homepage_url and type journal

 35%|████████████████████████▏                                             | 463/1337 [05:20<07:48,  1.87it/s]

IEEE transactions on dielectrics and electrical insulation has homepage_url and type journal

 35%|████████████████████████▎                                             | 464/1337 [05:20<07:34,  1.92it/s]

Journal of Energy Chemistry/Journal of energy chemistry has homepage_url and type journal

 35%|████████████████████████▎                                             | 465/1337 [05:21<07:25,  1.96it/s]

ACS energy letters has homepage_url and type journal

 35%|████████████████████████▍                                             | 466/1337 [05:22<11:27,  1.27it/s]

Materials has homepage_url and type journal

 35%|████████████████████████▍                                             | 467/1337 [05:23<10:11,  1.42it/s]

Materials today physics has homepage_url and type journal

 35%|████████████████████████▌                                             | 468/1337 [05:24<12:29,  1.16it/s]

Solid state sciences has homepage_url and type journal

 35%|████████████████████████▌                                             | 469/1337 [05:25<14:30,  1.00s/it]

Journal of materials processing technology has homepage_url and type journal

 35%|████████████████████████▌                                             | 470/1337 [05:27<17:00,  1.18s/it]

Journal of manufacturing processes has homepage_url and type journal

 35%|████████████████████████▋                                             | 471/1337 [05:27<14:02,  1.03it/s]

IEEE electron device letters has homepage_url and type journal

 35%|████████████████████████▊                                             | 473/1337 [05:28<10:24,  1.38it/s]

Microstructures has homepage_url and type journal

 36%|████████████████████████▊                                             | 475/1337 [05:29<08:53,  1.61it/s]

ACS applied energy materials has homepage_url and type journal

 36%|████████████████████████▉                                             | 476/1337 [05:31<13:06,  1.10it/s]

Plasma has homepage_url and type journal

 36%|████████████████████████▉                                             | 477/1337 [05:32<12:28,  1.15it/s]

Journal of applied physics has homepage_url and type journal

 36%|█████████████████████████                                             | 479/1337 [05:33<12:18,  1.16it/s]

APL photonics has homepage_url and type journal

 36%|█████████████████████████▏                                            | 480/1337 [05:34<10:43,  1.33it/s]

Physical review. Accelerators and beams has homepage_url and type journal

 36%|█████████████████████████▏                                            | 482/1337 [05:35<08:49,  1.61it/s]

IEEE transactions on device and materials reliability has homepage_url and type journal

 36%|█████████████████████████▎                                            | 483/1337 [05:36<11:33,  1.23it/s]

Acta materialia has homepage_url and type journal

 36%|█████████████████████████▎                                            | 484/1337 [05:36<10:06,  1.41it/s]

Journal of CO2 utilization has homepage_url and type journal

 36%|█████████████████████████▍                                            | 485/1337 [05:37<09:03,  1.57it/s]

IETE Technical Review/IETE technical review has homepage_url and type journal

 36%|█████████████████████████▍                                            | 486/1337 [05:38<10:11,  1.39it/s]

International journal of rock mechanics and mining sciences has homepage_url and type journal

 36%|█████████████████████████▍                                            | 487/1337 [05:38<09:17,  1.53it/s]

Acta astronautica has homepage_url and type journal

 37%|█████████████████████████▌                                            | 489/1337 [05:39<08:07,  1.74it/s]

IEEE transactions on energy conversion has homepage_url and type journal

 37%|█████████████████████████▋                                            | 490/1337 [05:41<11:06,  1.27it/s]

Electronics letters has homepage_url and type journal

 37%|█████████████████████████▋                                            | 491/1337 [05:41<09:56,  1.42it/s]

Matter and radiation at extremes has homepage_url and type journal

 37%|█████████████████████████▊                                            | 492/1337 [05:42<10:50,  1.30it/s]

IEEE transactions on biomedical circuits and systems has homepage_url and type journal

 37%|█████████████████████████▊                                            | 493/1337 [05:42<09:40,  1.45it/s]

IEEE transactions on applied superconductivity has homepage_url and type journal

 37%|█████████████████████████▊                                            | 494/1337 [05:44<11:58,  1.17it/s]

Advanced energy materials has homepage_url and type journal

 37%|█████████████████████████▉                                            | 495/1337 [05:44<10:48,  1.30it/s]

Plasma processes and polymers has homepage_url and type journal

 37%|█████████████████████████▉                                            | 496/1337 [05:45<09:33,  1.47it/s]

Journal of physics and chemistry of solids has homepage_url and type journal

 37%|██████████████████████████                                            | 497/1337 [05:45<08:44,  1.60it/s]

Reviews of modern plasma physics has homepage_url and type journal

 37%|██████████████████████████                                            | 498/1337 [05:46<08:15,  1.69it/s]

IEEE photonics technology letters has homepage_url and type journal

 37%|██████████████████████████▏                                           | 499/1337 [05:47<09:02,  1.55it/s]

Energy has homepage_url and type repository

 37%|██████████████████████████▏                                           | 500/1337 [05:47<08:21,  1.67it/s]

PloS one has homepage_url and type journal

 38%|██████████████████████████▎                                           | 502/1337 [05:49<11:01,  1.26it/s]

International journal of energy research has homepage_url and type journal

 38%|██████████████████████████▍                                           | 504/1337 [05:50<09:00,  1.54it/s]

IEEE transactions on power systems has homepage_url and type journal

 38%|██████████████████████████▍                                           | 505/1337 [05:50<08:16,  1.67it/s]

IEEJ transactions on electrical and electronic engineering has homepage_url and type journal

 38%|██████████████████████████▍                                           | 506/1337 [05:51<07:48,  1.78it/s]

ACS applied electronic materials has homepage_url and type journal

 38%|██████████████████████████▌                                           | 507/1337 [05:52<09:14,  1.50it/s]

I.E.E.E. transactions on electron devices/IEEE transactions on electron devices has homepage_url and type journal

 38%|██████████████████████████▌                                           | 508/1337 [05:53<11:08,  1.24it/s]

Energy reports has homepage_url and type journal

 38%|██████████████████████████▋                                           | 509/1337 [05:53<09:50,  1.40it/s]

Applications in energy and combustion science has homepage_url and type journal

 38%|██████████████████████████▋                                           | 510/1337 [05:54<08:51,  1.56it/s]

Fusion science and technology has homepage_url and type journal

 38%|██████████████████████████▊                                           | 511/1337 [05:55<11:52,  1.16it/s]

Metals has homepage_url and type journal

 38%|██████████████████████████▊                                           | 512/1337 [05:56<10:22,  1.33it/s]

Journal of large-scale research facilities has homepage_url and type journal

 38%|██████████████████████████▊                                           | 513/1337 [05:56<09:12,  1.49it/s]

Proceedings of the Combustion Institute has homepage_url and type journal

 38%|██████████████████████████▉                                           | 514/1337 [05:57<08:23,  1.64it/s]

IEEE electrification magazine has homepage_url and type journal

 39%|███████████████████████████                                           | 517/1337 [05:58<08:23,  1.63it/s]

Buildings has homepage_url and type journal

 39%|███████████████████████████▎                                          | 521/1337 [06:01<09:53,  1.38it/s]

IEEE journal of the Electron Devices Society has homepage_url and type journal

 39%|███████████████████████████▎                                          | 522/1337 [06:01<08:55,  1.52it/s]

IEEE journal of emerging and selected topics in power electronics has homepage_url and type journal

 39%|███████████████████████████▍                                          | 523/1337 [06:02<09:03,  1.50it/s]

Quantum electronics has homepage_url and type journal

 39%|███████████████████████████▍                                          | 524/1337 [06:03<11:32,  1.17it/s]

Vacuum has homepage_url and type journal

 39%|███████████████████████████▍                                          | 525/1337 [06:04<10:24,  1.30it/s]

The Journal of adhesion/Journal of adhesion has homepage_url and type journal

 39%|███████████████████████████▌                                          | 526/1337 [06:05<09:17,  1.46it/s]

Physica scripta has homepage_url and type journal

 39%|███████████████████████████▌                                          | 527/1337 [06:05<08:34,  1.57it/s]

Combustion and flame has homepage_url and type journal

 40%|███████████████████████████▋                                          | 529/1337 [06:06<07:32,  1.78it/s]

AEÜ. International journal of electronics and communications has homepage_url and type journal

 40%|███████████████████████████▊                                          | 531/1337 [06:07<06:58,  1.93it/s]

ACS omega has homepage_url and type journal

 40%|███████████████████████████▊                                          | 532/1337 [06:08<06:55,  1.94it/s]

Circuit world has homepage_url and type journal

 40%|████████████████████████████                                          | 535/1337 [06:09<07:56,  1.68it/s]

Waste has homepage_url and type journal

 40%|████████████████████████████                                          | 536/1337 [06:10<09:09,  1.46it/s]

Journal of manufacturing and materials processing has homepage_url and type journal

 40%|████████████████████████████                                          | 537/1337 [06:11<11:23,  1.17it/s]

Journal of hazardous materials has homepage_url and type journal

 40%|████████████████████████████▏                                         | 538/1337 [06:13<13:18,  1.00it/s]

Environmental research has homepage_url and type journal

 40%|████████████████████████████▏                                         | 539/1337 [06:14<13:59,  1.05s/it]

Electrochimica acta has homepage_url and type journal

 40%|████████████████████████████▎                                         | 540/1337 [06:14<11:55,  1.11it/s]

Quantum beam science has homepage_url and type journal

 40%|████████████████████████████▎                                         | 541/1337 [06:15<10:33,  1.26it/s]

Optics express has homepage_url and type journal

 41%|████████████████████████████▍                                         | 542/1337 [06:16<09:18,  1.42it/s]

Laser and particle beams has homepage_url and type journal

 41%|████████████████████████████▍                                         | 544/1337 [06:17<10:22,  1.27it/s]

Journal of non-crystalline solids has homepage_url and type journal

 41%|████████████████████████████▌                                         | 545/1337 [06:18<09:10,  1.44it/s]

IEEE transactions on microwave theory and techniques has homepage_url and type journal

 41%|████████████████████████████▌                                         | 546/1337 [06:18<08:25,  1.57it/s]

IEEE antennas and wireless propagation letters/Antennas and wireless propagation letters has homepage_url and type journal

 41%|████████████████████████████▋                                         | 547/1337 [06:19<07:45,  1.70it/s]

IEEE transactions on instrumentation and measurement has homepage_url and type journal

 41%|████████████████████████████▋                                         | 548/1337 [06:19<07:47,  1.69it/s]

CIRP journal of manufacturing science and technology has homepage_url and type journal

 41%|████████████████████████████▋                                         | 549/1337 [06:20<07:26,  1.77it/s]

Plasma physics and controlled fusion has homepage_url and type journal

 41%|████████████████████████████▊                                         | 550/1337 [06:20<07:13,  1.82it/s]

International journal of hydrogen energy has homepage_url and type journal

 41%|████████████████████████████▊                                         | 551/1337 [06:21<06:56,  1.89it/s]

Journal of laser applications has homepage_url and type journal

 41%|████████████████████████████▉                                         | 552/1337 [06:21<07:09,  1.83it/s]

IEEE transactions on electromagnetic compatibility has homepage_url and type journal

 41%|████████████████████████████▉                                         | 553/1337 [06:22<06:50,  1.91it/s]

Molecules/Molecules online/Molecules annual has homepage_url and type journal

 42%|█████████████████████████████                                         | 555/1337 [06:23<06:30,  2.00it/s]

Journal of electrostatics has homepage_url and type journal

 42%|█████████████████████████████                                         | 556/1337 [06:24<09:40,  1.35it/s]

Physical review. E has homepage_url and type journal

 42%|█████████████████████████████▏                                        | 557/1337 [06:25<08:52,  1.46it/s]

Laser physics letters has homepage_url and type journal

 42%|█████████████████████████████▏                                        | 558/1337 [06:25<08:11,  1.59it/s]

Radiation physics and chemistry has homepage_url and type journal

 42%|█████████████████████████████▎                                        | 559/1337 [06:26<08:34,  1.51it/s]

Nanomaterials has homepage_url and type journal

 42%|█████████████████████████████▎                                        | 560/1337 [06:26<07:57,  1.63it/s]

Chinese Physics B/Chinese physics B has homepage_url and type journal

 42%|█████████████████████████████▍                                        | 562/1337 [06:28<09:35,  1.35it/s]

Microelectronics reliability/Microelectronics and reliability has homepage_url and type journal

 42%|█████████████████████████████▍                                        | 563/1337 [06:28<08:40,  1.49it/s]

Journal of fluid science and technology has homepage_url and type journal

 42%|█████████████████████████████▌                                        | 564/1337 [06:30<10:49,  1.19it/s]

CES transactions on electrical machines and systems has homepage_url and type journal

 42%|█████████████████████████████▌                                        | 565/1337 [06:30<09:36,  1.34it/s]

Optics communications has homepage_url and type journal

 42%|█████████████████████████████▋                                        | 566/1337 [06:31<08:44,  1.47it/s]

Defence technology has homepage_url and type journal

 42%|█████████████████████████████▋                                        | 567/1337 [06:32<10:47,  1.19it/s]

Coatings has homepage_url and type journal

 42%|█████████████████████████████▋                                        | 568/1337 [06:33<12:41,  1.01it/s]

Minerals has homepage_url and type journal

 43%|█████████████████████████████▊                                        | 569/1337 [06:34<13:11,  1.03s/it]

Advanced engineering materials has homepage_url and type journal

 43%|█████████████████████████████▉                                        | 571/1337 [06:36<11:45,  1.09it/s]

Journal of magnetic resonance has homepage_url and type journal

 43%|██████████████████████████████                                        | 573/1337 [06:37<09:54,  1.28it/s]

Photonics has homepage_url and type journal

 43%|██████████████████████████████                                        | 575/1337 [06:38<07:48,  1.63it/s]

EPJ web of conferences has homepage_url and type journal

 43%|██████████████████████████████▏                                       | 576/1337 [06:39<07:14,  1.75it/s]

Optical and quantum electronics has homepage_url and type journal

 43%|██████████████████████████████▎                                       | 578/1337 [06:40<09:37,  1.31it/s]

Batteries has homepage_url and type journal

 43%|██████████████████████████████▎                                       | 579/1337 [06:41<08:45,  1.44it/s]

Nuclear Science and Techniques/Nuclear science and techniques has homepage_url and type journal

 43%|██████████████████████████████▎                                       | 580/1337 [06:42<09:38,  1.31it/s]

Journal of welding and joining has homepage_url and type journal

 43%|██████████████████████████████▍                                       | 581/1337 [06:42<08:37,  1.46it/s]

International journal of microwave and wireless technologies has homepage_url and type journal

 44%|██████████████████████████████▌                                       | 583/1337 [06:43<07:22,  1.70it/s]

International journal of circuit theory and applications has homepage_url and type journal

 44%|██████████████████████████████▌                                       | 584/1337 [06:44<06:54,  1.82it/s]

Thin solid films has homepage_url and type journal

 44%|██████████████████████████████▋                                       | 585/1337 [06:45<08:39,  1.45it/s]

Japanese journal of applied physics has homepage_url and type journal

 44%|██████████████████████████████▋                                       | 587/1337 [06:47<10:09,  1.23it/s]

IEEE photonics journal has homepage_url and type journal

 44%|██████████████████████████████▊                                       | 589/1337 [06:48<07:58,  1.56it/s]

Physical review applied has homepage_url and type journal

 44%|██████████████████████████████▉                                       | 590/1337 [06:48<07:35,  1.64it/s]

International journal of molecular sciences has homepage_url and type journal

 44%|██████████████████████████████▉                                       | 591/1337 [06:49<07:13,  1.72it/s]

Materials research express has homepage_url and type journal

 44%|██████████████████████████████▉                                       | 592/1337 [06:49<06:51,  1.81it/s]

Solid state nuclear magnetic resonance has homepage_url and type journal

 44%|███████████████████████████████                                       | 594/1337 [06:50<06:40,  1.86it/s]

IEEE transactions on transportation electrification has homepage_url and type journal

 45%|███████████████████████████████▏                                      | 595/1337 [06:51<06:39,  1.86it/s]

CIRP annals has homepage_url and type journal

 45%|███████████████████████████████▏                                      | 596/1337 [06:51<06:41,  1.84it/s]

Europhysics letters has homepage_url and type journal

 45%|███████████████████████████████▎                                      | 597/1337 [06:52<07:40,  1.61it/s]

Journal of instrumentation has homepage_url and type journal

 45%|███████████████████████████████▎                                      | 598/1337 [06:53<09:37,  1.28it/s]

Crystals has homepage_url and type journal

 45%|███████████████████████████████▎                                      | 599/1337 [06:54<08:44,  1.41it/s]

Chinese Optics Letters has homepage_url and type journal

 45%|███████████████████████████████▍                                      | 600/1337 [06:55<10:02,  1.22it/s]

Nuclear engineering and technology has homepage_url and type journal

 45%|███████████████████████████████▌                                      | 602/1337 [06:56<08:09,  1.50it/s]

Instruments and experimental techniques has homepage_url and type journal

 45%|███████████████████████████████▌                                      | 603/1337 [06:56<07:27,  1.64it/s]

Problemy osobo opasnyh infekcij has homepage_url and type journal

 45%|███████████████████████████████▋                                      | 605/1337 [06:58<09:53,  1.23it/s]

Sustainability has homepage_url and type journal

 45%|███████████████████████████████▋                                      | 606/1337 [06:59<08:38,  1.41it/s]

Bioelectrochemistry has homepage_url and type journal

 45%|███████████████████████████████▊                                      | 607/1337 [06:59<07:51,  1.55it/s]

IEEE electrical insulation magazine has homepage_url and type journal

 46%|███████████████████████████████▉                                      | 609/1337 [07:00<07:04,  1.72it/s]

Physics letters. A has homepage_url and type journal

 46%|███████████████████████████████▉                                      | 610/1337 [07:01<06:41,  1.81it/s]

Optics letters/Optics index has homepage_url and type journal

 46%|████████████████████████████████                                      | 612/1337 [07:02<08:33,  1.41it/s]

Journal of advanced manufacturing systems has homepage_url and type journal

 46%|████████████████████████████████                                      | 613/1337 [07:03<07:47,  1.55it/s]

Plasma and fusion research has homepage_url and type journal

 46%|████████████████████████████████▏                                     | 614/1337 [07:04<08:50,  1.36it/s]

High temperature material processes has homepage_url and type journal

 46%|████████████████████████████████▏                                     | 615/1337 [07:05<11:02,  1.09it/s]

Nanotechnology has homepage_url and type journal

 46%|████████████████████████████████▎                                     | 616/1337 [07:06<09:45,  1.23it/s]

IEEE open journal of power electronics has homepage_url and type journal

 46%|████████████████████████████████▍                                     | 620/1337 [07:08<06:30,  1.83it/s]

Microwave and optical technology letters has homepage_url and type journal

 46%|████████████████████████████████▌                                     | 621/1337 [07:08<06:18,  1.89it/s]

Materials science forum has homepage_url and type book series

 47%|████████████████████████████████▌                                     | 622/1337 [07:09<08:28,  1.41it/s]

Journal of Semiconductors/Journal of semiconductors has homepage_url and type journal

 47%|████████████████████████████████▌                                     | 623/1337 [07:11<10:37,  1.12it/s]

Waste management has homepage_url and type journal

 47%|████████████████████████████████▋                                     | 625/1337 [07:12<11:02,  1.07it/s]

IET power electronics has homepage_url and type journal

 47%|████████████████████████████████▊                                     | 626/1337 [07:13<09:27,  1.25it/s]

Electrical engineering in Japan has homepage_url and type journal

 47%|████████████████████████████████▊                                     | 627/1337 [07:14<11:02,  1.07it/s]

Nauka i tehnika has homepage_url and type journal

 47%|████████████████████████████████▉                                     | 628/1337 [07:15<09:39,  1.22it/s]

Food engineering series has homepage_url and type book series

 47%|████████████████████████████████▉                                     | 629/1337 [07:16<11:25,  1.03it/s]

Analytical chemistry has homepage_url and type journal

 47%|█████████████████████████████████                                     | 631/1337 [07:23<25:50,  2.20s/it]

Applied thermal engineering has homepage_url and type journal

 47%|█████████████████████████████████▏                                    | 634/1337 [07:24<13:57,  1.19s/it]

Results in physics has homepage_url and type journal

 48%|█████████████████████████████████▍                                    | 639/1337 [07:28<09:12,  1.26it/s]

IEEE transactions on nuclear science has homepage_url and type journal

 48%|█████████████████████████████████▌                                    | 640/1337 [07:29<08:46,  1.32it/s]

Materials letters has homepage_url and type journal

 48%|█████████████████████████████████▋                                    | 643/1337 [07:31<07:42,  1.50it/s]

Physics open has homepage_url and type journal

 48%|█████████████████████████████████▊                                    | 645/1337 [07:32<09:33,  1.21it/s]

Optical materials has homepage_url and type journal

 48%|█████████████████████████████████▉                                    | 648/1337 [07:34<07:04,  1.62it/s]

Acta IMEKO has homepage_url and type journal

 49%|█████████████████████████████████▉                                    | 649/1337 [07:35<06:43,  1.71it/s]

Journal of environmental chemical engineering has homepage_url and type journal

 49%|██████████████████████████████████▏                                   | 652/1337 [07:36<05:52,  1.94it/s]

Welding international has homepage_url and type journal

 49%|██████████████████████████████████▎                                   | 655/1337 [07:37<05:37,  2.02it/s]

Journal of Asian Ceramic Societies has homepage_url and type journal

 49%|██████████████████████████████████▎                                   | 656/1337 [07:39<08:09,  1.39it/s]

Fuel has homepage_url and type journal

 49%|██████████████████████████████████▍                                   | 658/1337 [07:40<06:56,  1.63it/s]

Analytical letters has homepage_url and type journal

 49%|██████████████████████████████████▌                                   | 660/1337 [07:41<06:04,  1.86it/s]

Chinese Chemical Letters/Chinese chemical letters has homepage_url and type journal

 49%|██████████████████████████████████▌                                   | 661/1337 [07:41<05:53,  1.91it/s]

Heliyon has homepage_url and type journal

 50%|██████████████████████████████████▋                                   | 662/1337 [07:42<05:42,  1.97it/s]

Avtomatizaciâ tehnologičeskih i biznes-processov has homepage_url and type journal

 50%|██████████████████████████████████▋                                   | 663/1337 [07:42<05:36,  2.00it/s]

Meeting abstracts/Meeting abstracts (Electrochemical Society. CD-ROM) has homepage_url and type journal

 50%|██████████████████████████████████▊                                   | 665/1337 [07:43<05:30,  2.03it/s]

Electric power components and systems has homepage_url and type journal

 50%|██████████████████████████████████▊                                   | 666/1337 [07:43<05:24,  2.07it/s]

E3S web of conferences has homepage_url and type journal

 50%|██████████████████████████████████▉                                   | 667/1337 [07:44<05:43,  1.95it/s]

The Journal of the Acoustical Society of America/The journal of the Acoustical Society of America has homepage_url and type journal

 50%|███████████████████████████████████▎                                  | 674/1337 [07:48<06:29,  1.70it/s]

Proceedings of the Nordic Insulation Symposium has homepage_url and type journal

 51%|███████████████████████████████████▍                                  | 676/1337 [07:49<05:59,  1.84it/s]

IEEE transactions on magnetics has homepage_url and type journal

 51%|███████████████████████████████████▍                                  | 678/1337 [07:51<07:42,  1.43it/s]

American journal of physics has homepage_url and type journal

 51%|███████████████████████████████████▌                                  | 680/1337 [07:52<06:26,  1.70it/s]

Procedia manufacturing has homepage_url and type journal

 51%|███████████████████████████████████▊                                  | 683/1337 [07:54<06:34,  1.66it/s]

IEEE Letters on Electromagnetic Compatibility Practice and Applications has homepage_url and type journal

 51%|███████████████████████████████████▊                                  | 684/1337 [07:54<06:21,  1.71it/s]

Journal of magnetism and magnetic materials has homepage_url and type journal

 51%|███████████████████████████████████▉                                  | 687/1337 [07:56<05:33,  1.95it/s]

IET electric power applications has homepage_url and type journal

 52%|████████████████████████████████████▏                                 | 691/1337 [07:58<07:07,  1.51it/s]

Applied optics has homepage_url and type journal

 52%|████████████████████████████████████▍                                 | 697/1337 [08:01<05:42,  1.87it/s]

IEEE transactions on power delivery has homepage_url and type journal

 52%|████████████████████████████████████▌                                 | 698/1337 [08:02<05:27,  1.95it/s]

Inženernyj žurnal: nauka i innovacii has homepage_url and type journal

 53%|████████████████████████████████████▊                                 | 702/1337 [08:04<06:14,  1.69it/s]

Transportation research procedia has homepage_url and type journal

 53%|████████████████████████████████████▊                                 | 704/1337 [08:05<05:39,  1.86it/s]

Journal of cosmetic and laser therapy has homepage_url and type journal

 53%|████████████████████████████████████▉                                 | 705/1337 [08:06<05:34,  1.89it/s]

Journal of the Electrochemical Society has homepage_url and type journal

 53%|█████████████████████████████████████                                 | 707/1337 [08:07<05:35,  1.88it/s]

Thermal spray has homepage_url and type journal

 53%|█████████████████████████████████████                                 | 708/1337 [08:07<05:29,  1.91it/s]

Optik has homepage_url and type journal

 53%|█████████████████████████████████████                                 | 709/1337 [08:08<05:21,  1.95it/s]

International Journal of Electrical Components and Energy Conversion has homepage_url and type journal

 53%|█████████████████████████████████████▏                                | 710/1337 [08:08<05:31,  1.89it/s]

Plasma research express has homepage_url and type journal

 53%|█████████████████████████████████████▏                                | 711/1337 [08:09<05:23,  1.94it/s]

JPhys photonics has homepage_url and type journal

 53%|█████████████████████████████████████▎                                | 712/1337 [08:09<05:26,  1.91it/s]

Solid state electronics letters has homepage_url and type journal

 53%|█████████████████████████████████████▍                                | 715/1337 [08:11<06:01,  1.72it/s]

Tehnìčna elektrodinamìka has homepage_url and type journal

 54%|█████████████████████████████████████▋                                | 719/1337 [08:15<06:49,  1.51it/s]

International journal of innovative technology and exploring engineering has homepage_url and type journal

 54%|█████████████████████████████████████▉                                | 724/1337 [08:17<05:58,  1.71it/s]

Energy storage has homepage_url and type journal

 54%|██████████████████████████████████████                                | 727/1337 [08:19<05:44,  1.77it/s]

ECS transactions has homepage_url and type journal

 55%|██████████████████████████████████████▍                               | 733/1337 [08:23<07:46,  1.29it/s]

Defence Science Journal/Defence science journal has homepage_url and type journal

 56%|███████████████████████████████████████▍                              | 754/1337 [08:35<06:59,  1.39it/s]

Molecular genetics and metabolism has homepage_url and type journal

 56%|███████████████████████████████████████▌                              | 755/1337 [08:36<06:18,  1.54it/s]

Lighting research and technology has homepage_url and type journal

 57%|███████████████████████████████████████▌                              | 756/1337 [08:36<07:12,  1.34it/s]

Springer theses has homepage_url and type book series

 57%|███████████████████████████████████████▋                              | 758/1337 [08:37<05:56,  1.62it/s]

Lecture notes in physics has homepage_url and type book series

 57%|███████████████████████████████████████▉                              | 762/1337 [08:41<08:18,  1.15it/s]

Instruments has homepage_url and type journal

 57%|████████████████████████████████████████                              | 764/1337 [08:42<06:30,  1.47it/s]

Izvestiâ vysših učebnyh zavedenij Rossii. Radioèlektronika has homepage_url and type journal

 57%|████████████████████████████████████████                              | 766/1337 [08:43<05:32,  1.72it/s]

Journal of Engineering Science and Military Technologies /Journal of Engineering Science and Military Technologies has homepage_url and type journal

 58%|████████████████████████████████████████▎                             | 770/1337 [08:46<05:50,  1.62it/s]

International journal on engineering applications has homepage_url and type journal

 58%|████████████████████████████████████████▋                             | 776/1337 [08:49<05:32,  1.69it/s]

Voprosy radioèlektroniki has homepage_url and type journal

 58%|████████████████████████████████████████▊                             | 779/1337 [08:51<05:31,  1.68it/s]

Tehnìčna ìnženerìâ has homepage_url and type journal

 58%|████████████████████████████████████████▉                             | 781/1337 [08:52<04:54,  1.89it/s]

Izvestiâ vysših učebnyh zavedenij. Černaâ metallurgiâ has homepage_url and type journal

 59%|█████████████████████████████████████████▏                            | 786/1337 [08:55<04:39,  1.97it/s]

Annals of nuclear energy has homepage_url and type journal

 59%|█████████████████████████████████████████▏                            | 787/1337 [08:55<04:40,  1.96it/s]

Journal of Engineering Research and Reports has homepage_url and type journal

 59%|█████████████████████████████████████████▎                            | 788/1337 [08:56<04:37,  1.98it/s]

Journal of drug delivery and therapeutics has homepage_url and type journal

 59%|█████████████████████████████████████████▌                            | 794/1337 [08:58<04:22,  2.07it/s]

bioRxiv (Cold Spring Harbor Laboratory) has homepage_url and type repository

 60%|██████████████████████████████████████████                            | 804/1337 [09:03<04:20,  2.04it/s]

IEEE transactions on aerospace and electronic systems has homepage_url and type journal

 60%|██████████████████████████████████████████▏                           | 805/1337 [09:05<06:45,  1.31it/s]

Aerospace science and technology has homepage_url and type journal

 60%|██████████████████████████████████████████▎                           | 807/1337 [09:06<05:28,  1.61it/s]

Journal of aerospace information systems has homepage_url and type journal

 60%|██████████████████████████████████████████▎                           | 808/1337 [09:07<07:03,  1.25it/s]

Safety science has homepage_url and type journal

 61%|██████████████████████████████████████████▎                           | 809/1337 [09:08<08:22,  1.05it/s]

Aerospace has homepage_url and type journal

 61%|██████████████████████████████████████████▍                           | 810/1337 [09:09<07:10,  1.22it/s]

Electronic research archive has homepage_url and type journal

 61%|██████████████████████████████████████████▌                           | 812/1337 [09:10<05:42,  1.53it/s]

Computational intelligence and neuroscience has homepage_url and type journal

 61%|██████████████████████████████████████████▌                           | 813/1337 [09:11<08:07,  1.08it/s]

The aeronautical journal/Aeronautical journal has homepage_url and type journal

 61%|██████████████████████████████████████████▌                           | 814/1337 [09:12<08:19,  1.05it/s]

International journal of aerospace engineering has homepage_url and type journal

 61%|██████████████████████████████████████████▋                           | 816/1337 [09:13<06:13,  1.40it/s]

Journal of Aerospace Technology and Management has homepage_url and type journal

 61%|██████████████████████████████████████████▊                           | 817/1337 [09:14<07:00,  1.24it/s]

Journal of navigation has homepage_url and type journal

 61%|██████████████████████████████████████████▊                           | 818/1337 [09:15<07:28,  1.16it/s]

Imaging science journal/The imaging science journal has homepage_url and type journal

 61%|██████████████████████████████████████████▉                           | 819/1337 [09:17<08:27,  1.02it/s]

Remote sensing has homepage_url and type journal

 62%|███████████████████████████████████████████▏                          | 824/1337 [09:19<04:58,  1.72it/s]

Journal of the Korean Institute of Electromagnetic Engineering and Science has homepage_url and type journal

 62%|███████████████████████████████████████████▏                          | 825/1337 [09:20<06:15,  1.36it/s]

Journal of aerospace engineering has homepage_url and type journal

 62%|███████████████████████████████████████████▎                          | 827/1337 [09:21<05:21,  1.59it/s]

Xibei gongye daxue xuebao has homepage_url and type journal

 62%|███████████████████████████████████████████▎                          | 828/1337 [09:22<04:56,  1.71it/s]

Aircraft engineering and aerospace technology has homepage_url and type journal

 62%|███████████████████████████████████████████▍                          | 829/1337 [09:23<05:27,  1.55it/s]

Measurement + control/Measurement and control has homepage_url and type journal

 62%|███████████████████████████████████████████▌                          | 831/1337 [09:25<07:22,  1.14it/s]

International journal of general systems has homepage_url and type journal

 63%|███████████████████████████████████████████▊                          | 836/1337 [09:28<05:36,  1.49it/s]

INCAS Buletin has homepage_url and type journal

 63%|███████████████████████████████████████████▊                          | 838/1337 [09:29<06:06,  1.36it/s]

Journal of defense modeling and simulation has homepage_url and type journal

 63%|███████████████████████████████████████████▉                          | 840/1337 [09:30<05:08,  1.61it/s]

International journal on artificial intelligence tools has homepage_url and type journal

 63%|████████████████████████████████████████████▏                         | 843/1337 [09:33<07:11,  1.15it/s]

Authorea (Authorea) has homepage_url and type repository

 63%|████████████████████████████████████████████▏                         | 844/1337 [09:34<06:14,  1.32it/s]

Frontiers in aerospace engineering has homepage_url and type journal

 63%|████████████████████████████████████████████▎                         | 846/1337 [09:35<05:00,  1.64it/s]

EURASIP Journal on Advances in Signal Processing has homepage_url and type journal

 64%|████████████████████████████████████████████▌                         | 851/1337 [09:37<04:27,  1.82it/s]

JAREE (Journal on Advanced Research in Electrical Engineering) has homepage_url and type journal

 64%|████████████████████████████████████████████▊                         | 855/1337 [09:40<05:08,  1.56it/s]

International journal of automation and control has homepage_url and type journal

 64%|████████████████████████████████████████████▊                         | 856/1337 [09:41<04:54,  1.63it/s]

Ozbroênnâ ta vìjsʹkova tehnìka has homepage_url and type journal

 64%|████████████████████████████████████████████▉                         | 859/1337 [09:42<04:54,  1.63it/s]

Navigation has homepage_url and type journal

 65%|█████████████████████████████████████████████▏                        | 864/1337 [09:45<03:54,  2.02it/s]

Problemy Mechatroniki has homepage_url and type journal

 65%|█████████████████████████████████████████████▍                        | 867/1337 [09:47<05:00,  1.56it/s]

INSIST (International Series on Integrated Science and Technology) has homepage_url and type journal

 65%|█████████████████████████████████████████████▌                        | 870/1337 [09:49<04:17,  1.81it/s]

SN applied sciences/SN Applied Sciences has homepage_url and type journal

 65%|█████████████████████████████████████████████▌                        | 871/1337 [09:49<04:07,  1.88it/s]

Problemy Techniki Uzbrojenia i Radiolokacji has homepage_url and type journal

 65%|█████████████████████████████████████████████▋                        | 872/1337 [09:50<04:04,  1.90it/s]

International game theory review has homepage_url and type journal

 65%|█████████████████████████████████████████████▊                        | 874/1337 [09:51<04:15,  1.81it/s]

Proceedings in applied mathematics and mechanics has homepage_url and type journal

 65%|█████████████████████████████████████████████▊                        | 875/1337 [09:52<05:59,  1.28it/s]

Jurnal pertahanan/Jurnal Pertahanan has homepage_url and type journal

 66%|█████████████████████████████████████████████▊                        | 876/1337 [09:59<20:40,  2.69s/it]

Defence and peace economics has homepage_url and type journal

 66%|██████████████████████████████████████████████                        | 879/1337 [10:03<12:44,  1.67s/it]

Journal of control and decision has homepage_url and type journal

 66%|██████████████████████████████████████████████▎                       | 884/1337 [10:05<05:18,  1.42it/s]

Han'gug jeonja'pa haghoe nonmunji/The Journal of Korean institute of electromagnetic engineering and science has homepage_url and type journal

 66%|██████████████████████████████████████████████▍                       | 886/1337 [10:07<05:23,  1.40it/s]

Barekeng has homepage_url and type journal

 66%|██████████████████████████████████████████████▌                       | 889/1337 [10:08<04:11,  1.78it/s]

Open Astronomy has homepage_url and type journal

 67%|██████████████████████████████████████████████▊                       | 894/1337 [10:11<03:49,  1.93it/s]

International journal of enterprise information systems has homepage_url and type journal

 67%|██████████████████████████████████████████████▉                       | 897/1337 [10:12<03:38,  2.01it/s]

TsAGI science journal has homepage_url and type journal

 67%|███████████████████████████████████████████████                       | 898/1337 [10:13<03:38,  2.01it/s]

Zeszyty Naukowe Akademii Marynarki Wojennej/Zeszyty Naukowe - Akademia Marynarki Wojennej im. Bohaterów Westerplatte has homepage_url and type journal

 67%|███████████████████████████████████████████████▏                      | 902/1337 [10:14<03:36,  2.01it/s]

Advances in Military Technology has homepage_url and type journal

 68%|███████████████████████████████████████████████▍                      | 906/1337 [10:16<03:35,  2.00it/s]

Vortex has homepage_url and type journal

 68%|███████████████████████████████████████████████▌                      | 909/1337 [10:18<03:28,  2.05it/s]

American journal of aerospace engineering has homepage_url and type journal

 68%|███████████████████████████████████████████████▊                      | 914/1337 [10:20<03:24,  2.07it/s]

International journal of computers and communications has homepage_url and type journal

 69%|███████████████████████████████████████████████▉                      | 916/1337 [10:21<03:20,  2.10it/s]

Advances in Manufacturing Science and Technology has homepage_url and type journal

 69%|████████████████████████████████████████████████                      | 919/1337 [10:23<03:16,  2.13it/s]

IEEE transactions on geoscience and remote sensing has homepage_url and type journal

 69%|████████████████████████████████████████████████▏                     | 920/1337 [10:23<03:20,  2.08it/s]

IEEE geoscience and remote sensing letters has homepage_url and type journal

 69%|████████████████████████████████████████████████▏                     | 921/1337 [10:24<04:13,  1.64it/s]

IEEE journal of selected topics in applied earth observations and remote sensing has homepage_url and type journal

 69%|████████████████████████████████████████████████▎                     | 922/1337 [10:25<04:06,  1.68it/s]

Cognitive computation has homepage_url and type journal

 69%|████████████████████████████████████████████████▎                     | 923/1337 [10:26<05:12,  1.33it/s]

Journal of network and computer applications has homepage_url and type journal

 69%|████████████████████████████████████████████████▍                     | 925/1337 [10:27<04:16,  1.61it/s]

IEEE aerospace and electronic systems magazine has homepage_url and type journal

 69%|████████████████████████████████████████████████▍                     | 926/1337 [10:27<03:59,  1.72it/s]

IEEE wireless communications letters has homepage_url and type journal

 69%|████████████████████████████████████████████████▌                     | 927/1337 [10:28<03:53,  1.76it/s]

International journal of remote sensing has homepage_url and type journal

 69%|████████████████████████████████████████████████▌                     | 928/1337 [10:28<03:40,  1.85it/s]

IEEE journal of oceanic engineering has homepage_url and type journal

 69%|████████████████████████████████████████████████▋                     | 929/1337 [10:29<03:33,  1.91it/s]

Journal of applied remote sensing has homepage_url and type journal

 70%|████████████████████████████████████████████████▋                     | 930/1337 [10:30<05:16,  1.29it/s]

Signal processing has homepage_url and type journal

 70%|████████████████████████████████████████████████▋                     | 931/1337 [10:31<05:30,  1.23it/s]

IEEE transactions on image processing has homepage_url and type journal

 70%|████████████████████████████████████████████████▊                     | 932/1337 [10:32<04:50,  1.39it/s]

IEEE signal processing letters has homepage_url and type journal

 70%|████████████████████████████████████████████████▊                     | 933/1337 [10:32<04:46,  1.41it/s]

Digital signal processing has homepage_url and type journal

 70%|████████████████████████████████████████████████▉                     | 934/1337 [10:33<04:19,  1.55it/s]

Remote sensing letters has homepage_url and type journal

 70%|█████████████████████████████████████████████████                     | 936/1337 [10:34<03:41,  1.81it/s]

Journal of electronic imaging has homepage_url and type journal

 70%|█████████████████████████████████████████████████                     | 937/1337 [10:34<03:40,  1.81it/s]

Journal of electromagnetic waves and applications has homepage_url and type journal

 70%|█████████████████████████████████████████████████▏                    | 940/1337 [10:36<03:20,  1.98it/s]

IEEE transactions on information forensics and security has homepage_url and type journal

 70%|█████████████████████████████████████████████████▎                    | 941/1337 [10:37<04:12,  1.57it/s]

Journal of visual communication and image representation has homepage_url and type journal

 70%|█████████████████████████████████████████████████▎                    | 942/1337 [10:37<03:55,  1.68it/s]

IEEE transactions on circuits and systems for video technology has homepage_url and type journal

 71%|█████████████████████████████████████████████████▎                    | 943/1337 [10:38<03:41,  1.78it/s]

Hanguk gunsa gwahak gisul hakoeji/Han'gug gunsa gwahag gi'sul haghoeji has homepage_url and type journal

 71%|█████████████████████████████████████████████████▍                    | 944/1337 [10:39<04:36,  1.42it/s]

ISPRS journal of photogrammetry and remote sensing has homepage_url and type journal

 71%|█████████████████████████████████████████████████▍                    | 945/1337 [10:39<04:17,  1.52it/s]

IET signal processing has homepage_url and type journal

 71%|█████████████████████████████████████████████████▌                    | 946/1337 [10:40<03:56,  1.65it/s]

Scientific programming has homepage_url and type journal

 71%|█████████████████████████████████████████████████▌                    | 947/1337 [10:41<04:35,  1.42it/s]

Integrated ferroelectrics has homepage_url and type journal

 71%|█████████████████████████████████████████████████▋                    | 949/1337 [10:42<05:08,  1.26it/s]

Optical engineering has homepage_url and type journal

 71%|█████████████████████████████████████████████████▋                    | 950/1337 [10:43<04:31,  1.42it/s]

International journal of antennas and propagation has homepage_url and type journal

 71%|█████████████████████████████████████████████████▊                    | 951/1337 [10:44<05:46,  1.11it/s]

Computer communications has homepage_url and type journal

 71%|█████████████████████████████████████████████████▊                    | 952/1337 [10:45<05:06,  1.26it/s]

Applied artificial intelligence has homepage_url and type journal

 71%|█████████████████████████████████████████████████▉                    | 953/1337 [10:45<04:34,  1.40it/s]

IEEE journal on miniaturization for air and space systems has homepage_url and type journal

 72%|██████████████████████████████████████████████████▋                   | 968/1337 [10:54<03:52,  1.59it/s]

Cybernetics and Information Technologies has homepage_url and type journal

 73%|███████████████████████████████████████████████████                   | 976/1337 [10:58<03:02,  1.98it/s]

Iraqi journal of science has homepage_url and type journal

 73%|███████████████████████████████████████████████████▏                  | 977/1337 [10:58<03:03,  1.96it/s]

International journal of optics has homepage_url and type journal

 73%|███████████████████████████████████████████████████▎                  | 979/1337 [10:59<03:07,  1.91it/s]

Physical communication has homepage_url and type journal

 73%|███████████████████████████████████████████████████▎                  | 981/1337 [11:01<04:07,  1.44it/s]

IEICE transactions on electronics has homepage_url and type journal

 73%|███████████████████████████████████████████████████▍                  | 982/1337 [11:01<03:47,  1.56it/s]

PeerJ. Computer science has homepage_url and type journal

 74%|███████████████████████████████████████████████████▍                  | 983/1337 [11:02<04:26,  1.33it/s]

Future internet has homepage_url and type journal

 74%|███████████████████████████████████████████████████▌                  | 985/1337 [11:03<03:37,  1.62it/s]

Proceedings of meetings on acoustics has homepage_url and type journal

 74%|███████████████████████████████████████████████████▋                  | 987/1337 [11:05<04:03,  1.44it/s]

Journal of mathematics has homepage_url and type journal

 74%|███████████████████████████████████████████████████▉                  | 993/1337 [11:08<03:06,  1.84it/s]

Advances in multimedia has homepage_url and type journal

 74%|████████████████████████████████████████████████████▏                 | 996/1337 [11:09<03:02,  1.87it/s]

IEEE journal on multiscale and multiphysics computational techniques has homepage_url and type journal

 75%|████████████████████████████████████████████████████▎                 | 999/1337 [11:11<03:08,  1.79it/s]

International journal of cloud computing has homepage_url and type journal

 75%|███████████████████████████████████████████████████▋                 | 1001/1337 [11:13<03:55,  1.43it/s]

Wireless communications and mobile computing has homepage_url and type journal

 75%|███████████████████████████████████████████████████▋                 | 1002/1337 [11:13<03:35,  1.55it/s]

T-comm has homepage_url and type journal

 75%|███████████████████████████████████████████████████▊                 | 1005/1337 [11:15<02:58,  1.86it/s]

Springer optimization and its applications has homepage_url and type book series

 75%|████████████████████████████████████████████████████                 | 1008/1337 [11:16<02:48,  1.95it/s]

Journal of Interdisciplinary Mathematics/Journal of interdisciplinary mathematics has homepage_url and type journal

 76%|████████████████████████████████████████████████████▌                | 1019/1337 [11:21<02:30,  2.12it/s]

Journal of electromagnetic engineering and science has homepage_url and type journal

 76%|████████████████████████████████████████████████████▋                | 1022/1337 [11:23<02:49,  1.85it/s]

International journal of information and communication technology has homepage_url and type journal

 77%|████████████████████████████████████████████████████▉                | 1025/1337 [11:25<03:26,  1.51it/s]

Security and communication networks has homepage_url and type journal

 77%|█████████████████████████████████████████████████████                | 1028/1337 [11:27<02:45,  1.87it/s]

Journal of Scientific Research of the Banaras Hindu University has homepage_url and type journal

 77%|█████████████████████████████████████████████████████▍               | 1035/1337 [11:31<03:29,  1.44it/s]

IET biometrics has homepage_url and type journal

 78%|█████████████████████████████████████████████████████▌               | 1038/1337 [11:33<02:42,  1.84it/s]

Thin-walled structures has homepage_url and type journal

 78%|█████████████████████████████████████████████████████▌               | 1039/1337 [11:34<03:40,  1.35it/s]

Journal of aircraft and spacecraft technology has homepage_url and type journal

 78%|█████████████████████████████████████████████████████▋               | 1040/1337 [11:35<04:41,  1.05it/s]

Quarterly journal of the Royal Meteorological Society has homepage_url and type journal

 78%|█████████████████████████████████████████████████████▋               | 1041/1337 [11:36<05:16,  1.07s/it]

International affairs has homepage_url and type journal

 78%|█████████████████████████████████████████████████████▊               | 1042/1337 [11:37<04:30,  1.09it/s]

Comparative strategy has homepage_url and type journal

 78%|█████████████████████████████████████████████████████▉               | 1044/1337 [11:39<04:41,  1.04it/s]

Defence studies has homepage_url and type journal

 78%|█████████████████████████████████████████████████████▉               | 1046/1337 [11:40<03:30,  1.38it/s]

Contemporary security policy has homepage_url and type journal

 78%|██████████████████████████████████████████████████████               | 1047/1337 [11:40<03:08,  1.54it/s]

Cold war history has homepage_url and type journal

 78%|██████████████████████████████████████████████████████               | 1048/1337 [11:41<02:55,  1.65it/s]

Morbidity and mortality weekly report has homepage_url and type journal

 78%|██████████████████████████████████████████████████████▏              | 1049/1337 [11:41<02:45,  1.74it/s]

Middle East policy has homepage_url and type journal

 79%|██████████████████████████████████████████████████████▏              | 1050/1337 [11:43<03:48,  1.25it/s]

International security has homepage_url and type journal

 79%|██████████████████████████████████████████████████████▏              | 1051/1337 [11:44<04:17,  1.11it/s]

Omega has homepage_url and type journal

 79%|██████████████████████████████████████████████████████▎              | 1052/1337 [11:45<04:40,  1.02it/s]

Astrodynamics has homepage_url and type journal

 79%|██████████████████████████████████████████████████████▍              | 1054/1337 [11:46<03:27,  1.36it/s]

Journal of peace research has homepage_url and type journal

 79%|██████████████████████████████████████████████████████▌              | 1057/1337 [11:47<02:39,  1.75it/s]

Space policy has homepage_url and type journal

 79%|██████████████████████████████████████████████████████▌              | 1058/1337 [11:49<03:37,  1.28it/s]

Sports has homepage_url and type journal

 79%|██████████████████████████████████████████████████████▋              | 1060/1337 [11:50<02:46,  1.66it/s]

Journal for peace and nuclear disarmament has homepage_url and type journal

 79%|██████████████████████████████████████████████████████▊              | 1061/1337 [11:51<03:25,  1.34it/s]

Ìstorìâ nauki ì tehnìki has homepage_url and type journal

 80%|██████████████████████████████████████████████████████▊              | 1063/1337 [11:52<03:17,  1.39it/s]

Astropolitics has homepage_url and type journal

 80%|██████████████████████████████████████████████████████▉              | 1064/1337 [11:53<02:51,  1.59it/s]

Journal of space safety engineering has homepage_url and type journal

 80%|███████████████████████████████████████████████████████              | 1067/1337 [11:55<02:55,  1.54it/s]

Historia i Polityka has homepage_url and type journal

 80%|███████████████████████████████████████████████████████▏             | 1069/1337 [11:56<02:38,  1.69it/s]

The Journal of American history has homepage_url and type journal

 80%|███████████████████████████████████████████████████████▎             | 1071/1337 [11:57<02:24,  1.84it/s]

Tikrit journal for political science/Mağallaẗ Tikrīt li-l-ʻulūm al-siyāsiyyaẗ has homepage_url and type journal

 80%|███████████████████████████████████████████████████████▌             | 1076/1337 [12:00<03:34,  1.22it/s]

Domes has homepage_url and type journal

 81%|███████████████████████████████████████████████████████▋             | 1079/1337 [12:02<02:32,  1.70it/s]

International journal of pattern recognition and artificial intelligence has homepage_url and type journal

 81%|███████████████████████████████████████████████████████▉             | 1083/1337 [12:04<02:41,  1.57it/s]

Journal of Slavic military studies/The Journal of Slavic military studies has homepage_url and type journal

 81%|███████████████████████████████████████████████████████▉             | 1084/1337 [12:05<02:31,  1.67it/s]

The Physics teacher/The physics teacher has homepage_url and type journal

 81%|███████████████████████████████████████████████████████▉             | 1085/1337 [12:06<03:18,  1.27it/s]

Health security has homepage_url and type journal

 81%|████████████████████████████████████████████████████████             | 1086/1337 [12:07<03:51,  1.08it/s]

Water resources research has homepage_url and type journal

 81%|████████████████████████████████████████████████████████             | 1087/1337 [12:08<03:17,  1.27it/s]

Vestnik MGIMO-universiteta has homepage_url and type journal

 81%|████████████████████████████████████████████████████████▏            | 1088/1337 [12:08<02:53,  1.43it/s]

Meždunarodnaâ analitika has homepage_url and type journal

 81%|████████████████████████████████████████████████████████▏            | 1089/1337 [12:09<02:36,  1.58it/s]

Security dialogue has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▎            | 1090/1337 [12:09<02:30,  1.64it/s]

Herald of the Russian Academy of Sciences has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▎            | 1091/1337 [12:10<02:22,  1.72it/s]

Intellektualʹnye sistemy v proizvodstve has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▍            | 1093/1337 [12:12<03:01,  1.34it/s]

Scientific Bulletin has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▌            | 1095/1337 [12:13<02:26,  1.66it/s]

Security and Defence Quarterly has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▌            | 1096/1337 [12:13<02:17,  1.76it/s]

Defense and security analysis has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▌            | 1097/1337 [12:14<02:13,  1.79it/s]

Daedalus has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▋            | 1098/1337 [12:14<02:12,  1.80it/s]

Rossiâ i Amerika v XXI veke has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▋            | 1099/1337 [12:15<02:08,  1.85it/s]

International journal of multicultural and multireligious understanding has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▊            | 1100/1337 [12:15<02:05,  1.89it/s]

Politeja has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▊            | 1101/1337 [12:16<02:08,  1.84it/s]

Journal of strategic studies/The Journal of strategic studies has homepage_url and type journal

 82%|████████████████████████████████████████████████████████▊            | 1102/1337 [12:17<02:47,  1.40it/s]

International journal has homepage_url and type journal

 83%|████████████████████████████████████████████████████████▉            | 1104/1337 [12:18<02:52,  1.35it/s]

Kosmìčna nauka ì tehnologìâ has homepage_url and type journal

 83%|█████████████████████████████████████████████████████████            | 1106/1337 [12:20<02:31,  1.53it/s]

Physics today has homepage_url and type journal

 83%|█████████████████████████████████████████████████████████▏           | 1107/1337 [12:20<02:19,  1.65it/s]

Australian journal of maritime and ocean affairs has homepage_url and type journal

 83%|█████████████████████████████████████████████████████████▎           | 1110/1337 [12:22<02:04,  1.83it/s]

Modern approaches in solid earth sciences has homepage_url and type book series

 83%|█████████████████████████████████████████████████████████▎           | 1111/1337 [12:22<02:00,  1.87it/s]

Revista historia autónoma has homepage_url and type journal

 83%|█████████████████████████████████████████████████████████▍           | 1112/1337 [12:23<01:58,  1.91it/s]

The international history review/International history review has homepage_url and type journal

 83%|█████████████████████████████████████████████████████████▍           | 1113/1337 [12:23<01:54,  1.96it/s]

Angelaki has homepage_url and type journal

 84%|█████████████████████████████████████████████████████████▋           | 1117/1337 [12:25<01:51,  1.97it/s]

Journal of Education on Social Science has homepage_url and type journal

 84%|█████████████████████████████████████████████████████████▋           | 1118/1337 [12:26<01:47,  2.03it/s]

Studia Historiae Scientiarum has homepage_url and type journal

 84%|█████████████████████████████████████████████████████████▊           | 1120/1337 [12:27<01:44,  2.07it/s]

Pacific focus/Pacific Focus has homepage_url and type journal

 84%|█████████████████████████████████████████████████████████▉           | 1123/1337 [12:29<02:04,  1.72it/s]

Scandinavian Journal of Military Studies has homepage_url and type journal

 85%|██████████████████████████████████████████████████████████▎          | 1131/1337 [12:33<02:05,  1.64it/s]

IEEE industrial electronics magazine has homepage_url and type journal

 85%|██████████████████████████████████████████████████████████▍          | 1132/1337 [12:38<07:06,  2.08s/it]

International Studies has homepage_url and type journal

 85%|██████████████████████████████████████████████████████████▌          | 1134/1337 [12:40<04:39,  1.38s/it]

Fiziko-himičeskaâ kinetika v gazovoj dinamike has homepage_url and type journal

 85%|██████████████████████████████████████████████████████████▌          | 1135/1337 [12:41<04:28,  1.33s/it]

Maritime Affairs/Maritime affairs has homepage_url and type journal

 85%|██████████████████████████████████████████████████████████▋          | 1136/1337 [12:42<04:26,  1.33s/it]

Istoriâ has homepage_url and type journal

 85%|██████████████████████████████████████████████████████████▊          | 1139/1337 [12:45<03:24,  1.03s/it]

Ante Portas has homepage_url and type journal

 85%|██████████████████████████████████████████████████████████▊          | 1140/1337 [12:46<02:52,  1.14it/s]

Dinamika global/Dinamika Global has homepage_url and type journal

 85%|██████████████████████████████████████████████████████████▉          | 1143/1337 [12:48<02:13,  1.46it/s]

Globalʹnaâ âdernaâ bezopasnostʹ has homepage_url and type journal

 86%|███████████████████████████████████████████████████████████▏         | 1147/1337 [12:50<01:48,  1.75it/s]

The Western historical quarterly has homepage_url and type journal

 86%|███████████████████████████████████████████████████████████▎         | 1149/1337 [12:51<01:57,  1.59it/s]

Journal of Contemporary Studies has homepage_url and type journal

 86%|███████████████████████████████████████████████████████████▍         | 1152/1337 [12:52<01:36,  1.92it/s]

National security journal has homepage_url and type journal

 86%|███████████████████████████████████████████████████████████▌         | 1154/1337 [12:54<02:13,  1.37it/s]

IEEE transactions on signal processing has homepage_url and type journal

 86%|███████████████████████████████████████████████████████████▌         | 1155/1337 [12:55<02:01,  1.49it/s]

Journal of lightwave technology has homepage_url and type journal

 86%|███████████████████████████████████████████████████████████▋         | 1156/1337 [12:55<01:51,  1.62it/s]

IET wireless sensor systems has homepage_url and type journal

 87%|███████████████████████████████████████████████████████████▋         | 1157/1337 [12:56<02:24,  1.25it/s]

Radio science has homepage_url and type journal

 87%|███████████████████████████████████████████████████████████▊         | 1158/1337 [12:57<02:05,  1.43it/s]

IEEE Open Journal of Antennas and Propagation has homepage_url and type journal

 87%|███████████████████████████████████████████████████████████▉         | 1162/1337 [12:59<01:36,  1.82it/s]

EURASIP Journal on wireless communications and networking has homepage_url and type journal

 87%|████████████████████████████████████████████████████████████         | 1165/1337 [13:00<01:28,  1.94it/s]

Entropy has homepage_url and type journal

 87%|████████████████████████████████████████████████████████████▎        | 1168/1337 [13:02<01:26,  1.95it/s]

IEEE sensors letters has homepage_url and type journal

 88%|████████████████████████████████████████████████████████████▌        | 1173/1337 [13:04<01:22,  2.00it/s]

High-confidence computing has homepage_url and type journal

 88%|████████████████████████████████████████████████████████████▊        | 1179/1337 [13:07<01:17,  2.03it/s]

IFIP advances in information and communication technology has homepage_url and type book series

 88%|█████████████████████████████████████████████████████████████        | 1182/1337 [13:09<01:16,  2.02it/s]

China Communications has homepage_url and type journal

 88%|█████████████████████████████████████████████████████████████        | 1183/1337 [13:10<01:56,  1.32it/s]

International journal of electronics has homepage_url and type journal

 89%|█████████████████████████████████████████████████████████████▎       | 1188/1337 [13:15<03:05,  1.25s/it]

World journal of engineering and technology has homepage_url and type journal

 89%|█████████████████████████████████████████████████████████████▌       | 1193/1337 [13:19<02:06,  1.14it/s]

Engineering reports has homepage_url and type journal

 90%|██████████████████████████████████████████████████████████████▏      | 1206/1337 [13:26<01:03,  2.06it/s]

The European physical journal plus has homepage_url and type journal

 90%|██████████████████████████████████████████████████████████████▎      | 1207/1337 [13:26<01:06,  1.96it/s]

Canadian journal of physics has homepage_url and type journal

 90%|██████████████████████████████████████████████████████████████▎      | 1208/1337 [13:27<01:04,  2.01it/s]

Journal of applied crystallography has homepage_url and type journal

 90%|██████████████████████████████████████████████████████████████▍      | 1209/1337 [13:27<01:04,  1.99it/s]

Journal of synchrotron radiation has homepage_url and type journal

 91%|██████████████████████████████████████████████████████████████▍      | 1210/1337 [13:28<01:19,  1.59it/s]

Science has homepage_url and type journal

 91%|██████████████████████████████████████████████████████████████▍      | 1211/1337 [13:29<01:44,  1.21it/s]

Applied radiation and isotopes has homepage_url and type journal

 91%|██████████████████████████████████████████████████████████████▌      | 1213/1337 [13:31<01:49,  1.13it/s]

Synchrotron radiation news has homepage_url and type journal

 91%|██████████████████████████████████████████████████████████████▋      | 1214/1337 [13:32<01:35,  1.29it/s]

IUCrJ has homepage_url and type journal

 91%|██████████████████████████████████████████████████████████████▊      | 1216/1337 [13:33<01:16,  1.59it/s]

Journal of the Physical Society of Japan has homepage_url and type journal

 91%|██████████████████████████████████████████████████████████████▉      | 1219/1337 [13:34<01:04,  1.84it/s]

Bulletin of the Russian Academy of Sciences. Physics has homepage_url and type journal

 91%|██████████████████████████████████████████████████████████████▉      | 1220/1337 [13:35<01:02,  1.89it/s]

Electronic structure has homepage_url and type journal

 91%|███████████████████████████████████████████████████████████████      | 1221/1337 [13:36<01:26,  1.35it/s]

Monthly Notices of the Royal Astronomical Society has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▏     | 1224/1337 [13:38<01:29,  1.27it/s]

Zeitschrift für physikalische Chemie has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▎     | 1226/1337 [13:39<01:11,  1.54it/s]

IEEE communications magazine has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▎     | 1227/1337 [13:39<01:05,  1.67it/s]

IEEE communications letters has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▎     | 1228/1337 [13:40<01:01,  1.77it/s]

IEEE journal of selected topics in quantum electronics has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▍     | 1229/1337 [13:40<00:58,  1.85it/s]

IEEE geoscience and remote sensing magazine has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▍     | 1230/1337 [13:42<01:15,  1.42it/s]

Optica has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▌     | 1231/1337 [13:42<01:08,  1.55it/s]

IEEE transactions on cognitive communications and networking/IEEE Transactions on Cognitive Communications and Networking has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▌     | 1232/1337 [13:43<01:03,  1.67it/s]

IEEE microwave magazine has homepage_url and type journal

 92%|███████████████████████████████████████████████████████████████▋     | 1235/1337 [13:44<00:53,  1.92it/s]

Transactions on emerging telecommunications technologies has homepage_url and type journal

 93%|███████████████████████████████████████████████████████████████▉     | 1239/1337 [13:46<00:47,  2.06it/s]

International journal of satellite communications and networking has homepage_url and type journal

 93%|████████████████████████████████████████████████████████████████     | 1241/1337 [13:47<00:47,  2.04it/s]

Sadhana/Sādhanā has homepage_url and type journal

 93%|████████████████████████████████████████████████████████████████     | 1242/1337 [13:48<01:15,  1.25it/s]

Bioprocess engineering has homepage_url and type journal

 93%|████████████████████████████████████████████████████████████████▏    | 1244/1337 [13:49<00:58,  1.59it/s]

Sučasnì ìnformacìjnì sistemi has homepage_url and type journal

 93%|████████████████████████████████████████████████████████████████▎    | 1245/1337 [13:50<00:55,  1.66it/s]

IT professional has homepage_url and type journal

 93%|████████████████████████████████████████████████████████████████▎    | 1246/1337 [13:50<00:54,  1.68it/s]

IET communications has homepage_url and type journal

 94%|████████████████████████████████████████████████████████████████▋    | 1254/1337 [13:55<00:46,  1.80it/s]

IEICE transactions on information and systems has homepage_url and type journal

 94%|████████████████████████████████████████████████████████████████▊    | 1257/1337 [13:57<00:52,  1.52it/s]

Seonjin gukbang yeongu has homepage_url and type journal

 94%|████████████████████████████████████████████████████████████████▉    | 1259/1337 [13:58<00:46,  1.69it/s]

International journal of numerical modelling has homepage_url and type journal

 94%|█████████████████████████████████████████████████████████████████▏   | 1263/1337 [14:01<00:58,  1.27it/s]

Journal of computer and communications has homepage_url and type journal

 95%|█████████████████████████████████████████████████████████████████▍   | 1269/1337 [14:05<00:37,  1.79it/s]

Vojnotehnički glasnik has homepage_url and type journal

 95%|█████████████████████████████████████████████████████████████████▋   | 1272/1337 [14:07<00:41,  1.57it/s]

Traitement du signal/TS. Traitement du signal has homepage_url and type journal

 96%|██████████████████████████████████████████████████████████████████▏  | 1283/1337 [14:12<00:26,  2.01it/s]

Inžiniring i tehnologii has homepage_url and type journal

 96%|██████████████████████████████████████████████████████████████████▎  | 1284/1337 [14:12<00:26,  2.02it/s]

Revista brasileira de aplicações de vácuo has homepage_url and type journal

 96%|██████████████████████████████████████████████████████████████████▍  | 1287/1337 [14:15<00:39,  1.26it/s]

European science has homepage_url and type journal

 97%|██████████████████████████████████████████████████████████████████▋  | 1293/1337 [14:20<00:35,  1.22it/s]

Sistemi obrobki ìnformacìï has homepage_url and type journal

 97%|██████████████████████████████████████████████████████████████████▊  | 1295/1337 [14:21<00:27,  1.55it/s]

European journal of applied physics has homepage_url and type journal

 97%|██████████████████████████████████████████████████████████████████▉  | 1297/1337 [14:22<00:23,  1.69it/s]

Springer proceedings in complexity has homepage_url and type book series

 97%|███████████████████████████████████████████████████████████████████▏ | 1303/1337 [14:26<00:28,  1.21it/s]

Materials research proceedings has homepage_url and type journal

 98%|███████████████████████████████████████████████████████████████████▎ | 1305/1337 [14:27<00:21,  1.47it/s]

Vestnik Donskogo gosudarstvennogo tehničeskogo universiteta has homepage_url and type journal

 98%|███████████████████████████████████████████████████████████████████▍ | 1307/1337 [14:29<00:23,  1.27it/s]

European journal of operational research has homepage_url and type journal

 98%|███████████████████████████████████████████████████████████████████▌ | 1308/1337 [14:30<00:24,  1.17it/s]

IEEE systems journal has homepage_url and type journal

 98%|███████████████████████████████████████████████████████████████████▌ | 1309/1337 [14:31<00:26,  1.05it/s]

Journal of military studies has homepage_url and type journal

 98%|███████████████████████████████████████████████████████████████████▌ | 1310/1337 [14:32<00:22,  1.19it/s]

Journal of the Operational Research Society has homepage_url and type journal

 98%|███████████████████████████████████████████████████████████████████▋ | 1312/1337 [14:33<00:16,  1.48it/s]

Statistical computation and simulation/Journal of statistical computation and simulation has homepage_url and type journal

 98%|███████████████████████████████████████████████████████████████████▊ | 1315/1337 [14:35<00:12,  1.82it/s]

ACM computing surveys has homepage_url and type journal

 98%|███████████████████████████████████████████████████████████████████▉ | 1316/1337 [14:35<00:11,  1.88it/s]

Journal on Baltic Security./Journal on Baltic security has homepage_url and type journal

 99%|████████████████████████████████████████████████████████████████████▏| 1322/1337 [14:38<00:08,  1.80it/s]

Alexandria Engineering Journal /Alexandria Engineering Journal has homepage_url and type journal

 99%|████████████████████████████████████████████████████████████████████▋| 1330/1337 [14:43<00:04,  1.68it/s]

Frontiers in space technologies has homepage_url and type journal

100%|████████████████████████████████████████████████████████████████████▋| 1331/1337 [14:44<00:03,  1.74it/s]

International journal of computational methods and experimental measurements has homepage_url and type journal

100%|████████████████████████████████████████████████████████████████████▉| 1335/1337 [14:46<00:01,  1.89it/s]

Bulletin of "Carol I" National Defense University has homepage_url and type journal

100%|████████████████████████████████████████████████████████████████████▉| 1336/1337 [14:47<00:00,  1.30it/s]

Aviation has homepage_url and type journal

100%|█████████████████████████████████████████████████████████████████████| 1337/1337 [14:48<00:00,  1.51it/s]

Sistemi ozbroênnâ ì vìjsʹkova tehnìka has homepage_url and type journal